### ISSUE TITLE
Erroneous stats on failure

### ISSUE THREAD

**Issue by yesman82** [sitespeedio/sitespeed.io#689] opened 2015-06-15 13:30 UTC
Hi,

I'm running Sitespeed.io with Chrome in an Xvfb display as Jenkins job on a Debian server and every now and then the tests fails with a "url timed out" or "ECONNREFUSED" error in conjunction with "Killed the Chromedriver instance because Chrome/driver was hanging". But these errors don't bother me. What annoys me is that graphite/grafana shows peaks in its graphs when these errors occur.

![Grafana](https://cloud.githubusercontent.com/assets/550213/8160171/a5a81698-136d-11e5-8694-261cd426af90.png)

The command being executed within the Xvfb display server by a Jenkins job:
```sh
cat >> urls.txt << EOF
http://www.example.com
http://www.example.com/somepath/
EOF

# run sitespeed
sitespeed.io -f urls.txt -b chrome -n 3 -d 0 --graphiteHost localhost --graphiteData "pagemetrics,timings" --no-html --noColor
```
The corresponding console output with error
```
Started by timer
Building in workspace /var/lib/jenkins/jobs/sitespeed.io 01 example.com/workspace
Xvfb starting$ /usr/bin/Xvfb :1 -screen 0 1024x768x24 -fbdir /var/lib/jenkins/xvfb-694-5497594089782556456.fbdir
[workspace] $ /bin/bash /tmp/hudson2520097783305836190.sh
jenkins
info: OS: 'linux 3.2.0-4-amd64', Node.js: 'v0.10.38', sitespeed.io: '3.6.1', PhantomJS: '1.9.8', java: '1.7.0_79', browsertime: '0.9.7'
info: Will analyze 2 pages
info: Running YSlow for http://www.example.com [phantomjs]
info: Running YSlow for http://www.example.com/somepath/ [phantomjs]
info: Starting proxy on port 2001, will wait at most 15000 ms
info: Queueing browsertime for http://www.example.com chrome
info: Queueing browsertime for http://www.example.com/somepath/ chrome
info: Running browsertime for chrome http://www.example.com
info: Fetching http://www.example.com (1 of 3)
info: Killed the Chromedriver instance because Chrome/driver was hanging.
error: [Error: ECONNREFUSED connect ECONNREFUSED]
error: Error running browsertime: [Error: ECONNREFUSED connect ECONNREFUSED]
info: Running browsertime for chrome http://www.example.com/somepath/
info: Fetching http://www.example.com/somepath/ (1 of 3)
info: Fetching http://www.example.com/somepath/ (2 of 3)
info: Fetching http://www.example.com/somepath/ (3 of 3)
info: Storing /var/lib/jenkins/jobs/sitespeed.io 01 example.com/workspace/sitespeed-result/urls.txt/2015-06-15-13-33-02/data/har/chrome/www.example.com-somepath-.har
info: Storing /var/lib/jenkins/jobs/sitespeed.io 01 example.com/workspace/sitespeed-result/urls.txt/2015-06-15-13-33-02/data/browsertime/chrome/www.example.com-somepath--browsertime.json
info: Stopping proxy
info: Done analyzing urls
info: Sending data to Graphite host:localhost port:2003
info: Wrote results to /var/lib/jenkins/jobs/sitespeed.io 01 example.com/workspace/sitespeed-result/urls.txt/2015-06-15-13-33-02
info: The analyze took 5 minutes (282 seconds)
/tmp ~/jobs/sitespeed.io 01 example.com/workspace
~/jobs/sitespeed.io 01 example.com/workspace
Xvfb stopping
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Triggering a new build of sitespeed.io 02 yet-another-domain.com
Finished: SUCCESS
```
It needs to be noticed that the stats of the second URL are perfectly fine. The timing statistics are, of course, missing as browsertime did not run through, but asset statistics are screwed.
This behavior is domain independent. 

Server configuration:
* Linux Debian-78-wheezy-64-minimal 3.2.0-4-amd64 # 1 SMP Debian 3.2.68-1+deb7u1 x86_64 GNU/Linux
* Jenkins 1.617 with Xvfb plugin 1.0.16
* Node.js: v0.10.38
* sitespeed.io: 3.6.1

Suggestion:
When an error occured at a specific URL then only submit statistics that ran without any errors to the graphite server.

**Comment by soulgalore** [comment] 2015-06-15 13:58
Hi @yesman82 ,
I know about the main problem but not the screwed numbers, that must be another defect. First about the main problem: Today we use the nodejs selenium version oob, and it is kind of callback hell when something fails. We have a new version of Browsertime in the way that promisify selenium that will make it easier to catch failures and also implement retries (like if a URL fails, we can try it again for a couple of times). So when will it be released you ask? Well, I think it will happen during the summer. The things is since we (mainly @tobli ) has rewritten everything, we need it up and running on our test servers and keep it running for some time to make sure it handle every kind of case where it kind fail.

One thing that I noticed: Using the selenium JAR instead when you run the tests makes it a little more stable (check this example https://registry.hub.docker.com/u/sitespeedio/sitespeed.io/) if you run sitespeed standalone, you need to start the server yourself. I say a little more stable because it can still fail. 

Another thing: Chrome & Chromedriver is more stable on Mac OS X than Linux (probably it will not help you though).

I'll ping the thread when we have the new version out, probably it will be releases in a kind of beta.

And about the current issue with the assets issue, I will look into that this week. Is it possible for you to email me peter [AT] soulgalore [DOT] com with the result folder of the failed run, then it will be faster for me to track down.

All the best
Peter

**Comment by soulgalore** [comment] 2015-06-15 21:16
Hey @yesman82 ,
ah ok, I understand the root cause of the problem. What happens is that when it fails, we get size of the assets from YSLOW (uncompressed + not completely right), else when Browsertime works, the size is the compressed size (there's no way today using PhantomJS to get the correct size), so we change it later in the flow when we have run Browsertime.

In the long run we will move away from Phantoms (but it will not happen during the summer) so lets see how we can fix so we don't send the size when BT fails, I'll try to do a fix release during this week.

Best
Peter

**Comment by yesman82** [comment] 2015-06-16 07:24
thx @soulgalore :+1:

**Comment by AugustKoelpin** [comment] 2016-02-19 16:06
hey @soulgalore any update on not sending data when chromedriver hangs?

**Comment by soulgalore** [comment] 2016-02-21 20:44
Hey @AugustKoelpin , no sorry, it will work better in 4.0 (or rather it's fixed). In the latest 3.X we updated PhantomJS to 2.1, have you seen if it works better, or do you get the same?

Best
Peter

**Comment by AugustKoelpin** [comment] 2016-02-23 09:16
Hey @soulgalore, i'm still seeing the same in 3.9. Will await 4.0 with bated breath :+1:

**Comment by soulgalore** [comment] 2016-10-28 09:29
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Closed by soulgalore** 2016-10-28 09:29 UTC
