### ISSUE TITLE
Using Docker to test android does not work properly

### ISSUE THREAD

**Issue by Nuoky** [sitespeedio/sitespeed.io#1816] opened 2017-11-22 07:45 UTC
Hi.

os: ubuntu 16.04 TLS

run：
```
sudo docker run --privileged --shm-size=1g -v /dev/bus/usb:/dev/bus/usb -e START_ADB_SERVER=true --rm -v "$(pwd)":/sitespeed.io -v /etc/localtime:/etc/localtime:ro sitespeedio/sitespeed.io --browsertime.xvfb false --browsertime.chrome.android.package com.android.chrome https://www.sitespeed.io
```

output：
>Google Chrome 60.0.3112.78 
Mozilla Firefox 54.0
>* daemon not running. starting it now on port 5037 *
>* daemon started successfully *
>List of devices attached 
GWY0216C09005039	device
>
>[2017-11-22 15:12:02] INFO: Versions OS: linux 4.10.0-38-generic nodejs: v6.11.1 sitespeed.io: 5.6.5 browsertime: 1.9.4 coach: 0.36.0
[2017-11-22 15:12:02] INFO: Starting chrome for analysing https://www.sitespeed.io 3 time(s)

then stop at:
>[2017-11-22 15:12:02] INFO: Starting chrome for analysing https://www.sitespeed.io 3 time(s)

I tried Samsung S8, Nexus 6P and Huawei Mate 9 they all had the same problem. also I try to enter the docker container to use the adb shell command is working.

My English is not so good, Sorry about that. 

Thanks!

**Comment by soulgalore** [comment] 2017-11-22 08:05
Hi @Nuoky thanks for the report, I wonder if we have broken anything, let me try it later on today and get back.

Best
Peter

**Comment by soulgalore** [comment] 2017-11-22 09:15
Yep this is broken (+ wrong docs on www.sitespeed.io). I'll have a look at it tonight.

**Comment by soulgalore** [comment] 2017-11-23 08:02
I updated the adb-kit and I got this working in Browsertime in Docker but not sitespeed.io. We don't populate the Browsertime log with the same verbose settings as sitespeed.io so I don't get the log I need, I will look into that first (or something is wrong with the verbose logging).

**Comment by soulgalore** [comment] 2017-11-23 09:24
The problem is that we try to start xvfb even though we don't use it :

```
[2017-11-23 09:18:42] INFO: Versions OS: linux 4.4.0-59-generic nodejs: v8.9.1 sitespeed.io: 6.0.0-alpha.1 browsertime: 2.0.0-beta.1 coach: 1.0.0
[2017-11-23 09:18:43] INFO: Starting chrome for analysing https://www.sitespeed.io 1 time(s)
Invalid screen configuration undefinedx24
use: X [:<display>] [option]
-a #                   default pointer acceleration (factor)

```

**Comment by soulgalore** [comment] 2017-11-23 10:28
This is fixed in master now (by upgrading browsertime), we will release it in one day or so.

**Comment by soulgalore** [comment] 2017-11-24 07:55
This was released yesterday. Please re-open if you still have the problem!

**Closed by soulgalore** 2017-11-24 07:55 UTC
Labels: verified bug
