### ISSUE TITLE
Filmstrip Capability

### ISSUE THREAD

**Issue by rodders** [sitespeedio/sitespeed.io#1555] opened 2017-03-30 00:56 UTC
Feature idea / request for filmstrips!

One of the capabilities I really value in webpagetest.org is the filmstrip generation. It allows me to see the progress we're making visually, benchmark our progress over time, etc.

It would be great if we can add that capability to sitespeed, say similar to the video flag. BTW, video capability is excellent, and greatly appreciated. I think having the filmstrip capability is a slightly different, complimentary view.

Thank you for all the hard work you've put into sitespeed. It's simply amazing!

Cheers,
Rod.

**Comment by soulgalore** [comment] 2017-03-30 04:07
Hey @rodders 
thank for the kind words :)

I agree that is a good idea! We actually have the logic already for creating the images for a filmstrip since we use [Visual Metrics](https://github.com/WPO-Foundation/visualmetrics/) that can create the images from the video, so we could add a flag in Browsertime to produce them. We could probably do that the coming days. I created [an issue](https://github.com/sitespeedio/browsertime/issues/300) for fixing it in Browsertime.

The problem is more the frontend. If we add the capability for creating images, any chance you can help out with the look and feel? :)

Best
Peter

**Comment by soulgalore** [comment] 2017-03-30 04:17
Ah the good thing is that we already produce the images when we record the vide, we just need to add config for quality and size.

**Comment by rodders** [comment] 2017-03-30 05:22
Happy to help however you need - great news that the images are already being produced when video is recorded! Makes the path a bit easier I guess!

Thank you for tagging the request and responding so quickly. LMK how I can help.

**Comment by soulgalore** [comment] 2017-04-02 11:09
I think it would be cool to show them related to the HAR as in WPT and SpeedCurve. If PerfCascade can report the position, we could add JavaScript that changes the screenshots. On our side we need to read all the images (the names in one dir) and make them available to the front end in a nice structure (order them by time and when they should change). It seems doable when we can get PerfCascade to report the position :)

**Comment by soulgalore** [comment] 2017-06-27 18:51
Let do something like this: https://github.com/micmro/PerfCascade/issues/196#issuecomment-310901919 and then also add a filmstrip where we uses the same screenshots. 6.0 baby :)

**Comment by soulgalore** [comment] 2017-08-27 17:18
This has halted but lets take this up again the coming weeks, it's a really nice thing.

**Comment by soulgalore** [comment] 2019-02-01 05:05
This will be released today or tomorrow!

**Closed by soulgalore** 2019-02-01 05:05 UTC
Labels: feature request
