### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by akashnimare** [sitespeedio/sitespeed.io#680] opened 2015-06-08 08:07 UTC
I getting this error 
Couldn't send data to Graphite:Error: getaddrinfo ENOTFOUND for host:http://localhost:8080 port:2003
Can anyone help me out?

**Comment by soulgalore** [comment] 2015-06-08 08:48
Hi @akashnimare ,
so how have you setup your Graphite and what OS do you use? On Mac OS X you need to run *boot2docker ip* to get the IP number you should use.

Best
Peter

**Comment by akashnimare** [comment] 2015-06-08 09:04
I am using ubuntu 14.02
Installed docker images for graphite/grafana/sitespeedio
Run graphite using this 
sudo docker run -d \
  --name graphite \
  -p 8080:80 \
  -p 2003:2003 \
  --restart="always" \
  -v /data/graphite/storage/whisper:/opt/graphite/storage/whisper \
  -v .htpasswd:/etc/nginx/.htpasswd \
  sitespeedio/graphite

Run grafana
sudo docker run -d -p 3000:3000 \
-v /data/grafana:/var/lib/grafana \
--name grafana \
--restart="always" \
grafana/grafana

I can login to graphite using guest/guest (port 8080) and grafana(port 3000) using admin/admin
Then 
docker run --privileged --rm sitespeedio/sitespeed.io sitespeed.io -u http://akashnimare.in -b firefox -n 1 --connection cable -r /tmp/ --graphiteHost http://localhost:8080

I am not sure where I am going wrong?

**Comment by soulgalore** [comment] 2015-06-08 09:16
ok, so inside of the docker container running sitespeed, will not know about localhost, so use the IP or hostname of the server instead. The the port used for sendning metrics is 2003 but that is default so you don't need to include it. do something like this:
<code>--graphiteHost my.host.com</code> or if you add your ip of the server.

**Comment by akashnimare** [comment] 2015-06-08 09:22
You mean http://127.0.0.1:8080 ?

**Comment by soulgalore** [comment] 2015-06-08 09:30
well how do you mean :) use the real ip of the server and skip the port. and do not use localhost, the container will think localhost is inside the container but we need to send the data outside. 

best
Peter

**Comment by akashnimare** [comment] 2015-06-08 09:40
I am running this on my local machine and not on any remote server. Its fetching data from  http://akashnimare.in. So in this case what IP address should I use. I tried localhost and  http://127.0.0.1.No luck.

**Comment by EikeDawid** [comment] 2015-06-08 10:21
It's the ip address of your host. You can find it out using ```/sbin/ifconfig``` - i my case it :

```
eth1      Link encap:Ethernet  HWaddr <redacted>  
             inet addr:192.168.33.10  Bcast:192.168.33.255  Mask:255.255.255.0
```

Here a small diagram to illustrate the localhost issue:
![localhost](https://cloud.githubusercontent.com/assets/638502/8032730/4e686da8-0dd0-11e5-9bb2-a8dd3ed0721d.jpg)

So if you configure the sitespeed.io docker container to use localhost then that is not your host machine (where you started the container from) but inside the container itself.

**Comment by akashnimare** [comment] 2015-06-08 10:40
Yes I have found out my host using ifconfig but still I am getting this error
Couldn't send data to Graphite:Error: connect ETIMEDOUT for host:172.17.42.1 port:2003

**Comment by EikeDawid** [comment] 2015-06-08 11:14
That looks like the IP docker overlay (docker0) and not your host's IP (eth1 .. or eth0).

e.g. this is **wrong**:

```
root@vagrant-ubuntu-trusty-64:/data/sitespeedio# /sbin/ifconfig 
docker0   Link encap:Ethernet  HWaddr 56:84:7a:fe:97:99  
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::5484:7aff:fefe:9799/64 Scope:Link
```

**Comment by akashnimare** [comment] 2015-06-08 11:16
So what should I do?

**Comment by EikeDawid** [comment] 2015-06-08 11:21
look for ```inet addr:``` in the section starting with ```eth1``` in your ```/sbin/ifconfig``` output ( see [above](https://github.com/sitespeedio/sitespeed.io/issues/680#issuecomment-109942840) for example) and then use that one

**Comment by akashnimare** [comment] 2015-06-08 11:51
Thanks I have got the host by this command
docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${CID}
Now I am able to see the graphs in graphite.
Can you tell me how can I see this graphs in grafana?

**Comment by EikeDawid** [comment] 2015-06-08 12:05
see in the grafana section in the documentation - you need to configure/add a datasource:
http://www.sitespeed.io/documentation/performance-dashboard/#grafana

Theres is a screenshot - make sure that you use the same IP/hostname for this configuration that you used in the configuration above.

**Comment by akashnimare** [comment] 2015-06-08 13:00
I see nothing in grafana. I did this
Grafana admin > Data Sources > Add new
Data source name - demo 
default
Type:graphite
Url : http://172.17.0.56/
Basic auth enable
What should I do next?
I run this command
docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://akashnimare.in -b firefox -n 1 --connection cable -r /tmp/ --graphiteHost http://172.17.0.56  --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1

**Comment by EikeDawid** [comment] 2015-06-08 13:07
You need to **build** your dashboard using grafana via the Grafana UI - see here for docs: http://docs.grafana.org/ 

However if you only run the command once then you will only have a data for a single point in time stored - which is why the docs suggest to run it in crontab in 30 mins intervals.

**Comment by soulgalore** [comment] 2015-06-08 13:11
yep. you can also import the dashboard.json (http://www.sitespeed.io/documentation/performance-dashboard/#setup-your-dashboards) to get quick setup and then change the keys to follow your structure. It's not optimal but at least a start.

**Comment by akashnimare** [comment] 2015-06-08 14:13
Sorry but I am not getting this.
1. http://docs.grafana.org/datasources/graphite/ There is no Metric editor in grafana
2. I have imported the dashboard.json but it shows nothing. Where should I change the key?
Here is the screenshot of grafana
![1433772719561screensave](https://cloud.githubusercontent.com/assets/2263909/8036611/921723c8-0e16-11e5-864c-c8073d017918.png)

**Comment by EikeDawid** [comment] 2015-06-08 14:36
I probably should have linked here:
http://docs.grafana.org/guides/gettingstarted/#beginner-guides

I would suggest to start with a "new dashboard" and work you way through a simple graph to get a general feel for it. 

(the editor appears if you click on the graph title - e.g. "Median timings", a small overlay will appear, click edit )

Alternatively you can search and replace the metric names in the json before importing it using cmd/sed/awk/vim/text editor/ide .

**Comment by akashnimare** [comment] 2015-06-08 15:04
Oh thanks a ton man. I was able to find the metric editor and setup the graphs. Though I was not able to run secure website. I was trying this website https://hackerrank.com and got tons of error. I am not able to get yslow output.

**Comment by soulgalore** [comment] 2015-06-08 19:32
hey @akashnimare ,
yep got the same when I tested with phantom 1.9.8, haven't tested with newerversion though. will test later with plain YSlow to see where the problem is.

Best
Peter

**Comment by akashnimare** [comment] 2015-06-08 19:39
Ok. Please don't close this issue as I am having some issues with crontab. I'll let you know the problem tomorrow. 
Thanks for all the help :)

**Comment by akashnimare** [comment] 2015-06-09 10:03
I have save this in crontab
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
0,5,10,15 * * * * docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://akashnimare.in -b firefox -n 5 --connection cable -r /tmp/ --graphiteHost 172.17.0.6 --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1

but I am not getting the data. Do I need to run crontab or it will automatically do the job?

**Comment by lyneld** [comment] 2015-06-09 10:13
What do you see in `/tmp/sitespeed-run.txt`? Based on your cron, it should run on the 0th, 5th, 10th & 15th minute of the hour, every hour. Cron will automatically run the command, you don't really need anything else.

**Comment by akashnimare** [comment] 2015-06-09 10:38
Couldn't send data to Graphite:Error: getaddrinfo ENOTFOUND for host:http://localhost:9090

**Comment by akashnimare** [comment] 2015-06-09 10:52
@lyneld @soulgalore We need the localhost address in crontab. When I add http://127.0.0.1:8080 cron works perfectly. Here we don't need to put the graphitehost.

**Comment by soulgalore** [comment] 2015-06-10 07:11
so @akashnimare , does it work for you now? didn't fully follow the last things?

**Comment by akashnimare** [comment] 2015-06-10 12:09
Yeah somehow it worked. I got the IP host using 
> docker exec -it graphite bash
> cat /etc/hosts
But YSlow is not working with https. Can you tell me a quick fix for this problem.
I have checked your dashboard (http://dashboard.sitespeed.io/dashboard/db/compare-multiple-sites?edit&from=now-7d&to=now) where it's working.

**Comment by soulgalore** [comment] 2015-06-10 13:00
cool. the problem is not https, it something that don't make it work with the site you are testing. I'll test it in the latest phantomjs and then also in plain Yslow(phantomJS version) to see where the problem is.

**Comment by akashnimare** [comment] 2015-06-10 13:34
That will be awesome. Let me know if you find the solution.

**Comment by soulgalore** [comment] 2015-06-10 14:05
did a fast test and got the same using plain Yslow, got <code>FAIL to load undefined</code>, I'll need to debug to see what's happening. will get back tonight.

**Comment by akashnimare** [comment] 2015-06-11 09:45
Did you find out the solution?

**Comment by soulgalore** [comment] 2015-06-11 17:14
No, I haven't looked into it more, need to see why YSlow fail. The problem is that the YSlow project is kind of dead so I guess I'll have to look into it :) Will do today or tomorrow, think at least I can find the reason, then fixing it, not sure.

**Comment by akashnimare** [comment] 2015-06-12 09:18
I have tried everything. This is the problem from YSlow side. It would be very helpful If you can find the reason behind it.

**Comment by akashnimare** [comment] 2015-06-14 01:33
Can you add this URL to your sitespeed dashboard and see if it's working
there or not?

**Comment by soulgalore** [comment] 2015-06-14 08:38
Hi @akashnimare ,
I think that will not matter. either it is the YSlow impl of PhantomJS or Phantom itself. You said you got an error when you load the URL using Phantom standalone?

Best
Peter

**Comment by akashnimare** [comment] 2015-06-14 09:42
It is Phantom who is giving the problem. I load this url using Phantom and got an error saying Failed to load the address.
But when you check this url on http://gtmetrix.com/ and https://webpagetest.org I get the Yslow output. That's why I was saying If you check this url on your sitespeed dashboard it might work.

**Comment by akashnimare** [comment] 2015-06-16 08:48
@soulgalore hi
I was able to get YSlow plain output using url https://www.hackerrank.com?nocheckcdn=1
But when I checked it with sitespeed it was saying no urls to analyze.

**Comment by soulgalore** [comment] 2016-10-28 09:28
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Closed by soulgalore** 2016-10-28 09:28 UTC
Labels: non working URL
