### ISSUE TITLE
Video converting issue

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#2493] opened 2019-06-04 12:06 UTC
docker image sitespeed.io:9.0.0-plus1

I see following error from time to time while running Gitlab job
First of all I've checked hardware and Gitlab monitoring shows that's everything is ok (but I don't really trust it actually).
What may be the reason of this error?

ERROR: Converting the video failed. Converting from /tmp/browsertime-EMPUJu/x11.mp4 to /sitespeed.io/sitespeed-results/desktop/cable/pages/172.17.0.2/URL1/data/video/1.mp4
[2019-06-04 11:49:13] ERROR: Error: Command failed: ffmpeg -nostdin -i /tmp/browsertime-EMPUJu/x11.mp4 -c:v libx264 -crf 23 -preset medium -vf format=yuv420p /sitespeed.io/sitespeed-results/desktop/cable/pages/172.17.0.2/URL1/data/video/1.mp4

**Comment by soulgalore** [comment] 2019-06-04 13:07
Hi @Icecold777 not sure. Can you run with `--videoParams.keepOriginalVideo ` and copy the original video and share it? That way I can probably reproduce on my local machine to understand what's going on. Do you get it all the time?

Best
Peter

**Comment by Icecold777** [comment] 2019-06-05 11:18
Hi @soulgalore, I'll try to get the video but it's not an easy task because Gitlab do not post job artifacts when it fails. Need some time to find a workaround. As I wrote before it reproduces from time to time. I don't see any correlation.

**Comment by soulgalore** [comment] 2019-06-05 13:06
I wonder if it can have something 2do with what kind of instance running the tests (CPU etc). I don't know how Gitlab is handling the job is do.

**Comment by soulgalore** [comment] 2019-11-18 00:09
Did this got fixed on your side?

**Comment by soulgalore** [comment] 2020-07-06 08:02
Closing since no more feedback.

**Closed by soulgalore** 2020-07-06 08:02 UTC
Labels: need more info
