### ISSUE TITLE
TypeError: Cannot set property '_meta' of undefined

### ISSUE THREAD

**Issue by mzl-ki** [sitespeedio/sitespeed.io#2506] opened 2019-06-14 13:40 UTC
Hi,

I get the error **TypeError: Cannot set property '_meta' of undefined** running the following example:

```sh
sitespeed.io ./sitespeed/testMetaMissing.js --preScript ./sitespeed/navigateToGoogle.js  --multi -n 1
[2019-06-14 15:30:58] INFO: Versions OS: darwin 18.2.0 nodejs: v11.4.0 sitespeed.io: 9.2.1 browsertime: 5.1.3 coach: 3.5.7
[2019-06-14 15:30:59] INFO: Running tests using Chrome - 1 iteration(s)
[2019-06-14 15:31:01] INFO: Navigating to url http://www.google.com iteration 1
[2019-06-14 15:31:07] INFO: Start to measure Time to google something
[2019-06-14 15:31:09] ERROR: TypeError: Cannot set property '_meta' of undefined
    at Object.addMetaToHAR (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/har/index.js:138:34)
    at addExtraFieldsToHar (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:76:19)
    at Engine.runByScript (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:189:7)
[2019-06-14 15:31:10] INFO: HTML stored in ...
```

navigateToGoogle.js
```javascript
module.exports = async function(context, commands) {
  await commands.navigate("http://www.google.com");
};
```

testMetaMissing.js
```javascript
module.exports = async function(context, commands) {
  await commands.measure.start("Time to google something");
  await commands.wait.byTime(1000);
  await commands.measure.stop();
};
```

As soon as I add the navigate line to _testMetaMissing.js_ everything is fine.

**Comment by soulgalore** [comment] 2019-06-14 16:49
Hi @ppi-mzl thanks for creating the issue, I think the docs is unclear:

`--preScript` is a way to run something before you test a URL. For example, say that you want to test 10 pages of your site as a logged in user. Then create a preScript that logs in the user and feed sitespeed.io with ten URLs. Then for each URL the browser will open, your user will be logged in and then you will measure each URLS (and close it between URLs).

Scripting (`--multi `) is measuring multiple pages within the same browser session (so browser cache etc will be used.

In your example, you mean that you also have a some code where you actually do a search and that is what you want to measure? That should work if you enter something in the search field, click the search button (clickAndWait).

Checkout the docs for scripting at https://www.sitespeed.io/documentation/sitespeed.io/scripting/

Hope that helps
Peter

**Comment by ppi-mzl** [comment] 2019-06-17 07:18
Hey,

thanks for the kind explanation. The code above is just an example for how to reproduce the error and has no actual meaning.

I want to test some components excluding the page load time so I thought navigating to the url in the preScript and using measure.start() in the actual script was the way to go.

In any case the error code should be more descriptive.

Regards
Martin

**Comment by soulgalore** [comment] 2019-06-18 06:34
If you can provide a real example following our guide: https://www.sitespeed.io/documentation/sitespeed.io/bug-report/ we can see if we can fix the original problem. I've seen this pattern before, simplifying use cases sometimes misses the real error, so with real with real examples we can probably fix it or at least add it to the list of things that should be fixed :)

Best
Peter

**Comment by ppi-mzl** [comment] 2019-06-19 15:26
The real error is that in my test there is no navigation in between the measure.start() and measure.stop() call. I wanted to measure performance of a react component performing state changes which didn't involve any page loads.
As I understand it now, sitespeed requires a navigation to apply its metrics. Since I found no way to measure actions without measuring a page load as well, I guess sitespeed is the wrong tool for my use case.

Nevertheless thank you for your help!

**Comment by skhilko** [comment] 2019-06-25 17:42
The error trace looks the same as in https://github.com/sitespeedio/browsertime/issues/847

**Comment by soulgalore** [comment] 2019-06-28 12:31
At the moment you need to either navigate or make one request between start/stop for it to work.

Best
Peter

**Comment by gremjua** [comment] 2019-08-16 19:37
Hi @soulgalore I have a problem similar to @ppi-mzl. 
I want to measure the time it takes for a react component to change state.
There are no new page loads, but I know there are requests that are made when I click the component.
Still, I get the Cannot set property '_meta' of undefined problem.
Is sitespeed supposedly able to measure times if there is a request between start and stop? (The URL of the page remains the same)

**Comment by soulgalore** [comment] 2019-08-16 19:42
Hi @gremjua can you measure it with a [User Timing](https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API)? That is automatically picked up by sitespeed.io:

* start measure
* navigate to that page
* do what you need to change the state 
* stop measuring

Best
Peter

**Comment by soulgalore** [comment] 2020-07-06 08:02
Closing since no more feedback.

**Closed by soulgalore** 2020-07-06 08:02 UTC
Labels: need more info
