### ISSUE TITLE
Duplicate slack message when testing single url

### ISSUE THREAD

**Issue by harshavarma** [sitespeedio/sitespeed.io#2595] opened 2019-08-25 02:48 UTC
Hi Team,

I added a webhook for a slack channel and passed the required parameters when running sitespeed. I'm running it using the official docker image on Ubuntu. 

`--slack.hookUrl https://hooks.slack.com/services/************ --slack.type all \
--slack.limitMetric firstVisualChange --slack.limitWarning 1300 -n 1`

I'm only running it on a single url with a single iteration. The slack messages are working but every run is generating 2 messages (or 1 message with duplicate content) as per the attached screenshot. Actually, almost 4 messages since the summary is laid out with out any styling, then the styled summary and again a copy of the whole thing. I tried `--slack.type summary` and it generates duplicate messages without styling. `--slack.type url` didn't send a message at all.

Also, I set the `limitWarning` parameter to `1300` and I'm not getting any warnings even though the `firstVisualChange` metric is `~1600`. Am I missing something?

![chrome_2019-08-25_12-37-15](https://user-images.githubusercontent.com/788876/63644898-6d742380-c736-11e9-90dd-9cd7b9c83d09.png)

**Comment by harshavarma** [comment] 2019-08-27 02:53
Just to add to this, error notifications are showing a green border instead of red. The example in the documentation clearly shows proper styling, so I'm think I haven't configured Slack properly. Any ideas?

![chrome_2019-08-27_12-50-31](https://user-images.githubusercontent.com/788876/63737398-a85a9080-c8c9-11e9-940d-c9c565d5abe3.png)

**Comment by soulgalore** [comment] 2019-08-27 05:49
Hi @harshavarma yes the double posting seems like a bug, let me look into it. We have the alerts running in our continuous test but I cannot see the same there, but we test multiple URLs there, I wonder if there's a bug when you use just one URL.

About the unstyled content, I didn't fully get that part? 

The green colouring when there's an error also looks like a bug. 

For the limit, I need look into it. 

Best
Peter

**Comment by harshavarma** [comment] 2019-08-27 06:32
Hi @soulgalore , please ignore the part about styling.

**Comment by soulgalore** [comment] 2019-09-03 06:27
Hi @harshavarma I think fixed the most of those problems for the coming the release, but I haven't been able to get those duplicate messages?

Best
Peter

**Comment by harshavarma** [comment] 2019-09-03 07:15
Thanks @soulgalore . I'll try to find the root cause for the duplicate messages but it is not a big deal.

**Comment by soulgalore** [comment] 2019-10-09 21:10
I haven't been able to reproduce the duplicate messages. Closing for now but if someone can reproduce/get the same issue, please let me know and I can re-open.

**Closed by soulgalore** 2019-10-09 21:10 UTC
Labels: bug, good first issue
