### ISSUE TITLE
Image size shows up as 0

### ISSUE THREAD

**Issue by pranavparikh** [sitespeedio/sitespeed.io#773] opened 2015-11-04 21:21 UTC
I'm trying to test this url with sitespeed.io
https://www.yahoo.com/beauty/self-cover-shoots-jessica-alba-walks-us-through-152557950.html

Running this command, 

sudo docker run --name ssiodocker --rm -v /usr/lib/node_modules/phantomas_srv:/sitespeed.io sitespeedio/sitespeed.io:3.11.1 sitespeed.io -u http://yahoo.com/beauty/self-cover-shoots-jessica-alba-walks-us-through-152557950.html -r public/sitespeedio/ --outputFolderName 151104_test1 --suppressDomainFolder -d 1 -b firefox --memory 512 -n 1 --screenshot --seleniumServer http://127.0.0.1:4444/wd/hub --connection native --profile desktop

I get the image size as 0 in the results however, in the screenshots, I can see some images

I tried running the same test on run.sitespeed.io, I see that sitespeed analyzed 3 different urls including our test url.
https://results.sitespeed.io/cd6e-2015/10/4/017fa400-8f2f-45df-8c39-4246005b3e2b/index2.html

Questions
1) Why is the behavior different on run.sitespeed.io ? 
2) Do you think our issue is related to https://github.com/sitespeedio/sitespeed.io/issues/107 ?
3) Am I using sitespeed.io in a wrong way ?
3) Will using waitScript solve our issue ? (tried --waitScript "return performance.now() > 20000;" but that didn't work) 

Appreciate your help.

Thanks

**Comment by soulgalore** [comment] 2015-11-04 21:47
Hi @pranavparikh ,
>1) Why is the behavior different on run.sitespeed.io ? 

The online version default crawl the first URL and test 2 more two show more of the functionality

> 2) Do you think our issue is related to #107 ?
> 3) Am I using sitespeed.io in a wrong way ?
> 3) Will using waitScript solve our issue ? (tried --waitScript "return performance.now() > 20000;" but that didn't work)

The problem is on our side, the current version is using YSlow the phantomjs version to pickup the images, could be that something is not working there (will be fixed in the coming 4.0 though). However, your trick by setting the waitscript looks promising but for that to work you need PhantomJS 2. That is actually in the Docker container (but not so good documented sorry). If you add:
<pre>--phantomjsPath /usr/local/phantomjs/bin/phantomjs</pre> to the parameters when you run Docker the PhantomJS will be picked up (I think it's implementing performance.now right? else you could do some other trick with the nav timings that is supported from 2.0).

Hopefully then the images will be picked up. You could also check the HAR file, that one should (if you use the waitscript) pick up the images. Please get back to let me know if it works or not.

Best
Peter

**Comment by pranavparikh** [comment] 2015-11-04 21:50
Thanks @soulgalore ,

Yes. I tried with PhantomJS 2 like you mentioned but that didn't work.

**Comment by soulgalore** [comment] 2015-11-04 21:53
Aha, ok, hmm then I think its nothing I can do until we release 4.0 (it will then be HAR based, so we get all the data from the HAR-file instead of using phantom). And if everything works fine, the first beta will be here this year.

What you can do is use WebPageTest directly or if you want the dashboard etc, let sitespeed.io drive WebPageTest.

**Comment by tufandevrim** [comment] 2015-12-29 06:43
Hi @soulgalore 

I am wondering when 4.0 will be available. Can't wait to use HAR based metrics instead of phantom. I am also wondering how you guys are planning to get yslow metrics like 'rule scores' and 'critical rendering path scores' data if you're not going to use yslow. Or, will you still be using yslow rules via browsertime/har/browsermob?

Please let me know about the 4.0 progress. If you need help, please let me also know where I can fit in.

Thanks,
Devrim

**Comment by soulgalore** [comment] 2015-12-30 08:22
Hi @tufandevrim ,
realistic I think the alpha release will be a couple of months into 2016, but we will publish part of the new version step by step. In a couple of days (hopefully) we can publish the new rule engine and then we need help to get test and add more rules, so if you can help with that, it would be great! 

The new rules will be done in two steps: We will run Javascript in Firefox/Chrome that collects info from the DOM and then in the next step, we will analyze the HAR file. So we can get the same thing as YSlow but from a modern browser. What we are missing (or rather one of the things we are working on) is getting the HAR files direct from the browser instead of the proxy we use, to get better and more fine grained HAR files.

Best
Peter

**Comment by tufandevrim** [comment] 2015-12-30 21:01
Hi @soulgalore ,

Thanks for the details. Btw I am pretty sure you're aware that yslow can analyze the har file as well:
http://yslow.org/command-line-har/

Again can't wait to see the new rule engine.

Thanks,
Devrim

**Comment by soulgalore** [comment] 2015-12-30 22:24
Hi @tufandevrim ,
yes I know, YSlow was super fantastic when it was created, now I think we can do better :)

Best
Peter

**Comment by soulgalore** [comment] 2016-10-28 09:32
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Closed by soulgalore** 2016-10-28 09:32 UTC
