### ISSUE TITLE
cannot install sitespeed with npm

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1443] opened 2017-02-07 15:06 UTC
I have been meaning to report this for some time: installing sitespeed.io via npm I consistently get issues with "saprano-saxaphone package"

`Failed at the soprano-saxophone@0.13.0 install script 'node install.js'`

Thanks,

**Comment by soulgalore** [comment] 2017-02-08 09:49
Thanks @ppcuenca for reporting. I think the problem is that is running "node" bit on your system it's called nodejs right? I've had this on a list before but missed fixing it. I've added an [issue](https://github.com/tobli/soprano-saxophone/issues/4) in that project see when we can fix that, thanks again for reporting.

Best
Peter

**Comment by ppcuenca** [comment] 2017-02-09 14:07
Hi @soulgalore,

 Any workaround/temp fix I could do in the meanwhile?

**Comment by soulgalore** [comment] 2017-02-09 14:17
Hey @ppcuenca 
I think it is like this: https://github.com/Medium/phantomjs#im-on-debian-or-ubuntu-and-the-installer-failed-because-it-couldnt-find-node

This shouldn't be only failing for that install? Follow the instructions there how to handle the lagacy node and it should work.

Best
Peter

**Comment by soulgalore** [comment] 2017-03-03 08:19
Closing this following phantomjs example.

**Closed by soulgalore** 2017-03-03 08:19 UTC
Labels: bug
