### ISSUE TITLE
ERROR: Could not get the HAR from Firefox

### ISSUE THREAD

**Issue by Staicul** [sitespeedio/sitespeed.io#2424] opened 2019-04-15 14:18 UTC
This script:
```
module.exports = async function (context, commands) {
  const webdriver = context.selenium.webdriver;
  const driver = context.selenium.driver;
  await commands.navigate(
    'https://www.kolikkopelit.com/pelit/saunapeli-1-1079194/play-for-fun'
  );

  try {
    await commands.measure.start('playgame')
    const gameFrame = driver.findElement(webdriver.By.xpath('//iframe[@data-test-name="game-frame-iframe"]'))
    driver.switchTo().frame(gameFrame)
    context.log.info("switched to game frame")
    await commands.wait.byXpath(`//div[@class="continueText"]`, 30000)
    context.log.info("found continue button")
    await commands.click.byXpath(`//div[@class="continueText"]`)
    context.log.info("clicked the continue button")
    await commands.wait.byXpath(`//div[@class="spin-button-icon "]`, 20000)
    await commands.click.byXpath(`//div[@class="spin-button-icon "]`)
    context.log.info("spin 1")
    await commands.wait.byXpath(`//div[@class="spin-button-icon "]`, 20000)
    await commands.measure.stop()

  } catch (e) {
    context.log.info(e.message)
  }
};
```
when run with the command:
```
docker run --shm-size=1g --rm -v /path:/sitespeed.io sitespeedio/sitespeed.io:8.12.0 -b firefox scripts/play_saunapeli.js --multi -n=1 --browsertime.viewPort 2560x1440 --spa
```
gives the following log:
```
Google Chrome 74.0.3729.75 beta
Mozilla Firefox 66.0
[2019-04-15 13:55:21] INFO: Versions OS: linux 4.9.125-linuxkit nodejs: v10.13.0 sitespeed.io: 8.12.0 browsertime: 4.6.2 coach: 3.3.0
[2019-04-15 13:55:22] INFO: Running tests using Firefox - 1 iteration(s)
[2019-04-15 13:55:26] INFO: Navigating to url https://www.kolikkopelit.com iteration 1
[2019-04-15 13:55:47] INFO: Start to measure playgame
clicked on Saunapeli
switched to game frame
found continue button
clicked the continue button
clicked the spin button
[2019-04-15 14:02:57] INFO: Waiting on har-export-trigger to collect the HAR
[2019-04-15 14:02:57] ERROR: Could not get the HAR from Firefox JavascriptError: ReferenceError: HAR is not defined
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.executeScript()
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.executeAsyncScript (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:891:17)
    at SeleniumRunner.runAsyncScript (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:302:26)
    at FirefoxDelegate.onCollect (/usr/src/app/node_modules/browsertime/lib/firefox/webdriver/firefoxDelegate.js:74:38)
    at Measure.collect (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:249:31)
```

I am running on MacOS Mojave 10.14.4.

**Comment by soulgalore** [comment] 2019-04-15 17:06
Hi @Staicul if the HAR is undefined, it looks like the https://github.com/firefox-devtools/har-export-trigger didn't work. It's plugin we run in Firefox to be able to get the HAR file. Any change you can install it in Firefox and try that page, it looks like it could be a upstream thing, and if you can reproduce just with the plugin, it will be easier to create a upstream issue.

Thanks
Peter

**Comment by Staicul** [comment] 2019-05-06 10:08
Hi @soulgalore , this is still giving me trouble. It seems to work with the plugin:

![Screenshot 2019-05-06 at 12 03 37](https://user-images.githubusercontent.com/23332674/57219066-406cfb00-6ff7-11e9-8a01-92abc3793cbe.png)

Do you have any other suggestions? Thanks!

**Comment by soulgalore** [comment] 2019-05-06 10:37
Hi @Staicul jus wanted to verify that you use the latest container pushed yesterday, since Firefox broke all extensions if you don't upgrade to 66.0.4?

**Comment by Staicul** [comment] 2019-05-06 12:07
I've just tried with sitespeed.io:8.15.2 and I get the same error.
I also updated the script in the first comment to accommodate some locator changes that took place, so it will work for you.

**Comment by Staicul** [comment] 2019-05-16 11:57
Hi @soulgalore , I'm still getting this error and it really slows down the execution and also seems to alter the metrics. Could you take a look or give me some suggestions? Might there be a workaround?

**Comment by soulgalore** [comment] 2019-05-16 18:05
Hi @Staicul sorry for not getting back, I haven't tried it before. What are you trying to measure? Measure will measure a navigation to a new URL (see https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measure). If you wanna measure something inside a page, I think you could use a timer in the scrip (start/stop) or a user timing. To report that back ... I think you need to take care if the data yourself at the moment. It would be cool be able to add things to the results from within a script but I don't think that is possible at the moment.

Best
Peter

**Comment by Staicul** [comment] 2019-05-17 09:39
It's my bad then. I understand it better now, thanks. But I'm still a bit confused since I'm getting the metrics for a spa with no change in the url. I'm trying to measure the homepage (the page after login). It goes like this:
```
navigate to url
fill username and password
measure.start()
click the login button AndWait
measure.stop()
```
Could the metrics I'm getting be reliable since there is no new url?

**Comment by soulgalore** [comment] 2019-05-30 15:30
Hey @Staicul sorry for not getting back. I explained it bad. It works like this: If you run sitespeed.io by default it will wait for the pageCompleteCheck to complete (wait for the onLoadEvent to happen). If you add --spa it will wait for silence in the resource timing API meaning as long as you do one request in your spa and that one is updating the layout of the page, the video metrics like visual paints will work. Was that understandable? Let me know, else I'll try to explain it better.

**Comment by soulgalore** [comment] 2019-11-19 01:34
I'm closing this now, if it is still unclear please let me know.

**Closed by soulgalore** 2019-11-19 01:34 UTC
