### ISSUE TITLE
switch to iframe by xpath

### ISSUE THREAD

**Issue by zzhao2010** [sitespeedio/sitespeed.io#3644] opened 2022-05-02 17:47 UTC
### Your question

I was trying to use the switch function to switch to different iframes in the page. However it didn't work as expected. 
I had to use xpath because there is no id attribute defined for the iframe that I wanna switch to. As the example shows below, I had to switch to a child iframe inside a frame. It didn't throw out exception but it didn't work because the iframe and targetIframe variables returned the identical value.
```
const iframe = await seleniumDriver.findElement(By.xpath('//iframe[@title="accessibility title"]'));
context.log.info('The iframe is: ', iframe)
await commands.switch.toFrame(iframe)
context.log.info('Switch to the target iframe')
const targetIframe = await seleniumDriver.findElement(By.xpath('//iframe[@id="vod_iframe"]'));
context.log.info('The iframe is: ', iframe)
```

And then I tried to use selenium switchTo().frame function directly like below, which worked when I was just testing it as a selenium script. But it threw an exception after I ran it on sitespeed.io..
`await seleniumDriver.switchTo().frame(seleniumDriver.findElement(By.xpath('//iframe[@title="accessibility title"]')));`

ERROR: No page that could be associated with the error:iframe is not defined
[2022-05-02 17:17:15] ERROR: ReferenceError: iframe is not defined
    at module.exports (/sitespeed.io/lex-record_account_professional.js:12:45)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:7:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:221:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:266:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:145:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:150:26)

**Comment by soulgalore** [comment] 2022-05-03 13:17
Hi @zzhao2010 thanks for creating the issue!

For the thing were you can't switch using `commands.switch.toFrame` what's the easiest way I can reproduce that?

> ERROR: No page that could be associated with the error:iframe is not defined

Can you share your full script, its hard to guess what is happening? Can you share more what you are trying to accomplish?

**Comment by zzhao2010** [comment] 2022-05-05 20:30
@soulgalore Any updates for this issue?

**Comment by soulgalore** [comment] 2022-05-11 07:14
@soulgalore sorry I didn't look since there wasn't an easy way to reproduce.

Looking at the Selenium docs, it looks like the id is "A number that specifies a (zero-based) index into window frames and not the id of an element"?  https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_TargetLocator.html - do that work if you try?

For the code in your example, that looks right according to the docs right?
```
 const targetIframe = await seleniumDriver.findElement(By.xpath('//iframe[@id="vod_iframe"]'));
 context.log.info('The iframe is: ', iframe)
 await commands.switch.toFrame(targetIframe);
```

In your example you use Python flavour of Selenium, I wonder if there's a bug in Selenium, if you can do a simple test case that would be super helpful, thanks!

**Comment by soulgalore** [comment] 2023-12-27 16:36
Didn't get any response so closing.

**Closed by soulgalore** 2023-12-27 16:36 UTC
