### ISSUE TITLE
Read run-config from file

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#270] opened 2013-09-30 05:15 UTC
It would be cool to read all the run configutrations from file, instead of feed from command line. Then you could test mobile/desktop against each other in the same sites test. It will also be good to not bloat the command line.

**Comment by tay1orjones** [comment] 2015-05-29 15:02
+1 for this idea. I'd like to see json as well.

**Comment by soulgalore** [comment] 2015-05-29 18:58
hey @paazmaya and @tay1orjones , it actually exists using <pre>--configFile <PATH></pre> but I haven't tried it since I did the nodejs release,  I'll try it this weekend and see if it needs some tweaks.

When you do a run, the configuration is stored as config.json, and that can be used. But let me test it, think it could need some tweaks.

**Comment by paazmaya** [comment] 2015-06-01 08:17
Great :apple:

**Comment by lukewertz** [comment] 2015-07-23 10:07
@soulgalore were you able to test the configFile parameter? In trying to use the config.json file that is returned from a successful run, I'm just getting sitespeed's help output:

```
$ sitespeed.io --configFile /Users/luke/Desktop/config.json
You must specify either a URL to test or a file with URL:s

Usage: node sitespeed.io [options]
...
```

**Comment by soulgalore** [comment] 2015-07-23 13:00
sorry I missed trying it, let me try tonight.

In the long run I think this needs to be re-worked, I got some ideas.

Best
Peter

**Comment by lukewertz** [comment] 2015-07-23 13:05
Awesome, thank you. I'll look forward to seeing if the error is just on my end or if it is reproducible.

**Comment by soulgalore** [comment] 2015-07-24 06:41
sorry this seems to have been broken over time. I'll add a test case and fix it asap (on vacation now though). Thinking it's better to have a .sitespeed.io file in your home dir where you can set specific default parameters? I'm not 100% like the config.json, think it's hard to understand how/why etc :)

Best
Peter

**Comment by lukewertz** [comment] 2015-07-24 13:48
Personally, I like the workflow of having the config.json file generated with the run. I'm generating a baseline set of metrics and then using the same test throughout development of a new feature set to see how performance is impacted. The settings stay with the project, not with me as a person (or, more accurately, my user on the computer).

My only feedback, though it's very high-level because I haven't spent much time playing with it, would be this: regardless of how the URLs are passed to the test, I would like them to be hardcoded in the outputted .json file. Since the text file that holds the URLs might not get committed or saved with the .json file, the URLs that are tested should be considered a hard artifact of the test itself. But it's not really that big of a deal.

Lastly: Thank you. Seriously. Sitespeed is awesome and I really appreciate all your work on it. Enjoy your vacation!

**Comment by soulgalore** [comment] 2015-07-24 19:59
Thanks @lukewertz 
I see your point. I'll be able fix it early next week, and I like your point about the URL:s, need to think though how it can be done in a good way.

Best
Peter

**Comment by jzoldak** [comment] 2015-08-05 16:12
+1 on re-enabling reading from a config file. I'd also be happy to test out any code for you.

**Comment by soulgalore** [comment] 2015-08-05 19:01
yep sorry about this, it's broken right now and I haven't had the time to fix it, lets see this weekend.

**Closed** 2015-08-10 09:59 UTC
Labels: bug
