### ISSUE TITLE
🤥Can sitespeed.io do page turn performance test?

### ISSUE THREAD

**Issue by Poytr1** [sitespeedio/sitespeed.io#1748] opened 2017-10-20 16:40 UTC
Hi,
In order to test the performance of our website, our team searched a lot of tools and finally found that `sitespeed.io` is the most suitable tools for us, because it is powerful by integrating enough tools, we really think it is an excellent tool😘.
But `sitespeed.io` cannot perfectly solve all of our problems😔. It seems not be good to deal with the page turn situation. For example, we have such a scenario: upload pictures, then search in the picture library to find similar ones and return the results. So we first visit the upload page and after we upload pictures, page will turn to search results(at this time the corresponding url has become the url of the results page), but at the very beginning the url is unknown for us. Our case is similar to issue #1664 , but not all the same. We consider that it's an Indivisible process from the upload picture, and page turns to the results page, rather than a direct access to the URL of the results page🤔.
We think this is a very common requirement, the analysis of process: firstly visit the beginning page then do some operations and jump to the final page ... so can it be possible to add this as a new feature to `sitespeed.io`(maybe 6.0 or later)? If you think `sitespeed.io` should not do such things, can you give us some advice? we now very reliant on it because its great capability. We also hope `sitespeed.io` would be better and more powerful.
Thanks and looking forward to your reply~

**Comment by soulgalore** [comment] 2017-10-20 23:30
Hi @Poytr1 I think that is described in the branch https://github.com/sitespeedio/browsertime/tree/selenium-script  however I'm not 100% sure the metrics will be measured, lets try out that first

If you know a tool where you tested and verified that it really picks up changes, that's really appreciated, since I haven't seen a tool that fixed this in a good way yet.

Best
Peter

**Comment by markshao** [comment] 2017-10-21 03:39
Thanks @soulgalore  for your quick response . I am working on the same team with @Poytr1 

I have reviewed the [browsertime] project (https://github.com/sitespeedio/browsertime/tree/selenium-script), looks like it doesn't meet out requirement. 

Currently the `browsertime` gathering the metrics starts from an "HTTP Get" action ,  the selenium script here is only used for setting the authentication cookie . But in our business , we need to gather the performance starts from an "HTTP POST" action . Need to know the rendering performance after post a form (uploading a picture) and waiting for the entire result page fully rendered.

Maybe a new pull request for the browsertime is necessary ?  @soulgalore how do you think about it ?

**Comment by soulgalore** [comment] 2017-10-21 15:38
Hey @markshao I think the code is hard to read. That change would make it possible to run a selenium script instead of a URL so whatever you can do in Selenium you can do that here too (will open up to measure a full flow). However we haven't had time yet to synch within the project that is the way forward. Another solution would be to run navigate using raw JavaScript. Let me get back next weekend when we had some time speak to each other.

Best
Peter

**Comment by soulgalore** [comment] 2017-10-21 15:39
@markshao and PR are of course always welcome, we just need to discuss how to solve it.

**Comment by markshao** [comment] 2017-10-22 13:48
@soulgalore look forward to see some progress on this discussion next week .  We can provide more detail information from our requirement if it is helpful  @Poytr1 .

**Comment by soulgalore** [comment] 2017-10-30 04:12
Hi @markshao @Poytr1 we did not get the time to fully discuss it last week (we moved on the fixes for the plugin structure). My feeling when I thought about is that it is complex. If you have time it would be great to explain your exact use case so we have the full picture.

Thanks!
Peter

**Comment by Poytr1** [comment] 2017-10-30 07:15
@soulgalore Thanks for replying, I will give you more details as follows.
Now `browsertime` gathers all metrics while visiting a specific URL and selenium just works for preparing cookies or cache.I think we can give selenium script more jobs like adding a hook attached to some specific operations of selenium driver so it can sniff URL change and gather browser's metrics during this process .
In our scenario, we want to start gathering all metrics when a picture is uploaded using selenium driver, and the page turn to the result page along with the new URL. So for `visualmetrics`, Video starts recording when uploading pictures，stops until the result page is fullly rendered.

**Comment by markshao** [comment] 2017-11-01 14:02
I think the problem is how to define the start and end point of the video recorded by the script. Under that circumstance, the video will not start from blank page . Looks like there also need a change on the `visualmetrics.py` project.

**Comment by soulgalore** [comment] 2017-11-24 12:27
I created a discussion issue for this and closing all other issues: #1827 
That will makes it simpler for us since we have many issues something like this one! Let us do all the talking there :)

**Closed by soulgalore** 2017-11-24 12:27 UTC
