### ISSUE TITLE
Disabling saving of report/video

### ISSUE THREAD

**Issue by atiro** [sitespeedio/sitespeed.io#2377] opened 2019-03-18 10:43 UTC
I'm trying to disable the screenshots/videos being saved to disc for some runs to save space. I'm passing the options '--plugins.remove screenshot --plugins.remove html --video=false' but it seems to have no effect. Are there any other flags I should/can set ? I don't want to disable visualMetrics being generated or the HAR data being saved, but I don't want the large image/video files retained after the run.

(Running docker version latest on Ubuntu Linux)

**Comment by soulgalore** [comment] 2019-03-18 10:58
Hi @atiro thanks for creating the issue! Hmm I think it's bug for disabling the screenshot. First the documentation isn't reflecting the latest version(s) and it should work with --browsertime.screenshot false or something like that, but it doesn't. Let me have a look at it tonight.

Disable video works for me if I run like this:
`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://www.sitespeed.io/ --video false` 

Can you share an exact example on how you run when the video isn't removed? Thanks!

Best
Peter

**Comment by atiro** [comment] 2019-03-18 11:14
Hi Peter,

Thanks for the speedy reply. I'm running:

docker run --network sitespeed_default --rm -v [PATH]:/sitespeed.io sitespeedio/sitespeed.io -d 1 -r /tmp/ --graphite.host=graphite --plugins.remove screenshot --plugins.remove html --video=false [URL]

which retains both screenshots and videos.

If I use --visualMetrics=false as well, videos are not kept but screenshots still are:

docker run --network sitespeed_default --rm -v []PATH]:/sitespeed.io sitespeedio/sitespeed.io -d 1 -noYslow=true --plugins.add /sitespeed.io/plugin-gpsi --gpsi.key [KEY] --graphite.host=graphite --graphite.namespace=sitespeed_io.mobile --video=false --visualMetrics=false --visualElements=false -r /tmp/ --plugins.remove html --plugins.remove screenshot [URL]

There may be some old flags in there that can be removed (long time user!)

**Comment by soulgalore** [comment] 2019-03-18 19:59
Hi @atiro I've pushed a fix for screenshots (but not merged yet). I cannot reproduce the video though. 

Can you try:
`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.7.5 --video=false --plugins.remove screenshot --plugins.remove html https://www.sitespeed.io/ -n 1`

and see how that works for you?

Best
Peter

**Comment by atiro** [comment] 2019-05-15 15:59
Hi Peter, sorry for slow follow up. That seems to stop any videos being created, but all the images for it are still created (data/video/images/(1,2,3)). The screenshots are also still there in (data/screenshots)

**Comment by soulgalore** [comment] 2019-05-15 18:38
Tried it with latest release and yes it doesn't seems to work as it should. Let me look into when I find the time!

**Comment by soulgalore** [comment] 2019-11-19 01:36
This was fixed in the latest major.

**Closed by soulgalore** 2019-11-19 01:36 UTC
Labels: bug
