### ISSUE TITLE
Frequently getting ScriptTimeoutError

### ISSUE THREAD

**Issue by senthilr2k** [sitespeedio/sitespeed.io#1907] opened 2018-02-07 11:27 UTC
I pulled latest version of sitespeed using docker. I am very frequently getting the below error, could you please help

[2018-02-07 11:25:05] ERROR: ScriptTimeoutError: Timed out
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.executeAsyncScript (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:891:17)
    at Promise.try (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:225:26)
From previous event:
    at SeleniumRunner.runAsyncScript (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:219:23)
    at FirefoxDelegate.onStopIteration (/usr/src/app/node_modules/browsertime/lib/core/engineDelegate/firefoxDelegate.js:46:36)
    at Promise.resolve.tap.tap.tap.tap.tap.tap.tap.tap.tap.results (/usr/src/app/node_modules/browsertime/lib/core/engine.js:282:37)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:282:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:330:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:327:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:326:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:26)
    at /usr/src/app/node_modules/xvfb/index.js:55:28
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:207:22)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:206:12)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:210:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by soulgalore** [comment] 2018-02-07 11:29
Hi @senthilr2k we need the browser/URL and how you run so we can try to reproduce.

Thanks
Peter

**Comment by senthilr2k** [comment] 2018-02-07 11:33
[2018-02-07 11:28:38] INFO: Testing url https://www.verizonwireless.com/smartphones/lg run 1

**Comment by senthilr2k** [comment] 2018-02-07 11:36
browser is chrome

**Comment by senthilr2k** [comment] 2018-02-07 11:56
any specific reason we might get this kind of errors

**Comment by soulgalore** [comment] 2018-02-07 12:40
Hmm I cannot reproduce it, I've tested the latest Docker and running standalone on my Mac. Either it's some content that only comes sometimes or could it be that the instance you are using for testing is too small? How much memory do you have on that machine?

Best
Peter

**Comment by senthilr2k** [comment] 2018-02-07 12:46
the machine i'm using is having 32GB Ram

**Comment by soulgalore** [comment] 2018-02-07 14:32
Hmm, you say it is Chrome but from the trace log it is Firefox that is running, the method that gets the HAR from Firefox. Do you use the HAR/Har metrics? If not you can disable the HAR.

**Comment by Pe4enie** [comment] 2018-03-09 10:35
Hi @soulgalore. I'm currently having the same issue. Exists only for firefox and since quite some time now. You can look up my configuration in the other bug I reported (https://github.com/sitespeedio/sitespeed.io/issues/1861), currently i'm using the version 6.4.1 and getting this error

`[2018-03-09 11:30:10] ERROR: ScriptTimeoutError: Timed out
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.executeAsyncScript (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:891:17)
    at Promise.try (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:225:26)
From previous event:
    at SeleniumRunner.runAsyncScript (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:219:23)
    at FirefoxDelegate.onStopIteration (/usr/src/app/node_modules/browsertime/lib/core/engineDelegate/firefoxDelegate.js:46:36)
    at Promise.resolve.tap.tap.tap.tap.tap.tap.tap.tap.tap.tap.results (/usr/src/app/node_modules/browsertime/lib/core/engine.js:298:37)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:298:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:336:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:333:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:332:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:26)
    at /usr/src/app/node_modules/xvfb/index.js:55:28
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:209:22)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:208:12)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:210:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)`

for any page from my list I test with firefox.

run command is
`docker run $CABLE $DOCKER_SETUP $DOCKER_CONTAINER -b firefox $CONFIG $NO_LOGIN_URLS >> /tmp/s.log 2>&1` (preconfigured values are also there in other bug report)

Would really appreciate if you have a look at it :)
Thanks!

**Comment by soulgalore** [comment] 2018-03-09 11:35
@Pe4enie if I understand correctly it is the https://github.com/firebug/har-export-trigger that fails (we only run async script when we get the HAR). Quick solution is to `--skipHar` for Firefox, you will miss out on HAR information but you can still get visual metrics. 

The HAR plugin broke in FF 55 so I've been running without HAR for a while but I got some good news. Last night a fix landed in Firefox Nightly that makes it possible to run https://github.com/devtools-html/har-export-trigger instead of the old trigger (meaning we can update Firefox again). 

I've merged the new plugin yesterday in master (that will become 3.0) but if the works fine on Linux (I have only seen it work on Mac so far) I can backport it and make a release in the current 2.x so it will be possible to use the new exporter.

**Comment by Pe4enie** [comment] 2018-03-09 12:03
@soulgalore yap, that's what I also recognized (about --skipHar), that's why I said it exists for quite some time now. Was checking once in a while if it's fixed. Well, great news then. As soon as I can try it out on my setup with ubuntu, I can give some feedback.

Thanks!

**Comment by soulgalore** [comment] 2018-06-15 19:29
The new version of the HAR export trigger should fix @Pe4enie problem. For Chrome we still need to have the exact way to reproduce. Please re-open if you have a way to reproduce.

**Closed by soulgalore** 2018-06-15 19:29 UTC
