### ISSUE TITLE
Webpagetest screenshots are not reported back

### ISSUE THREAD

**Issue by ghost** [sitespeedio/sitespeed.io#2343] opened 2019-02-22 22:44 UTC
Hello,

I am experiencing an issue with getting back screenshots from webpagetest runs. I can see waterfall being retrieved and shown in html report. However, screenshots don't seem to be there. It looks like both are retrieved similarly on your end: https://github.com/sitespeedio/sitespeed.io/blob/7cc556220458748f5737325c8df86bea1193d6b4/lib/plugins/webpagetest/analyzer.js#L27

Thus, I was wondering what might be going wrong and whether I need to separately state that I want to retrieve Screenshots. 

Thanks!
----------
- Exact how you run: 
 docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.4.0 --config wpt-config.json -v
- Which version you are using
8.4.0
- OS (if you use Docker, report the base OS)
Docker/linux

**Comment by soulgalore** [comment] 2019-02-23 13:12
Hi @vladmgy thanks for your report! Ok so you don't see them?

We have a continuously WebPageTest test running where we test NY Times checkout https://s3.amazonaws.com/results.sitespeed.io/www.nytimes.com/2019-02-23-11-06-20/pages/www.nytimes.com/index.html#webpagetest

And there we have the screenshot downloaded:
<img width="721" alt="screen shot 2019-02-23 at 14 09 49" src="https://user-images.githubusercontent.com/540757/53286881-f2c15000-3774-11e9-9671-848dfe5320a1.png">

And you don't any error in the log etc? 

Best
Peter

**Comment by vladmgy** [comment] 2019-02-25 17:25
I don't see the screenshots folder under data in my results. I only see waterfall. Thus, waterfalls are displayed properly on my HTML results. 

I get Failed to load resource error in my log.

**Comment by soulgalore** [comment] 2019-02-25 19:26
Do you run your own WebPageTest instance? Can you share your config so I can try to reproduce?
Best
Peter

**Comment by vladmgy** [comment] 2019-02-25 20:42
This is what my config looks like:
`{   
    "gzipHAR": true,
    "browsertime":{
        "connectivity":{
            "profile":"cable"
        },
        "video": false
    },
    "html": {
        "fetchHARFiles": true
    },
    "graphite": {
        "host": "GRAPHITEHOST",
        "httpPort":80,
        "auth":"USER:PASS"
    },
    "slack": {
        "hookUrl": "SLACKHOOK",
        "userName": "WebPageTest"
    },
    "webpagetest": {
        "host": "WPTHOST",
        "location": "Linux",
        "private": false,
        "custom": "./custom-metrics.txt",
        "includeRepeatView": true,
        "lighthouse": true
    },
    "s3":{
        "bucketname":"RESULTSBUCKET",
        "removeLocalResult": true
    },
    "plugins": {
        "remove": ["browsertime"]
    },
    "metrics":{
        "filter": "webpagetest.pageSummary.data.lighthouse.categories.*.score"
    }
}`

I only intending on running WPT here. Thus, browsertime is removed.
Custom Metrics just specifies metrics to retrieve. I don't set anything specific related to screenshots.

**Comment by soulgalore** [comment] 2019-02-25 20:57
Do the screenshots exist on the WebPageTest server if you check the result page there? 

Best
Peter

**Comment by vladmgy** [comment] 2019-02-25 21:00
This is what on the WPT server inside of the results directory for any run. So yeah, it seems that those exist there.

<img width="1232" alt="screen shot 2019-02-25 at 12 59 26 pm" src="https://user-images.githubusercontent.com/47903966/53368300-38a92000-38fd-11e9-8f26-3b2d16984219.png">

**Comment by soulgalore** [comment] 2019-02-26 19:47
Ok, then I think it's either a WebPageTest API or server issue? I've missed, is it your own WPT instance or WebPageTest.org? If it's your own instance you could check the error logs if you can see the failing requests? Right now we send all the requests at the same time, maybe the WPT server can't handle that and we should add some delay.

**Comment by vldslvmgy** [comment] 2019-02-27 18:12
It's my own instance. I don't really see any failing requests there. 

So, there is nothing on sitespeed side that can cause this issue? I just find it weird that waterfalls are getting retrieved properly, but not the screenshots. There are no additional flags I need to enable to retrieve WPT screenshots?

**Comment by soulgalore** [comment] 2019-02-27 19:03
Getting screenshots works without any extra config on WebPageTest.org as in https://github.com/sitespeedio/sitespeed.io/issues/2343#issuecomment-466647562  - Do you have an [API key](https://www.webpagetest.org/getkey.php) so you can try your page there? I think what we maybe could do is to not send all the request to the WebPageTest API at once if the problem is that the server can't handle the requests.

**Comment by vldslvmgy** [comment] 2019-03-13 23:05
Sorry for a break. I checked the resource usage of my WPT instance. It seems fine even when running tests my usage is not exceeding limit.

**Comment by soulgalore** [comment] 2019-03-18 07:41
Ok, so if I understand: It looks fine own WebPageTets instance, and if you test to use WebPageTest.org using your API key, it also looks ok, but you get the same error from sitespeed.io that you don't see any screenshots, is that correct?

**Comment by wkhatri** [comment] 2019-06-03 03:39
Turning off full-resolution screenshot capture within settings.ini of webpagetest server config seems to have fixed the issue. 
```
;save png full-resolution screenshots
;pngss=1
```

**Comment by soulgalore** [comment] 2019-08-28 13:52
I've hit the same problem today setting up a new server, and disabling the full-resolution screenshot did the trick for me too, I'll create an upstream issue.

**Comment by soulgalore** [comment] 2019-08-28 15:37
This is fixed upstream now.

**Comment by soulgalore** [comment] 2019-11-19 01:37
This was fixed upstream so closing.

**Closed by soulgalore** 2019-11-19 01:37 UTC
Labels: need more info
