### ISSUE TITLE
 ERROR: Could not add meta data to the HAR, miss page<number>

### ISSUE THREAD

**Issue by vishnusn656** [sitespeedio/sitespeed.io#3301] opened 2021-03-05 15:25 UTC
While running Sitespeed script for higher number of iterations(Greater than 20), result collation is failing with following messages in console: "ERROR: Could not add meta data to the HAR, miss page<Number>" ",  ERROR: Could not find the right index 145 for har for url<url>", and  "ERROR: Caught error from Browsertime Error: PageIndex out of range".  When same script is executed under exact same conditions upto 20 iterations, no error is observed and gets all data in html as well as influx. What could be the potential reasons for this behavior?   I did not cross verify my script, since it is working fine up to 20 iterations.

**Comment by vishnusn656** [comment] 2021-03-05 15:57
Latest Update: After verifying the logs of 30 iteration test, it was found that 8th iteration had an assertion error in it and hence script continued with 9th iteration and successfully completed up to 30th iteration. Failure in one iteration out of 30 iteration is causing the above mentioned errors. Data is not pushed to influxdb as well.

**Comment by soulgalore** [comment] 2021-03-06 08:19
Hi @vishnusn656 thanks for creating the issue, can you please follow https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue and make a reproducible test case and I can have a look, thanks!

**Comment by soulgalore** [comment] 2021-04-13 17:37
And there is not a more complicated flow than you explain? There's only one measure.start right. I think in the same where you get the failure your
> //Navigate to a url/click a button to load new page

doesn't seem to work, I would try to add some more try/catch there for those elements and try to see what goes wrong.

**Comment by soulgalore** [comment] 2022-02-12 16:21
Closing since I didn't get any feedback.

**Closed by soulgalore** 2022-02-12 16:21 UTC
Labels: awaiting response
