### ISSUE TITLE
Timeout loading page in Firefox browser.

### ISSUE THREAD

**Issue by sureshkrishnaselvam** [sitespeedio/sitespeed.io#2178] opened 2018-10-10 13:54 UTC
@soulgalore I am facing issue in Firefox browser when I execute test from config.json file, but the same config.json file works fine for chrome browser. Do I need to change anything in configuration, can you please help me to find out the issue in this.

Here is the **config.json**,

{
  "browsertime": {
  "iterations": 1,
  "browser": "firefox",
  "visualMetrics" : true,
  "connectivity" :{
    "profile" : "3gfast"
    },
  "videoParams": {
    "combine": true
    },
    "video": true
  },
  "xvfb": true,
  "firefox": {
      "args": [
        "no-sandbox"
      ]
    },
  "html": {
    "showAllWaterfallSummary": true
  },
  "outputFolder": "test/performance/reports/appointment",
  "mobile": true,
  "budget": {
    "configPath": "budget.json",
    "output": "tap"
  },
  "utc": true
}

**Error Log:**

[2018-10-10 11:20:26] INFO: Catched a WebDriverError [Timeout loading page after 300000ms]. Try one more time.TimeoutError: Timeout loading page after 300000ms
[2018-10-10 11:25:27] ERROR: WebDriverError:TimeoutError: Timeout loading page after 300000ms
[2018-10-10 11:25:27] ERROR: Could not load URLUrlLoadError: Failed to load https://www.google.com, cause: Timeout loading page after 300000ms
[2018-10-10 11:25:28] ERROR: https://www.google.com generated the following error in Browsertime UrlLoadError: Failed to load https://www.google.com
    at getUrl.then.then.catch.catch.e (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:176:15)
    at tryCatcher (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2018-10-10 11:25:28] INFO: Write budget to /sitespeed.io/test/performance/reports/google/budget.tap
[2018-10-10 11:25:29] INFO: HTML stored in /sitespeed.io/test/performance/reports/google
[2018-10-10 11:25:29] INFO: Finished analysing https://www.google.com

**Comment by sureshkrishnaselvam** [comment] 2018-10-11 08:43
Hi @soulgalore thanks for looking into this issue, even I too got the same error for mobile breakpoint. Its working for desktop breakpoint. 

**TypeError:** Cannot read property '2' of null
    at FirefoxDelegate.onStopIteration (/usr/src/app/node_modules/browsertime/lib/core/engineDelegate/firefoxDelegate.js:58:33)
    at <anonymous>

**config.json:**

{
  "browsertime":{
    "iterations":1,
    "browser": "firefox",
    "speedIndex": true,
      "connectivity" :{
        "profile" : "3gfast"
        }
    },
    "xvfb": true,
    "firefox": {
      "args": [
        "no-sandbox"
      ]
    },
    "html": {
    "showAllWaterfallSummary": true
  },
  "outputFolder": "test/performance/reports/appointment",
  "mobile": false,
  "budget": {
    "configPath": "budget.json",
    "output": "tap"
  },
    "utc": true
}

**Comment by soulgalore** [comment] 2018-10-11 08:54
@sureshkrishnaselvam I did a fix release yesterday 7.5.1 where that problem is fixed.

**Comment by sureshkrishnaselvam** [comment] 2018-10-11 09:06
@soulgalore Thanks for the immediate fix, I am able to execute the test now in firefox, but getting error for chrome. Could you please help on this.

**Error Log:**
[2018-10-11 09:05:25] ERROR: TypeError: Cannot read property '_meta' of undefined
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:137:58)
    at <anonymous>

**Comment by soulgalore** [comment] 2018-10-11 09:41
It looks like https://github.com/sitespeedio/sitespeed.io/issues/2091#issuecomment-428498331 ? Are you using a prescript? The problem there is that we don't create a new page object in the HAR from Chrome. I could probably fix that but I need reproducible code so I can fix and verify that it works. Can you help with that? We have a section in the documentation that can help: https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue

Best
Peter

**Comment by soulgalore** [comment] 2019-02-17 17:12
Closing this since we never heard back, but please ping the issue again if you still have the issue so we can help you!

**Closed by soulgalore** 2019-02-17 17:12 UTC
Labels: need more info

**Comment by anhptn87** [comment] 2019-07-23 09:55
I have the same error when running the test with Firefox: Timeout loading page after 300000ms
Firefox quantum 68.0.1 (64bit); selenium 2; Running test under a proxy

This issue not always happens. It only happens with some URL and the occurrence rate is about 1/5
