### ISSUE TITLE
Sitespeed.io not running with https

### ISSUE THREAD

**Issue by sourabhsharma487** [sitespeedio/sitespeed.io#1222] opened 2016-09-27 08:04 UTC
Hi there,

I am interested to run sitespeed.io however I am unable to run sitespeed.io with https and it is working on protocol http as expected. Below is the version details, I am using : 

Sitespeed.io: 4.0.0-beta.3
node: v6.5.0
npm: 3.10.3

How did I install it:      npm install -g sitespeed.io@4.0.0-beta.3
Command which I am executing:  sitespeed.io https://www.jbscotch.com 

Below is the error detail:
[2016-09-26 21:34:49] **Versions OS: linux 2.6.32-504.el6.x86_64 nodejs: v6.5.0 sitespeed.io: 4.0.0-beta.3 browsertime: 1.0.0-beta.5 coach: 0.27.0**
[2016-09-26 21:34:51] Starting chrome for analysing https://www.jbscotch.com 3 time(s)
[2016-09-26 21:34:51] Testing url https://www.jbscotch.com run 1
[2016-09-26 21:34:51] https://www.jbscotch.com generated the **following error in Browsertime BrowserError: Server terminated early with status 1**
    at BrowsertimeError (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:79:15)
From previous event:
    at SeleniumRunner.start (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:78:13)
    at runIteration (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:158:21)
    at Promise.reduce (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:233:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:232:17)
From previous event:
    at Engine.run (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:231:8)
    at engine.start.then (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:88:26)
From previous event:
    at Object.analyzeUrl (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:88:8)
    at Object.processMessage (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:150:27)
    at queue.process (/usr/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback](timers.js:533:5)
[2016-09-26 21:34:51] Render HTML for 1 page(s)
**[2016-09-26 21:34:53] HTML stored in /root/sitespeed-result/www.jbscotch.com/2016-09-26-21-34-49
[2016-09-26 21:34:53] Finished analysing https://www.jbscotch.com**

Please confirm in case I missed anything to make it a perfect run.

Regards,
Sourabh Sharma

**Comment by sourabhsharma487** [comment] 2016-09-29 07:55
Anyone there specially from team who created sitespeed.io may respond on this, please ?

**Comment by soulgalore** [comment] 2016-09-29 08:02
It works for me on Mac OS X both for Chrome/FF (installed latest beta.4):
sitespeed.io https://www.jbscotch.com
[2016-09-29 10:00:22] Versions OS: darwin 16.0.0 nodejs: v4.6.0 sitespeed.io: 4.0.0-beta.4 browsertime: 1.0.0-beta.5 coach: 0.27.1
[2016-09-29 10:00:22] Starting chrome for analysing https://www.jbscotch.com 3 time(s)
[2016-09-29 10:00:22] Testing url https://www.jbscotch.com run 1
[2016-09-29 10:00:29] Testing url https://www.jbscotch.com run 2
[2016-09-29 10:00:36] Testing url https://www.jbscotch.com run 3
[2016-09-29 10:00:42] Render HTML for 1 page(s) 
[2016-09-29 10:00:44] HTML stored in /Users/peter/git/sitespeed.io/sitespeed-result/www.jbscotch.com/2016-09-29-10-00-22
[2016-09-29 10:00:44] Finished analysing https://www.jbscotch.com

But could it be that we get different content? I live in Sweden so I get the id popup since it's illegal with alcohol to kids here. Do you have some kind of redirect that happens otherwise?

Best
Peter

**Comment by brianjking** [comment] 2016-10-17 12:45
I can confirm this works using `beta.4` on macOS Sierra.

````
   ~  sitespeed.io https://theupbeatk9.com                                                                                                              07:37   17.10.16
[2016-10-17 07:41:19] Versions OS: darwin 16.0.0 nodejs: v6.8.0 sitespeed.io: 4.0.0-beta.4 browsertime: 1.0.0-beta.5 coach: 0.27.1
[2016-10-17 07:41:20] Starting chrome for analysing https://theupbeatk9.com 3 time(s)
[2016-10-17 07:41:20] Testing url https://theupbeatk9.com run 1
[2016-10-17 07:41:30] Testing url https://theupbeatk9.com run 2
[2016-10-17 07:41:38] Testing url https://theupbeatk9.com run 3
[2016-10-17 07:41:46] Render HTML for 1 page(s)
[2016-10-17 07:41:48] HTML stored in /Users/brianjking/sitespeed-result/theupbeatk9.com/2016-10-17-07-41-19
[2016-10-17 07:41:48] Finished analysing https://theupbeatk9.com
````

**Comment by soulgalore** [comment] 2016-10-28 09:38
I think works, please re-open if you still have problems.

**Comment by sourabhsharma487** [comment] 2016-11-03 10:58
Hi Peter,

It works good for me on MacOS moreover it is not working on CentOS 6/7.  I have tried to run sitespeed.io with latest version i.e. beta 4. 

Just to update you that latest version of sitespedd.io is not working for me. Below is the detail:

sitespeed.io https://www.google.com
[2016-11-03 16:27:33] Versions OS: linux 2.6.32-504.el6.x86_64 nodejs: v6.9.0 sitespeed.io: 4.0.3 browsertime: 1.0.0-beta.9 coach: 0.28.4
[2016-11-03 16:27:34] Starting chrome for analysing https://www.google.com 3 time(s)
[2016-11-03 16:27:34] Testing url https://www.google.com run 1
[2016-11-03 16:27:34] https://www.google.com generated the following error in Browsertime BrowserError: Server terminated early with status 1
    at BrowsertimeError (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:79:15)
From previous event:
    at SeleniumRunner.start (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:78:13)
    at runIteration (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:167:21)
    at Promise.reduce (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:242:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:241:17)
From previous event:
    at Engine.run (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:240:8)
    at engine.start.then (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:26)
From previous event:
    at Object.analyzeUrl (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:8)
    at Object.processMessage (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:129:27)
    at queue.process (/usr/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
[2016-11-03 16:27:34] Render HTML for 1 page(s)
[2016-11-03 16:27:37] HTML stored in /root/sitespeed-result/www.google.com/2016-11-03-16-27-33
[2016-11-03 16:27:37] Finished analysing https://www.google.com

Could you please help me to get this resolved. Please let me know in case you need more information at my end.

Regards,
Sourabh

**Comment by tobli** [comment] 2016-11-03 11:46
Hi @sourabhsharma487 
What version of Chrome are you running? Sitespeed.io bundles the current version of Chromedriver, used to communicate with Chrome. It only support recent versions of Chrome, see http://chromedriver.storage.googleapis.com/2.25/notes.txt.
The title mentions https, are you only seeing issues with https sites, or http as well?
If you could test with Firefox as well, it'd help to narrow down the issue.

**Comment by soulgalore** [comment] 2016-11-03 22:40
@sourabhsharma487 you could also test our Docker version, then we can rule out version problems.

**Comment by soulgalore** [comment] 2017-03-03 08:30
Closing for lack of info.

**Closed by soulgalore** 2017-03-03 08:30 UTC
