### ISSUE TITLE
Internet explorer

### ISSUE THREAD

**Issue by measureworks** [sitespeedio/sitespeed.io#553] opened 2015-01-06 14:37 UTC
He Peter and Tobias,

We are running sitespeed in windows to crawl urls with Internet Explorer (and safari in the future) but in the end it is not able to kill the javaprocess.

Kind regards,
Ingrid

**Comment by soulgalore** [comment] 2015-01-08 00:01
Yes I get the same, think we have a duplicate of this, need to check.

**Comment by soulgalore** [comment] 2015-03-09 10:18
This was fixed a couple of releases ago.

**Closed by soulgalore** 2015-03-09 10:18 UTC
