### ISSUE TITLE
config.json plugin add  field no work

### ISSUE THREAD

**Issue by linqunhe** [sitespeedio/sitespeed.io#3744] opened 2022-10-19 07:24 UTC
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://glitch.com/

### What are you trying to accomplish

use json config:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/80025623/196623381-3c52b241-c471-4cdd-8670-f26a41710c55.png">
add plugin no work

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/80025623/196623520-2c1592aa-84e6-4698-be84-a780e9358ce4.png">

use load field , it work , but output warning
<img width="248" alt="image" src="https://user-images.githubusercontent.com/80025623/196623580-a58d3065-cc74-4120-8841-5e42e831b8b1.png">
<img width="1581" alt="image" src="https://user-images.githubusercontent.com/80025623/196623705-b1f6a165-d444-49df-8b2a-129e05bc6e08.png">

### What browser did you use?

Other

### How to reproduce

```shell
{
  "browsertime": {
    "iterations": 1,
    "browser": "chrome",
    "viewPort": "1920x1080",
    "cpu": true,
    "spa": true,
    "delay": 1000,
    "cacheClearRaw": true,
    "videoParams": {
      "framerate": 24,
      "filmstripQuality": 50,
      "convert": false,
      "createFilmstrip": false
    },
    "screenshotParams": {
      "png": {
        "compressionLevel": 5
      }
    },
    "timeouts": {
      "pageCompleteCheck": 4500000
    },
    "visualMetricsPortable": true,
    "skipHar": true,
    "chrome": {
      "collectNetLog": true,
      "timeline": true,
      "collectLongTasks": true
    }
  },
  "decimals": 2,
  "utc": true,
  "summaryDetail": true,
  "html": {
    "topListSize": 3,
    "logDownloadLink": false,
    "showScript": false,
    "fetchHARFiles": true
  },
  "filmstrip": {
    "showAll": false
  },
  "plugins": {
    "list": true,
    "add": [
      "analysisstorer",
      "coach"
    ],
    "remove": [
      "axe",
      "sustainable",
      "/lighthouse",
      "/gpsi",
      "budget",
      "assets",
      "grafana",
      "graphite",
      "slack",
      "s3"
    ]
  },
  "useHash": true
}
```

**Comment by soulgalore** [comment] 2022-10-19 11:09
If I use add it seems to work for me:

config.json

```JSON
{
    "plugins": {
      "list": true,
      "add": [
        "analysisstorer"
      ],
      "remove": [
        "coach"
      ]
   }
}
```

```
sitespeed.io --config config.json https://www.sitespeed.io -n 1 -o
...
[2022-10-19 13:05:29] INFO: The following plugins are enabled: assets, browsertime, budget, domains, harstorer, html, lateststorer, metrics, pagexray, remove, text, thirdparty, tracestorer, analysisstorer
....

```

**Comment by linqunhe** [comment] 2022-12-15 03:56
Hi， I have retry...
I don’t seem to be able to do it here, and my configuration file uses the inheritance scheme you provided, you can see the video execution effect 


https://user-images.githubusercontent.com/80025623/207768914-f6d7ecd9-1812-460c-9438-7458e0172b15.mp4




#### env
- node 16
- macos
- docker
- sitespeed 26.1.0

tks...

**Comment by soulgalore** [comment] 2023-12-27 16:14
I couldn't reproduce so closing.

**Closed by soulgalore** 2023-12-27 16:14 UTC
Labels: bug
