### ISSUE TITLE
Domain  change  is not working on Firefox

### ISSUE THREAD

**Issue by TusAuto** [sitespeedio/sitespeed.io#2987] opened 2020-05-11 12:40 UTC
1.URL Under test [ Can not provide as Company Policy ]
2. First we have sign in button screen and then Email address and password page to submit.
3. We are trying to measure page responsiveness after Sign in page.But some how after Sign in ..script unable to input Email address. Tried lot many times with wait as well . I have checked the same script is working fine with Chrome browser.
4. Even same script[ .js] is working fine with different url with firefox.
5. Sitespeed.io: 12.9.0 Firefox : 76   OS: windows 10
6. Please find the logs attached.

[Firfox log.txt](https://github.com/sitespeedio/sitespeed.io/files/4609578/Firfox.log.txt)

**Comment by soulgalore** [comment] 2020-05-11 18:43
Hi @TusAuto try to increase the memory where you run your tests. Do you run in Docker?

**Comment by TusAuto** [comment] 2020-05-12 03:01
hey @soulgalore  yes i am executing in docker and tried to executing it with increase in memory size  2g many times but no luck :(   even  3g memory is also not working.  
Please suggest other solution .

**Comment by TusAuto** [comment] 2020-05-21 13:33
@soulgalore : Please suggest other solution.

**Comment by soulgalore** [comment] 2020-05-21 17:22
Hi @TusAuto I meant the memory on the server, was it that you increased? Those kind of errors usually is caused by running on a too small instance.

**Comment by TusAuto** [comment] 2020-05-22 06:15
Hi @soulgalore  I have increased memory on server by 2g. Even tried with 3g as well but no luck.

**Comment by soulgalore** [comment] 2020-07-06 07:28
That's in the Docker container (2g/3g). I think memory on the server?

**Comment by soulgalore** [comment] 2021-04-13 18:16
Closing since lack of info.

**Closed by soulgalore** 2021-04-13 18:16 UTC
Labels: need more info
