### ISSUE TITLE
Error with docker build

### ISSUE THREAD

**Issue by scabenga** [sitespeedio/sitespeed.io#2821] opened 2019-12-12 07:55 UTC
Hi All,

I'm getting the below error when trying to build the docker image:

Step 11/24 : RUN wpr installroot --https_cert_file /webpagereplay/certs/wpr_cert.pem --https_key_file /webpagereplay/certs/wpr_key.pem
 ---> Running in d411c3b421a9
/bin/sh: 1: wpr: Permission denied
The command '/bin/sh -c wpr installroot --https_cert_file /webpagereplay/certs/wpr_cert.pem --https_key_file /webpagereplay/certs/wpr_key.pem' returned a non-zero code: 126

I've tried with sudo.
Any ideas?

Thanks,
Scabs

**Comment by soulgalore** [comment] 2019-12-12 20:15
Hi @scabenga hmm, I can't reproduce but it looks like wpr has wrong execution rights. Can you try chmod to change it?

Best
Peter

**Comment by scabenga** [comment] 2019-12-13 08:11
Thanks @soulgalore, that issue is now fixed :)
On to the next error...

```
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
/usr/src/app/node_modules/sharp/install/libvips.js:82
          throw err;
          ^

Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
```

**Comment by soulgalore** [comment] 2019-12-13 09:46
Do you use our Dockerfile or do you do your own?  Do you use latest Docker to build?

**Comment by soulgalore** [comment] 2019-12-13 09:47
We autobuild at the Docker hub and we don't get those errors there: https://hub.docker.com/r/sitespeedio/sitespeed.io-autobuild/builds

**Comment by soulgalore** [comment] 2021-04-15 14:55
I'm closing, I haven't run into those errors. Please let me know in a new issue if you ever have problems building the Docker containers.

**Closed by soulgalore** 2021-04-15 14:55 UTC
Labels: need more info
