### ISSUE TITLE
Chrome mobile emulation visually complete flicker between 99 and 100%

### ISSUE THREAD

**Issue by kkopachev** [sitespeedio/sitespeed.io#1690] opened 2017-08-03 18:26 UTC
Was not sure to what repo to post, but running latest sitespeed.io in docker container and VisuallyComplete metric on mobile emulation (Chrome). So VisuallyComplete happening at around 20 seconds for some reason, where Visuallycomplete85 is around 3-5 seconds or so. Then there is no visual changes happening on the page.
![image](https://user-images.githubusercontent.com/2279051/28937076-94252216-783e-11e7-9505-44a7ab4e949e.png)

**Comment by soulgalore** [comment] 2017-08-03 18:45
Hey @kkopachev are you really sure nothing is changing in the video? [VisualMetrics](https://github.com/WPO-Foundation/visualmetrics) also creates some small screenshots by default for each change, have you checked them too and can confirm?

Best
Peter

**Comment by kkopachev** [comment] 2017-08-03 18:56
Checked screenshots and yes, there is a change - chrome shows "Loading blahblah.com" in left bottom corner. VisualMetrics seem to react on that and treat it as a page change. There is no visual changes to the rendered page itself.
These are last 3 screenshots it saved:

![ms_023166](https://user-images.githubusercontent.com/2279051/28938348-afec2112-7842-11e7-872f-8233222952d4.jpg)
---------------------------
![ms_023200](https://user-images.githubusercontent.com/2279051/28938352-b153e0e4-7842-11e7-9a8a-bce77d43297b.jpg)
---------------------------
![ms_023250](https://user-images.githubusercontent.com/2279051/28938353-b25a6300-7842-11e7-89ff-75f4a7f4030d.jpg)

**Comment by soulgalore** [comment] 2017-08-03 19:30
ok thanks, think we need to check then if we can fine tune the configuration.

**Comment by soulgalore** [comment] 2017-08-05 13:08
I'll have a go with this when I'm back from vacation so it will take a week or so before I can start. If anyone else have the time, have a try in Browsertime (needs to be fixed there).

**Comment by soulgalore** [comment] 2017-08-18 04:48
Hey @kkopachev now I'm back. Can you show me your config how you run? I tried to reproduce but for me the last part of the screen isn't picked up, but I think then it is different depending on viewport. I tried with default setting mobile to iPhone 6 (I did it in Browsertime so it's easier for me to debug):

`docker run --privileged --shm-size=1g --rm -v "$(pwd)":/browsertime-results sitespeedio/browsertime --video --speedIndex -n 1 --chrome.mobileEmulation.deviceName 'iPhone 6' https://www.popsugar.com/ -c cable`

Best
Oeter

**Comment by kkopachev** [comment] 2017-08-23 21:28
Hi @soulgalore I tried your command and it works fine, however, if I add viewport size to it [(as sitespeed.io adds)](https://github.com/sitespeedio/sitespeed.io/blob/3debfec0b4b2f721749ae197cc37e329a5afeae0/lib/plugins/browsertime/analyzer.js#L55) then that "Loading..." thing taken into account calculating last visual change. Here is command I ran to repro:

`docker run --privileged --shm-size=1g --rm -v "$(pwd)":/browsertime-results sitespeedio/browsertime --video --speedIndex -n 1 --chrome.mobileEmulation.deviceName 'iPhone 6' --viewPort '360x640' 'https://www.popsugar.com/' -c cable`

**Comment by soulgalore** [comment] 2017-08-24 04:46
Thanks @kkopachev I missed that, let me have a look asap!

**Comment by soulgalore** [comment] 2017-08-26 13:47
Had a go at this today to check if there's something we could do just by configuring VisualMetrics but no look, I'll need to change where we set the offset for the video that adds some testing, let me continue with that.

**Comment by soulgalore** [comment] 2017-09-13 16:05
Sorry for not getting back, I'll continue this weekend.

**Comment by soulgalore** [comment] 2017-09-13 16:55
I actually tried it out and got a solution for it, but need to do a change in the VisualMetrics script. I'll do the change probably tomorrow but also wanna check if it can be changed upstream, that makes it easier in the future.

**Comment by soulgalore** [comment] 2017-09-13 17:19
I made a fix in master for browsertime: https://github.com/sitespeedio/browsertime/commit/a4c0d76e539383b2f19c50673a92fc44afbe4487 

It works for me now. Roll it out in the next release (hopefully this weekend).

**Comment by soulgalore** [comment] 2017-09-14 07:13
Released this yesterday in sitespeed.io so I hope it will work now :)

**Comment by kkopachev** [comment] 2017-09-15 18:05
Hi Peter!
Tried latest sitespeed.io image and it didn't solve the problem, but created other problems.
http://sitespeedio.sugarops.com/www.popsugar.com/2017-09-15-14-17-11/pages/www.popsugar.com/celebrity/Easy-Halloween-Costumes-Women-Color-42592271/query-3b2b8401/data/video/0.mp4

There are no ovelay "First/Last paint" timings on the video (didn't find in changelog if new flag was introduced?)
Visual progress still jumps 99% -> 95%->99%.
At the very end of video page all the sudden scaled up 2x and then back to normal 1x. That's when video ends. 
Same issue in screenshots it generated. This was not happening with version 5.4.4.

**Comment by soulgalore** [comment] 2017-09-15 20:35
Hi @kkopachev 
thanks for getting back. The timer was a mistake by me when I pushed the new version of Browsertime, pushing a fix release now.

The size, I think something has changed in Chrome 61, but I haven't looked into it yet: https://github.com/sitespeedio/browsertime/issues/367 - I'll look later, else I'll rollback the to Chrome 60.

For Visual Progress, hmm it worked when I tried it Browsertime, but I'll try more this weekend, can set the diff to larger.

**Comment by soulgalore** [comment] 2017-09-16 19:56
That upscaling, it doesn't happen when I try, it's strange. 

I changed the margin again, now it is bigger and it will work for Linux but run on Mac it will still fail, I think the 2x DPI density is the problem. Is it easy for you to test from master (if you run on Linux but I guess you are)?

Best
Peter

**Comment by soulgalore** [comment] 2017-09-16 22:52
When I looked closer I could reproduce, I'll rollback to 60 and if that works, I'll report a bug in Chrome.

**Comment by kkopachev** [comment] 2017-09-19 21:20
5.6.2 fixed the main issue. Inappropriate scaling at the end of video gone as well. Timings are back.

**Comment by soulgalore** [comment] 2017-09-20 07:08
Ok good. I'll increased the the diff now to 25 (that is the same as WebPageTest, it's different values in VisualMetrics and WebPageTest. For the scaling, I'll run a test on CHrome 62 in master for a while and hope that it is gone (there have been multiple problems with the emulated mobile in the past), if that still fails, I'll create a bug in Chrome.

**Comment by soulgalore** [comment] 2017-09-20 07:33
No couldn't upgrade to 62 because of https://bugs.chromium.org/p/chromium/issues/detail?id=766674

**Comment by soulgalore** [comment] 2019-01-25 13:31
I haven't seen this for our tests at work so I guess this has been fixed in Chrome/Chromdriver some time ago. Please re-open if there still is an issue.

**Closed by soulgalore** 2019-01-25 13:31 UTC
Labels: Chrome, bug
