### ISSUE TITLE
The example from sitespeed.io is returning and exception with an unknown error with version 4.0

### ISSUE THREAD

**Issue by rpkoller** [sitespeedio/sitespeed.io#1275] opened 2016-10-28 01:40 UTC
Hi I've learned about sitespeed.io today and installed version 4.0 with `npm install -g sitespeed.io`on OSX 10.11.6 all the latest patches applied. For Node in version 7.0 `prefix = ${HOME}/.npm_global` is set in `.npmrc`. Right after the installation I've tried the example listed on the sitespeed.io homepage:

`sitespeed.io https://en.wikipedia.org/wiki/Main_Page https://en.wikipedia.org/wiki/Barack_Obama -c cable -b chrome`

Chrome has version `54.0.2840.71 (64-bit)` installed. The two urls from the example line are valid and reachable from the browser but when i run the command i get the following error messages in the terminal (chrome opens a window showing or loading nothing twice and sitespeed is writing and output to my home directory as well but without any output data): 

```
$> sitespeed.io https://en.wikipedia.org/wiki/Main_Page https://en.wikipedia.org/wiki/Barack_Obama -c cable -b chrome
(node:6290) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[2016-10-28 03:33:44] Versions OS: darwin 15.6.0 nodejs: v7.0.0 sitespeed.io: 4.0.0 browsertime: 1.0.0-beta.9 coach: 0.28.4
[2016-10-28 03:33:44] Starting chrome for analysing https://en.wikipedia.org/wiki/Main_Page 3 time(s)
[2016-10-28 03:33:45] Start tsproxy:/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/vendor/tsproxy.py --rtt 28 --inkbps 5000 --outkbps 1000 -p 1080
[2016-10-28 03:33:45] Testing url https://en.wikipedia.org/wiki/Main_Page run 1
[2016-10-28 03:33:47] https://en.wikipedia.org/wiki/Main_Page generated the following error in Browsertime BrowserError: session not created exception
from unknown error: bad inspector message: {"method":"Network.responseReceived","params":{"requestId":"6301.1","frameId":"6301.1","loaderId":"6301.1","timestamp":61761,446385,"type":"Document","response":{"url":"data:,","status":200,000000,"statusText":"OK","headers":{"Access-Control-Allow-Origin":"*","Content-Type":"text/plain;charset=US-ASCII"},"mimeType":"text/plain","connectionReused":false,"connectionId":0,000000,"fromDiskCache":false,"fromServiceWorker":false,"encodedDataLength":-1,000000,"protocol":"data","securityState":"unknown"}}}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
from unknown error: bad inspector message: {"method":"Network.responseReceived","params":{"requestId":"6301.1","frameId":"6301.1","loaderId":"6301.1","timestamp":61761,446385,"type":"Document","response":{"url":"data:,","status":200,000000,"statusText":"OK","headers":{"Access-Control-Allow-Origin":"*","Content-Type":"text/plain;charset=US-ASCII"},"mimeType":"text/plain","connectionReused":false,"connectionId":0,000000,"fromDiskCache":false,"fromServiceWorker":false,"encodedDataLength":-1,000000,"protocol":"data","securityState":"unknown"}}}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
    at startBrowser.call.catch.tap.tap.catch.catch (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:79:15)
From previous event:
    at SeleniumRunner.start (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:78:13)
    at runIteration (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:167:21)
    at Promise.reduce (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:242:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:241:17)
From previous event:
    at Engine.run (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:240:8)
    at engine.start.then (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:26)
From previous event:
    at Object.analyzeUrl (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:8)
    at Object.processMessage (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:128:27)
    at queue.process (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
[2016-10-28 03:33:47] Starting chrome for analysing https://en.wikipedia.org/wiki/Barack_Obama 3 time(s)
[2016-10-28 03:33:47] Start tsproxy:/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/vendor/tsproxy.py --rtt 28 --inkbps 5000 --outkbps 1000 -p 1080
[2016-10-28 03:33:47] Testing url https://en.wikipedia.org/wiki/Barack_Obama run 1
[2016-10-28 03:33:48] https://en.wikipedia.org/wiki/Barack_Obama generated the following error in Browsertime BrowserError: session not created exception
from unknown error: bad inspector message: {"method":"Network.responseReceived","params":{"requestId":"6311.1","frameId":"6311.1","loaderId":"6311.1","timestamp":61762,941255,"type":"Document","response":{"url":"data:,","status":200,000000,"statusText":"OK","headers":{"Access-Control-Allow-Origin":"*","Content-Type":"text/plain;charset=US-ASCII"},"mimeType":"text/plain","connectionReused":false,"connectionId":0,000000,"fromDiskCache":false,"fromServiceWorker":false,"encodedDataLength":-1,000000,"protocol":"data","securityState":"unknown"}}}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
from unknown error: bad inspector message: {"method":"Network.responseReceived","params":{"requestId":"6311.1","frameId":"6311.1","loaderId":"6311.1","timestamp":61762,941255,"type":"Document","response":{"url":"data:,","status":200,000000,"statusText":"OK","headers":{"Access-Control-Allow-Origin":"*","Content-Type":"text/plain;charset=US-ASCII"},"mimeType":"text/plain","connectionReused":false,"connectionId":0,000000,"fromDiskCache":false,"fromServiceWorker":false,"encodedDataLength":-1,000000,"protocol":"data","securityState":"unknown"}}}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
    at startBrowser.call.catch.tap.tap.catch.catch (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:79:15)
From previous event:
    at SeleniumRunner.start (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:78:13)
    at runIteration (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:167:21)
    at Promise.reduce (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:242:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:241:17)
From previous event:
    at Engine.run (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:240:8)
    at engine.start.then (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:26)
From previous event:
    at Object.analyzeUrl (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:8)
    at Object.processMessage (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:128:27)
    at queue.process (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
[2016-10-28 03:33:48] Render HTML for 2 page(s)
[2016-10-28 03:33:50] HTML stored in /Users/myuser/sitespeed-result/en.wikipedia.org/2016-10-28-03-33-44
[2016-10-28 03:33:50] Finished analysing https://en.wikipedia.org/wiki/Main_Page
```

Unsure if i did something wrong basically or if i ran into some bug or issues. If you need more specific infos let me know. Happy to help. Best regards Ralf

**Comment by rpkoller** [comment] 2016-10-28 02:04
Ok I've tried the same thing with Firefox as desired browser and there everything worked flawlessly: 

```
$> sitespeed.io https://en.wikipedia.org/wiki/Main_Page https://en.wikipedia.org/wiki/Barack_Obama -c cable -b firefox
(node:7455) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[2016-10-28 03:59:47] Versions OS: darwin 15.6.0 nodejs: v7.0.0 sitespeed.io: 4.0.0 browsertime: 1.0.0-beta.9 coach: 0.28.4
[2016-10-28 03:59:48] Starting firefox for analysing https://en.wikipedia.org/wiki/Main_Page 3 time(s)
[2016-10-28 03:59:48] Start tsproxy:/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/vendor/tsproxy.py --rtt 28 --inkbps 5000 --outkbps 1000 -p 1080
[2016-10-28 03:59:48] Testing url https://en.wikipedia.org/wiki/Main_Page run 1
[2016-10-28 04:00:03] Testing url https://en.wikipedia.org/wiki/Main_Page run 2
[2016-10-28 04:00:20] Testing url https://en.wikipedia.org/wiki/Main_Page run 3
[2016-10-28 04:00:35] 30 requests, 315.68 kb, DOMContentLoaded: 2.68s (±0.), Load: 5.64s (±0.29), rumSpeedIndex: 2.26s (±0.12) (3 runs)
[2016-10-28 04:00:36] Starting firefox for analysing https://en.wikipedia.org/wiki/Barack_Obama 3 time(s)
[2016-10-28 04:00:36] Start tsproxy:/Users/myuser/.npm_global/lib/node_modules/sitespeed.io/node_modules/browsertime/vendor/tsproxy.py --rtt 28 --inkbps 5000 --outkbps 1000 -p 1080
[2016-10-28 04:00:36] Testing url https://en.wikipedia.org/wiki/Barack_Obama run 1
[2016-10-28 04:01:02] Testing url https://en.wikipedia.org/wiki/Barack_Obama run 2
[2016-10-28 04:01:30] Testing url https://en.wikipedia.org/wiki/Barack_Obama run 3
[2016-10-28 04:01:56] 117 requests, 1181.24 kb, DOMContentLoaded: 4.45s (±0.35), Load: 14.s (±0.54), rumSpeedIndex: 4.12s (±0.21) (3 runs)
[2016-10-28 04:01:57] Render HTML for 2 page(s)
[2016-10-28 04:02:00] HTML stored in /Users/myuser/sitespeed-result/en.wikipedia.org/2016-10-28-03-59-47
[2016-10-28 04:02:00] Finished analysing https://en.wikipedia.org/wiki/Main_Pagemyuser
```
Might be an Chrome issue? Best regards r.

**Comment by soulgalore** [comment] 2016-10-28 08:58
Hey @rpkoller this a Chrome bug, @tobli do you have the reference? I think it's fixed but I don't know when it will be release. 

I know Tobias also had this when he had his OS configured to Swedish. The problem is that depending on language  the value for codes switch between using dots or commas in the timestamp: "timestamp":61762,941255


Best
Peter

**Comment by tobli** [comment] 2016-10-28 09:10
It's https://bugs.chromium.org/p/v8/issues/detail?id=5551. The fix was just merged to V8 stable, to be a part of Chrome 55 (coming around Dec 6th). It's already in Chrome Canary. So either use that, or switch locale. Not ideal, but works.

**Comment by rpkoller** [comment] 2016-10-28 10:28
ahhh thanks for the headsup @soulgalore and @tobli ! switching characters in the timestamps based on the used language is a tricky one. ;) oh and one word of advice; maybe change the example on sitespeed.io from chrome to firefox and leave also a remark on the examples page as well as in the documentation that users are warned beforehand not to use chrome at the moment. that might save you from quite a few more bug reports i suppose ;)

**Comment by soulgalore** [comment] 2016-10-28 11:05
l see your point changing the docs @rpkoller however the sad truth is that Firefox been unstable since the move to Geckodriver or rather each new release could break for us to use it, lets see.

**Comment by rpkoller** [comment] 2016-10-28 13:56
uhhhh i see @soulgalore . that's a valid point. but theoretically speaking so there might be times until the 6th of december during which none of the two possible output options in sitespeed.io, chrome as well as firefox, won't work at all?

**Comment by tobli** [comment] 2016-10-28 14:00
Chrome works, with the caveat that you might need to change the locale. In Docker containers we can control more of the environment (locale, what browser versions to include, etc.), so those are more resilient to such factors. Additionally we can prepackage dependencies that can be complex to manage yourself, such as VisualMetrics. I'd recommend you give it a try! We think it's a great default option for a lot of users.

**Comment by rpkoller** [comment] 2016-10-28 14:08
@tobli ahhhh cool! i will check that on the weekend when i have a bit of time. haven't jumped on the docker train yet. but looks like a good reason to finally give that a try. ;) thanks for the headsup!

**Comment by tobli** [comment] 2016-12-03 22:13
This is now resolved in Chrome 55.

**Closed by tobli** 2016-12-03 22:13 UTC
Labels: bug, Chrome, upstream
