### ISSUE TITLE
Hardware requirement for sitespeed.io to test multiple sites !

### ISSUE THREAD

**Issue by gugansankar** [sitespeedio/sitespeed.io#809] opened 2016-01-21 08:38 UTC
Hi,

What is the hardware requirement for sitespeed to run the test on multiple sites ?.

I have a bunch of sites hosted on my server. Just I need to run the test on all the sites to check the result. But when I run the script on cron, Server is getting overloaded In terms of CPU , Memory and Load. Sometime Server got hanged. So I rebooted manually.

My Server Details:
Centos6.7
CPU - 2
RAM - 8GB

My Cron Entry :  [ For testing I set it to 5 sec interval ]. 
*/5 * * * * /usr/bin/docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://dev1.infodesk.com -d 0 -n 5 --connection cable -r /tmp/ --graphiteHost 10.11.12.202 --graphiteNamespace sitespeed.io --graphiteData summary,rules,pagemetrics,timings,requests --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1
*/5 * * * * /usr/bin/docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://dev2.infodesk.com  -d 0 -n 5 --connection cable -r /tmp/ --graphiteHost 10.11.12.202 --graphiteNamespace sitespeed.io --graphiteData summary,rules,pagemetrics,timings,requests --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1
*/5 * * * * /usr/bin/docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://testing1.infodesk.com  -d 0 -n 5 --connection cable -r /tmp/ --graphiteHost 10.11.12.202 --graphiteNamespace sitespeed.io --graphiteData summary,rules,pagemetrics,timings,requests --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1
*/5 * * * * /usr/bin/docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://testing2.infodesk.com  -d 0 -n 5 --connection cable -r /tmp/ --graphiteHost 10.11.12.202 --graphiteNamespace sitespeed.io --graphiteData summary,rules,pagemetrics,timings,requests --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1
*/5 * * * * /usr/bin/docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://testing3.infodesk.com/   -d 0 -n 5 --connection cable -r /tmp/ --graphiteHost 10.11.12.202 --graphiteNamespace sitespeed.io --graphiteData summary,rules,pagemetrics,timings,requests --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1
*/5 * * * * /usr/bin/docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u https://prod1.infodesk.com  -d 0 -n 5 --connection cable -r /tmp/ --graphiteHost 10.11.12.202 --graphiteNamespace sitespeed.io --graphiteData summary,rules,pagemetrics,timings,requests --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1
*/5 * * * * /usr/bin/docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://prod2.infodesk.com/  -d 0 -n 5 --connection cable -r /tmp/ --graphiteHost 10.11.12.202 --graphiteNamespace sitespeed.io --graphiteData summary,rules,pagemetrics,timings,requests --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1
*/5 * * * * /usr/bin/docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://prod3.infodesk.com/  -d 0 -n 5 --connection cable -r /tmp/ --graphiteHost 10.11.12.202 --graphiteNamespace sitespeed.io --graphiteData summary,rules,pagemetrics,timings,requests --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1

You may noticed. Here I set depth is to 0. So Server got overloaded even for depth 0. What will happen if I remove that depth entry there [ Hope, if depth is not specified , then entire site page will be crawled ]

**Comment by soulgalore** [comment] 2016-01-21 22:28
Hey @gugansankar ,
so not really sure I understand what you want to accomplish with your tests? I think testing every 5 seconds is way to often :) I usually test a site every 5 minutes, 10 or once an hour depending on how often the content are changed. It's better to test once an hour and then make 3-5 runs to make sure you get stable values. That way you can collect stats and it will hopefully will be able to test regression. 

Your testing on testing/stage etc can be triggered on build/commit instead, so you more easy can compare before and after a change?

I run only one test at a time on a server to make sure it nothing else will interfere with collecting the metrics. 

For the example dashboard, I use a instance on Digital Ocean that have 1 GB Memory and one  CoreProcessor. More memory could be better because browsers nowadays usually ends up using a lot.

Hope that helps you 
Best
Peter

**Comment by beenanner** [comment] 2016-01-22 03:24
I agree with @soulgalore 5 seconds is too often as your example shows you are testing 5 times for each URL. Each test of each URL would need to finish in under a second for all 5 tests to finish in the 5 seconds before the next iteration of testing starts. 

The machine specs seems OK to me as I run something similar. I agree and think you should look at increasing your testing interval to at least the 5 minutes @soulgalore suggests and monitoring the system using the "top" command while the cron jobs are running. 

To answer your question about the depth setting if you remove the -d 0 it will default to testing all links on the page as well at the page itself. This would make each test take longer based on the number of links found on the page passed to the "u" option. On most of my setups I usually test 5-10 times every 15 minutes with a depth of 0 and that gives me enough detail to catch any regressions.

**Comment by gugansankar** [comment] 2016-01-22 05:40
@soulgalore @beenanner  Thanks for your Kind reply and this wonderful project.

The time interval I set it for my testing. But when I move it to production I will change it two 1 hours once.

Even If I set one hour once, what happen all the crond entries trigger at the same time. In my test , I found server  resource seems normal When I run 5 simultaneous/concurrent check. But When the check counts increase server Load , CPU everything got peaked out. 


@beenanner , How many sites will you run simultaneously on your setup ?.  If possible, could you please share your cron entry ?.

**Comment by beenanner** [comment] 2016-01-23 04:55
@gugansankar I only run 3 or 4 at a time. Could you group them all in a file and pass it using the -f options? You could even use the --sites option to group dev, testing, prod into their own file groups. That would allow them to run serially as well as group them so you are not running all of them in parallel.

**Comment by gugansankar** [comment] 2016-01-23 07:51
Hi  , Thanks for your reply.

yes, I tried with options "-f, -u, --sites" to parse group of sites. If I used this option, Unable to see the logs in Graphite for appropriate sites. It just show only combined summary report.  Also in Graphite, only  has a summary record of top/first site in the group file. 

![sitespeed1](https://cloud.githubusercontent.com/assets/4958813/12529132/b19bda42-c1d3-11e5-8aa4-86d7549d5bf0.png)

For above example,

In Graphite, I have summary record of www.google.com only not for remaining sites.

**Comment by beenanner** [comment] 2016-01-23 20:53
@gugansankar the other option is if you know about how long your tests will take you could modify your cronjobs to run in spaced out intervals to avoid maxing out your hardware and still running a few of them in parallel. I would first reduce the # of tests and monitor the box to see how many you can run in parallel. From there you could modify the cron jobs based on how long each test's run time. I would give your set of URLs at least a 5 minute window between one set of cron tasks and the next set to make sure all the tests finish before the new set of crons starts up. My best guess would be that you could run all you dev URLs in parallel then testing URLs and finally prod URLs. It would look something like this

```
#every hour (ex: 12:01, 12:15, 12:30, 12:45)
1,15,30,45 * * * * cron task dev1
1,15,30,45 * * * * cron task dev2
 
#every hour (ex: 12:05, 12:20, 12:35, 12:50)
5,20,35,50 * * * * cron task testing1
... etc.

```

**Comment by gugansankar** [comment] 2016-01-25 08:19
Yes, I already changed my cron entry based on the server load and distribute the jobs on different time interval.  From my local testing, I observed that normally sitespeed.io [ singe process] takes up to 16% of CPU. At the same time, I would accept , its a reasonable resource conception. But Is there any way to handle/reduce resource conception ?.

Apart from the Hardware issue, I mentioned already in my last reply. sitespeed.io option parameters like -f, -u, --sites doesn't suite for analyzing data through Graphite.  As these options is used to parse group of entry in file. But In a output, its show combined summary report of all the entries. Also its hard to analyze the data though graphite if we send these data to it.  Do you have any chance to keep separate summary page for each site ? .

Please correct me If I understand the concept wrongly. Once Again Thank you so much for your kind replies.

**Comment by soulgalore** [comment] 2016-01-25 10:13
Hi @gugansankar 
for getting different summary per site, you can use the <code>--sites</code> directive, there's a example here, see if it helps: https://www.sitespeed.io/documentation/configuration/#analyze-sites-and-benchmark

> But Is there any way to handle/reduce resource conception
not built in.

Best
Peter

**Comment by gugansankar** [comment] 2016-01-25 10:34
Already I mentioned in my last reply that options like **-f,-u , --sites** are not working for getting different summary per site. Even I tested **--sites** directive now. But no luck. it shows the combined report.

In the below report, you could see  the graphite shows report for "www.google.com". 

![sitespeed10](https://cloud.githubusercontent.com/assets/4958813/12548533/028b8dd0-c37d-11e5-8086-1f9516faa938.png)
![sitespeed11](https://cloud.githubusercontent.com/assets/4958813/12548534/0291ba02-c37d-11e5-9443-34c7f7a94e56.png)

**Comment by soulgalore** [comment] 2016-01-25 10:39
Yes but you need to have one file per domain, so that you use --sites 4 times, one per file/domain. Then you will have it (as in https://www.sitespeed.io/documentation/configuration/#analyze-sites-and-benchmark).

**Comment by gugansankar** [comment] 2016-01-25 10:49
:+1:

**Comment by soulgalore** [comment] 2016-10-28 09:44
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Closed by soulgalore** 2016-10-28 09:44 UTC
