### ISSUE TITLE
Core.xxxxx files are getting generated will running sitespeed.io

### ISSUE THREAD

**Issue by senthilr2k** [sitespeedio/sitespeed.io#1921] opened 2018-02-26 09:22 UTC
Hi ,
Core.xxxxx files are getting generated will running sitespeed.io in docker. These files are of huge size.

Thanks,
Senthil R

**Comment by soulgalore** [comment] 2018-02-26 20:30
Hi @senthilr2k thanks for reporting, can you help me out some more, how do you get them and where and what are those? What OS are you using etc. How do I do to reproduce the issue?

Thanks!
Peter

**Comment by soulgalore** [comment] 2018-06-15 19:27
Closing this since we didn't get any feedback.

**Closed by soulgalore** 2018-06-15 19:27 UTC
