### ISSUE TITLE
Options not getting recognised.

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#585] opened 2015-02-19 20:17 UTC
Whenever i tried to run my test environment url with options like -b,-d etc.. following message is displayed 

[1] 50272
-sh: -d: command not found

Any help is appreciated . 

![screen shot 2015-02-19 at 12 16 41 pm](https://cloud.githubusercontent.com/assets/1479179/6275072/3a78c986-b831-11e4-9006-f1ff03b036bd.png)

**Comment by soulgalore** [comment] 2015-02-19 20:25
Hi @badrinathvm ,
the problem is the URL, the & and bash doesn't work (it will think you want to run another command) try add the URL like this "http://thefulurl"

Best
Peter

**Comment by badrinathvm** [comment] 2015-02-19 20:29
If i use the format like the way u mentioned , it works , but i want to test performance of t particular page , mentioned below

http://www1.macys.com/shop/product/mac-lipstick-0.1-oz?ID=106363&CategoryID=30077#fn=sp%3D1%26spc%3D2%26kws%3D106363%26slotId%3D1

How can i accomplish this ?

**Comment by badrinathvm** [comment] 2015-02-19 20:39
Found a way to test . included the URL till http://www1.macys.com/shop/product/mac-lipstick-0.1-oz?ID=106363 , it works .. Thanks for pointing out mistake.

**Comment by soulgalore** [comment] 2015-02-19 21:16
great, closing the issue

**Closed by soulgalore** 2015-02-19 21:16 UTC
