### ISSUE TITLE
ERROR: VisualMetrics failed to run Error: Command failed with exit code 1: python

### ISSUE THREAD

**Issue by shasaks** [sitespeedio/sitespeed.io#3600] opened 2022-03-16 12:49 UTC
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.chegg.com/books

### What are you trying to accomplish

Running browser performance test for the multiple pages (15-20)

### What browser did you use?

Chrome

### How to reproduce

```shell
Add multiple page in the scripts. 

module.exports = async function(context, commands) {
  await commands.measure.start('https://www.chegg.com/books', 'home page');
  await commands.measure.start('https://www.chegg.com/books/study/qa', 'books page');
  await commands.measure.start('https://www.chegg.com/books/books', 'books page2');
};

Note: added 15 more pages in the above script.
```

### Relevant log output

```shell
[2022-03-16 10:51:04] INFO: Take largest contentful paint screenshot
[2022-03-16 10:51:07] INFO: Get visual metrics from the video
[2022-03-16 10:51:11] INFO: Get visual metrics from the video
[2022-03-16 10:51:12] INFO: Get visual metrics from the video
[2022-03-16 10:51:15] INFO: Get visual metrics from the video
[2022-03-16 10:51:17] INFO: Get visual metrics from the video
[2022-03-16 10:51:19] INFO: Get visual metrics from the video
[2022-03-16 10:51:21] INFO: Get visual metrics from the video
[2022-03-16 10:51:23] INFO: Get visual metrics from the video
[2022-03-16 10:51:25] INFO: Get visual metrics from the video
[2022-03-16 10:51:28] INFO: Get visual metrics from the video
[2022-03-16 10:51:30] INFO: Get visual metrics from the video
[2022-03-16 10:51:32] INFO: Get visual metrics from the video
[2022-03-16 10:51:34] INFO: Get visual metrics from the video
[2022-03-16 10:51:36] INFO: Get visual metrics from the video
[2022-03-16 10:51:39] INFO: Get visual metrics from the video
[2022-03-16 10:51:41] INFO: Get visual metrics from the video
[2022-03-16 10:51:43] INFO: Get visual metrics from the video
[2022-03-16 10:51:45] INFO: Get visual metrics from the video
[2022-03-16 10:51:46] ERROR: VisualMetrics failed to run Error: Command failed with exit code 1: python /root/.npm/_npx/aa19780b5aa25e1f/node_modules/sitespeed.io/node_modules/browsertime/browsertime/visualmetrics.py --dir /builds/chegginc/learning-services/uta/uta-gitab-playground/web-performance/sitespeed-results/pages/rc_live_test_cheggnet_com/books-page15/data/filmstrip/1 --video /builds/chegginc/learning-services/uta/uta-gitab-playground/web-performance/sitespeed-results/pages/rc_live_test_cheggnet_com/books-page15/data/video/1.mp4 --orange --force --renderignore 5 --json --viewport -q 75 --logfile /builds/chegginc/learning-services/uta/uta-gitab-playground/web-performance/sitespeed-results/pages/rc_live_test_cheggnet_com/books-page15/data/video/1.visualmetrics.log -vvv
ffmpeg version 5.0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/builds/chegginc/learning-services/uta/uta-gitab-playground/web-performance/sitespeed-results/pages/rc_live_test_cheggnet_com/books-page15/data/video/1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.16.100
  Duration: 00:00:04.33, start: 0.000000, bitrate: 312 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1366x708, 309 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/builds/chegginc/learning-services/uta/uta-gitab-playground/web-performance/sitespeed-results/pages/rc_live_test_cheggnet_com/books-page15/data/filmstrip/1/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.16.100
  Stream #0:0(und): Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1366x708, q=2-31, 200 kb/s, 30 fps, 30 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.18.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.474x    
video:575kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ffmpeg version 5.0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/builds/chegginc/learning-services/uta/uta-gitab-playground/web-performance/sitespeed-results/pages/rc_live_test_cheggnet_com/books-page15/data/video/1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.16.100
  Duration: 00:00:04.33, start: 0.000000, bitrate: 312 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1366x708, 309 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/builds/chegginc/learning-services/uta/uta-gitab-playground/web-performance/sitespeed-results/pages/rc_live_test_cheggnet_com/books-page15/data/filmstrip/1/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.16.100
  Stream #0:0(und): Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1366x708, q=2-31, 200 kb/s, 30 fps, 30 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.18.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.06 bitrate=N/A speed=0.928x    
video:579kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ffmpeg version 5.0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
```

**Comment by shasaks** [comment] 2022-03-16 16:58
@soulgalore Yes, if I use only 4-5 pages then it's working fine.

**Comment by soulgalore** [comment] 2022-03-17 08:13
Thanks for sharing the videos! I tried manually with the one that do not get any visual metrics and it worked, so that is strange. You don't get a error message in your log that starts with "Log from VisualMetrics"? If visual metrics fails, it should read the specific visual metrics log and log it to the standard log, but it seems to be case where it do not work.

In your output folder, do the visual metric log exist for that failed page, something like `books-pageX/data/video/1.visualmetrics.log ` - I need to see what happens there to understand what's going on.

**Comment by shasaks** [comment] 2022-03-24 12:24
@soulgalore No visual metric log exists in the output folder.

**Comment by soulgalore** [comment] 2023-12-29 06:01
I was never able to reproduce so closing. Please re-open if this is still an issue.

**Closed by soulgalore** 2023-12-29 06:01 UTC
Labels: bug
