### ISSUE TITLE
Git Required for Docker build

### ISSUE THREAD

**Issue by rsiddle** [sitespeedio/sitespeed.io#1960] opened 2018-03-24 19:27 UTC
Using the current master branch, running the following command:

```
docker build -t sitespeedio/sitespeedio .
```

Created this error:

```
...
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
```

I fixed it by adding the following line to [Dockerfile at line 10](https://github.com/sitespeedio/sitespeed.io/blob/master/Dockerfile#L10)

```
RUN sudo apt-get install git -y
```

**Comment by soulgalore** [comment] 2018-03-28 08:18
@rsiddle could see what caused this? I cannot reproduce.
Best
Peter

**Comment by soulgalore** [comment] 2019-01-26 19:43
This works on all environments I've tested so closing, but please let us know and explain if you still get this message.

**Closed by soulgalore** 2019-01-26 19:43 UTC
Labels: need more info
