### ISSUE TITLE
WebP not supported... FAIL to load undefined

### ISSUE THREAD

**Issue by paazmaya** [sitespeedio/sitespeed.io#241] opened 2013-08-05 12:40 UTC
Every time the script comes across webp file, `Could not analyze http://....webp unrecoverable error when parsing the page:`, which is followed by different number of `FAIL to load undefined`.

Could the latter part be more clear about what is the actual problem?

**Comment by tobli** [comment] 2015-02-04 15:34
Is this still valid? I could only guess how to reproduce, based on the initial report. However I tried running "sitespeed.io -u http://paazmaya.com -d 4" with 3.1.1, and didn't see any issues related to webp.

**Comment by paazmaya** [comment] 2015-02-04 15:38
I seem to have dropped `webp` since...

I could come up with a way to test this soon...ish

**Comment by paazmaya** [comment] 2015-02-04 15:41
Well here it is, http://paazmaya.com/page=5

```sh
sitespeed.io -u http://paazmaya.com/page=5 -d 4
```

That page has `webp` images shown when Chrome is used

**Comment by tobli** [comment] 2015-02-04 22:18
Hmm, I'm not seeing any analysis errors when running that command. Additionally, with the "FAIL to load ..." coming from YSlow in PhantomJS, adding -b chrome has no effect on that stage. It only instructs sitespeed to run Browsertime in Chrome after the YSlow analysis.

@paazmaya - what version of sitespeed.io are you running, also on what platform (including what version of node.js). It would be very helpful if you could share the logs from the run where you're seeing this error.
Thanks!

**Comment by paazmaya** [comment] 2015-02-05 08:05
It was the repository version in 5 Aug 2013.
Yesterday I could not get the Internet connection working with running that command...

Perhaps this has been fixed elsewhere

**Comment by tobli** [comment] 2015-02-15 10:34
Closing this since it's not reproducible anymore.

**Closed by tobli** 2015-02-15 10:34 UTC
Labels: bug
