### ISSUE TITLE
Scripting: commands.switch.toWindow() not working

### ISSUE THREAD

**Issue by nevesing** [sitespeedio/sitespeed.io#2537] opened 2019-07-08 21:33 UTC
**Env: Ubuntu/Docker/Sitespeedio:9.5.0**

I am trying to prepare test script for an application where it opens another window  (firefox/chrome) to enter user name/pwd. I am using commands.switch.toWindow(name) but I am getting this error:

Command:   await commands.switch.toWindow('Sign In');

**Error:**

```
[2019-07-08 17:20:48] ERROR: Could not switch to frame with name Sign In 
[2019-07-08 17:20:48] ERROR: Error: Could not switch to frame with name  Sign In
    at Switch.toWindow (/usr/src/app/node_modules/browsertime/lib/core/engine/command/switch.js:36:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by soulgalore** [comment] 2019-07-09 08:00
Hi @nevesing here are some docs on how you can debug your scripts:
https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug

Best
Peter

**Comment by soulgalore** [comment] 2019-10-09 21:22
Was the name you passed on `window.name` ?

Closing this since the issue is old.

**Closed by soulgalore** 2019-10-09 21:22 UTC
