### ISSUE TITLE
Metrics are incorrect

### ISSUE THREAD

**Issue by jonyt** [sitespeedio/sitespeed.io#3115] opened 2020-08-06 08:33 UTC
When I look at the results of a run for a single page the metrics are incorrect. For example total transfer size is listed as 30.8kb but when I look at Chrome dev tools it's 2.4M, sitespeed says 5 requests, Chrome says 34. I also see the JS/CSS/images transfer size listed as 0 bytes. I'm assuming I missed something in configuring sitespeed but any idea on what it could be?

Here's the command I run `docker run --network=cable  --rm -v "/home/ec2-user/":/sitespeed.io sitespeedio/sitespeed.io:13.3.2 sitespeed.js --multi --browsertime.iterations=7 --preScript pre.sitespeed.js --logToFile true --graphite.host 3528dc5773de`. This is with the latest docker-compose.yml and no changes to the configuration I cloned from the repo.

**Comment by soulgalore** [comment] 2020-08-06 20:55
Hi @jonyt can you help me how I should do to reproduce it, see https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue ?

**Comment by jonyt** [comment] 2020-08-10 14:36
It's an internal site, so impossible to reproduce by someone not from my company. But I'm attaching my script (below), log and an example video (attached) from a run. The script is running on Amazon Linux 2 with the latest sitespeed docker-compose.yml and the sitespeed Docker image is sitespeedio/sitespeed.io:13.3.2. As I said I'm almost certain it's a configuration issue because I ran the same configuration on [this](https://www.theguardian.com/environment/2020/mar/12/david-attenborough-calls-for-ban-on-devastating-deep-sea-mining) and the results looked reasonable.

On the other hand for the page I'm testing I get 31.4kb transfer size from sitespeed but 5.8Mb from Chrome. Could it be that sitespeed is stopping too early? Is there a way for me to configure when the test is stopped myself?

```
module.exports = async function(context, commands) {
  await commands.measure.start('Helpdesk');                                                                                                                                                                                      await commands.navigate(`https://subd.mycompany.com/HelpDesk.jsp`);
  return commands.measure.stop();  
};
```

![1](https://user-images.githubusercontent.com/1472873/89794436-b7187280-db2f-11ea-96b8-9fb77723d383.gif)

[sitespeed.io.log](https://github.com/sitespeedio/sitespeed.io/files/5051426/sitespeed.io.log)

**Comment by soulgalore** [comment] 2021-04-13 01:22
Sorry I missed getting back. Yep stopping to early is probably the problem. Checkout https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test

**Comment by soulgalore** [comment] 2021-04-15 14:34
Closing since I think when to stop is the key here.

**Closed by soulgalore** 2021-04-15 14:34 UTC
