### ISSUE TITLE
GPSI Module Errors

### ISSUE THREAD

**Issue by gregorywolf** [sitespeedio/sitespeed.io#3531] opened 2022-01-14 10:21 UTC
Hi - I am getting the following error on a regular basis. The error has occurred with both 21.3.0-plus1 and 21.4.0. My testing consists of either 5 or 7 URLs at a time. I have reviewed https://github.com/sitespeedio/plugin-gpsi/issues/7 and it seems that the issue is that there were too many URLs for a given run, which is not my issue. I am storing the data in Graphite on a separate machine. The one issue that might factor in is the my sitespeed machine may be a little under powered (2vCPU and 4GB mem). Not sure.

`ERROR: Error: Lighthouse returned error: Something went wrong.
    at Gaxios.<anonymous> (/gpsi/node_modules/gaxios/build/src/gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/gpsi/node_modules/gaxios/build/src/gaxios.js:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by soulgalore** [comment] 2022-01-15 13:41
Hi @gregorywolf that error comes directly from Google Page Speed Insights (GPSI). The "Lighthouse returned error" is an error directly from them, see for example https://stackoverflow.com/questions/55826735/how-to-fix-lighthouse-returned-error-no-fcp-when-running-google-page-speed-t

The machine size will not matter for this error, the GPSI runs Lighthouse on Google servers. Can you reproduce it all the time, like if it is a specific URL, then you could try report it at https://groups.google.com/g/pagespeed-insights-discuss or if they have a better way to report it.

**Comment by soulgalore** [comment] 2022-02-12 14:16
Closing since its a Lighthouse/GPSI issue.

**Closed by soulgalore** 2022-02-12 14:16 UTC
