### ISSUE TITLE
clear "from memory cache" and "from disk cache" after prescript

### ISSUE THREAD

**Issue by Nuoky** [sitespeedio/sitespeed.io#2193] opened 2018-10-25 08:29 UTC
Hi @soulgalore 

Is it possible to add a switch to clear the "from memory cache" and "from disk cache" caches after executing prescript? 

Because most of the spa resources will be loaded and cached on the login page and the home page that automatically jumps after login.

This will not simulate a user entering the test page directly when they are logged in.

Thanks!

**Comment by soulgalore** [comment] 2018-10-25 08:46
Hi @Nuoky do you use Chrome? I've seen people try to running without a cache, checkout for example https://github.com/sitespeedio/sitespeed.io/issues/1707 - could that help you (I haven't tried it myself).

Best
Peter

**Comment by soulgalore** [comment] 2018-10-25 21:53
Hi @Nuoky also seen people tried with:
`--browsertime.chrome.args disk-cache-dir=/dev/null`

At the moment we clear the following caches: https://github.com/sitespeedio/browsertime-extension/blob/master/background.js#L184-L198  but that happens before preScript.

About the tab, I'm not sure exactly what you mean, can you show me some more?

Best
Peter

**Comment by Nuoky** [comment] 2018-11-08 08:09
Hi @soulgalore 

Sorry for replying so long.

It has now been confirmed that the problem is not caused by caching.

In the past version of bt (2.5.0) use driver.get (url) to open the test page, and after the 3.xx version use window.location to open the test page, using driver.get (url) is similar to browsing The new tab of the device opens the url. Using window.location runs the page within the current tab.

So my reply to the previous one means: The generated HAR is different from the previous bt version (2.5.0). Is there a way to open the url in the browser's new tab page?

Thanks!

**Comment by soulgalore** [comment] 2018-11-08 08:12
Ah ok, I think I understand. So you want it to work like this:
1. You run the pre-script (login etc)
2. Open a new tab and access the URL you want to measure there?

Best
Peter

**Comment by soulgalore** [comment] 2019-01-26 19:55
At the moment there is no way of clearing the cache between URLs (in scripting).

**Comment by mackelito** [comment] 2019-11-06 12:34
What other way of testing pages behind a login do we have?

we have a login dialog that shows and once closed the site (uses angular) loads.. The problem is that all assets are loaded when user get's the login dialog, so we need to clear the cache to get proper data..

Any help is much appreciated :)

**Comment by soulgalore** [comment] 2019-11-06 12:39
HI @mackelito I think I've missed closing this issue, this is doable now. If you use scripting have a look at https://www.sitespeed.io/documentation/sitespeed.io/scripting/#cache. You can either clear the full cache (assets/cookies etc) or just clear the cache and keep cookies.
So the script should be like this:
- navigate to the page
- login the user
- clear the browser cache (keep cookies if you use them to keep the user logged in)
- measure the next page

Is that what you need?
Best
Peter

**Comment by mackelito** [comment] 2019-11-06 13:03
That is what I'm trying to do but it's not working :(
My guess is that the service worker cache is not cleared

````
module.exports = async function(context, commands) {
  await commands.navigate(
    'https://www.mysite.com/'
  );

  try {
    await commands.wait.byXpath('//*[@id="dialog-0"]/authentication-dialog',3000);

    // Enter login credentials 
    await commands.addText.byId(context.options.user, 'email');
    await commands.addText.byId(context.options.password, 'password');

    // Click on the submit button with id login
    await commands.click.byIdAndWait('login');
    
    // Clear the cache
    await commands.cache.clear();

    // Wait for element to show
    return commands.wait.byId('startpage_section_1',3000);

  } catch (e) {
    // We try/catch so we will catch if the the input fields can't be found
    // The error is automatically logged in Browsertime and re-thrown here
    // We could have an alternative flow ...
    // else we can just let it cascade since it catched later on and reported in
    // the HTML
    throw e;
  }
};
````

But the result is that not all assets are showing in the result...

**Comment by soulgalore** [comment] 2019-11-06 13:11
Ah ok, I need check our implementation. For Chrome we send `Network.clearBrowserCache` using the Chrome devtools protocol. Maybe something else is needed for the service worker. Can you check at https://chromedevtools.github.io/devtools-protocol if you can find something? Then you could use that directly with https://www.sitespeed.io/documentation/sitespeed.io/scripting/#chrome-devtools-protocol 

And then I can update or add another method later on?

Best
Peter

**Comment by mackelito** [comment] 2019-11-06 13:14
Another "issue" is the iterations.. we set `--browsertime.iterations=3` and this is the result:
1-3 looks as expected.. 4-6 are "broken"..

![Kapture 2019-11-06 at 14 09 04](https://user-images.githubusercontent.com/598463/68300899-04e2e480-009f-11ea-86d0-031eae5a6569.gif)

**Comment by soulgalore** [comment] 2019-11-06 13:17
Please create a new issue for that :)

**Comment by mackelito** [comment] 2019-11-06 13:20
@soulgalore will do.. suggested topic? quite new to sitespeed so not sure how to categories this bug :)

**Comment by soulgalore** [comment] 2019-11-06 13:47
Great, just create the bug and try to make reproducible see https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue 

Best
Peter

**Comment by mackelito** [comment] 2019-11-06 21:49
Found some ppl that used selenium to clear the data...
````
  const driver = context.selenium.driver;

    // Opens a new tab
    driver.execute_script("window.open()")

    // Switch to the newly opened tab
    driver.switch_to.window(driver.window_handles[1])

    // Navigate to new URL in new tab
    driver.get("chrome://settings/clearBrowserData")

    // Click on the Clear data button
    driver.find_element_by_css_selector("* /deep/ #clearBrowsingDataConfirm").click()

    driver.implicitly_wait(60)

    // Switch to original tab
    driver.switch_to.window(self.driver.window_handles[0])
````

But I get `ERROR: [browsertime] TypeError: Cannot read property 'execute_script' of undefined`

**Comment by mackelito** [comment] 2019-11-06 22:26
Realised it was an older api.. but able to "convert" it to use the new api :P

**Comment by soulgalore** [comment] 2019-11-06 23:39
I'm thinking you could try to disable service workers before you load the URL https://chromedevtools.github.io/devtools-protocol/tot/ServiceWorker#method-disable ?

For Chrome we use the Chrome devtools protocol to clear the cache, For Firefox we use a browser extension, there it potentially could work to empty the cache for SW but we haven't implemented it see https://github.com/sitespeedio/browsertime-extension/blob/master/background.js#L180-L221

**Comment by mackelito** [comment] 2019-11-07 07:03
hmm.. we are running tests in chrome so the SW cache should be cleared if I understand you correctly? But looking at the test results I see that it's not.. so I'm missing something or doing something wrong :/

**Comment by soulgalore** [comment] 2019-11-07 07:05
No then I was unclear. We only use the CDP network call to clear the cache, we need to check with the Chrome team what it actually. I think you should try turn off the Service Worker before measure the page. The documentation at https://chromedevtools.github.io/devtools-protocol/tot/ServiceWorker#method-disable isn't so friendly though :)

**Comment by mackelito** [comment] 2019-11-07 09:07
For reference, I ended up doing this:

````
    await commands.cache.clear();
    await commands.cdp.send('ServiceWorker.enable');
    await commands.cdp.send('ServiceWorker.stopAllWorkers');
````

**Comment by soulgalore** [comment] 2019-11-07 13:29
Thank you @mackelito for sharing!

**Comment by mackelito** [comment] 2019-11-07 13:36
Hey.. we thank you for the awesome work you’ve done! If we ever meet then you have a 🍺 coming your way! 😁

**Comment by soulgalore** [comment] 2019-11-18 01:48
The original issue: there's a lot of work to making multiple tabs work and I don't see how that will happen.

**Closed by soulgalore** 2019-11-18 01:48 UTC
Labels: enhancement

**Comment by Nuoky** [comment] 2021-03-02 06:54
Sorry, it took so long to reply.
I have now solved the problem by the following method:

```
// clear disk cache and memory cache
await commands.cdp.send('Network.clearBrowserCache');
// In order to solve the problem in chrome, if you redirect to the same URL after logging in, it will not refresh normally
await driver.get('chrome://new-tab-page');
```
