### ISSUE TITLE
browsermobproxy fails with error: TypeError: Cannot read property 'repeatView' of undefined

### ISSUE THREAD

**Issue by Vandrix** [sitespeedio/sitespeed.io#596] opened 2015-02-24 20:52 UTC
I'm running into browsermobproxy errors lately.

I run with: 
xvfb-run --server-args="-screen 0 1920x1080x24" sitespeed.io -f filename -r domain -b chrome --viewPort 1920x1080 --screenshot --gpsiKey key --wptConfig jsonfile --wptHost private instance --wptKey apikey

browsermobproxy.log:

2015-02-24T20:00:03.942Z - info: [browsermobproxy] stdout:Unable to find conf/bmp-logging.properties. Using default logging configuration.
2015-02-24T20:00:03.944Z - info: [browsermobproxy] stdout:
2015-02-24T20:00:04.784Z - error: [browsermobproxy] stderr:INFO 02/24 20:00:04 n.l.b.p.Main         - Starting BrowserMob Proxy version 2.0.0
2015-02-24T20:00:04.853Z - error: [browsermobproxy] stderr:INFO 02/24 20:00:04 o.e.j.u.log          - jetty-2.0.0
2015-02-24T20:00:04.916Z - error: [browsermobproxy] stderr:INFO 02/24 20:00:04 o.e.j.u.log          - started o.e.j.s.ServletContextHandler{/,null}
2015-02-24T20:00:06.392Z - error: [browsermobproxy] stderr:INFO 02/24 20:00:06 o.e.j.u.log          - Started SelectChannelConnector@0.0.0.0:9092
2015-02-24T20:00:21.792Z - error: [browsermobproxy] stderr:INFO 02/24 20:00:21 n.l.b.p.j.h.HttpSer~ - Version Jetty/2.0.0
2015-02-24T20:00:21.795Z - error: [browsermobproxy] stderr:INFO 02/24 20:00:21 n.l.b.p.j.u.Contain~ - Started HttpContext[/,/]
2015-02-24T20:00:21.805Z - error: [browsermobproxy] stderr:INFO 02/24 20:00:21 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:9091
2015-02-24T20:00:21.806Z - error: [browsermobproxy] stderr:INFO 02/24 20:00:21 n.l.b.p.j.u.Contain~ - Started net.lightbody.bmp.proxy.jetty.jetty.`Server@347fd24a`
2015-02-24T20:00:42.459Z - error: [browsermobproxy] stderr:INFO 02/24 20:00:42 n.l.b.p.j.u.Threade~ - Stopping Acceptor ServerSocket[addr=/0.0.0.0,localport=9091]
2015-02-24T20:00:42.560Z - error: [browsermobproxy] stderr:INFO 02/24 20:00:42 n.l.b.p.j.h.SocketL~ - Stopped SocketListener on 0.0.0.0:9091
2015-02-24T20:00:42.695Z - error: [browsermobproxy] stderr:INFO 02/24 20:00:42 n.l.b.p.j.u.Contain~ - Stopped HttpContext[/,/]
INFO 02/24 20:00:42 n.l.b.p.j.u.Contain~ - Stopped net.lightbody.bmp.proxy.jetty.jetty.`Server@347fd24a`

2015-02-24T20:11:59.598Z - error: [browsermobproxy] TypeError: Cannot read property 'repeatView' of undefined
    at /usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:174:48
    at Array.forEach (native)
    at collectWPT (/usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:161:28)
    at Object.exports.processPage (/usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:34:5)
    at /usr/local/lib/node_modules/sitespeed.io/lib/collector.js:126:7
    at Array.forEach (native)
    at Collector.collectPageData (/usr/local/lib/node_modules/sitespeed.io/lib/collector.js:125:19)
    at processAnalysisResults (/usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:134:17)
    at /usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:69:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17

sitespeed.io.log:

2015-02-24T20:00:03.542Z - info: [sitespeed] OS: 'linux 3.13.0-43-generic', Node.js: 'v0.12.0', sitespeed: '3.1.2', phantomJs: '1.9.8', java: '1.7.0_75', browsertime: '0.8.21'
2015-02-24T20:00:03.544Z - info: [sitespeed] Analyze 4 sites
2015-02-24T20:00:03.668Z - info: [sitespeed] Will analyze 1 pages
2015-02-24T20:00:06.396Z - info: [sitespeed] Running YSlow for http://private.tld [phantomjs]
2015-02-24T20:00:13.191Z - info: [sitespeed] Running Google Page Speed Insights for http://private.tld
2015-02-24T20:00:20.492Z - info: [sitespeed] Queueing browsertime for http://private.tld chrome
2015-02-24T20:00:20.494Z - info: [sitespeed] Running browsertime for chrome http://private.tld
2015-02-24T20:00:42.725Z - info: [sitespeed] Running WebPageTest http://private.tld  pollResults=10, timeout=3600, firstViewOnly=false, runs=3, private=true, aftRenderingTime=true, location=Local-WPTDriver:Chrome, connectivity=Cable, video=true, server=private
2015-02-24T20:11:55.218Z - info: [sitespeed] Taking screenshot for http://private.tld
2015-02-24T20:11:59.551Z - error: [sitespeed] Could not fetch data for aggregator: TTFBWPT: err: [TypeError: Cannot read property 'forEach' of undefined]

java -version 
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
`
JSON file:

{
  "server": "private",
  "location": "Local-WPTDriver:Chrome",
  "connectivity": "Cable",
  "timeout": "3600",
  "runs": "3",
  "firstViewOnly": "false"
}

**Comment by soulgalore** [comment] 2015-02-24 21:17
Hi @Vandrix ,
there's a fix for one of the problem "Could not fetch data for aggregator"  in 3.1.7, so upgrading to that will help at least. For the other problem, I need to check, can do that tomorrow (but please upgrade to 3.1.7 that could help!).

There's one thing that seems strange in the logs:
<pre>
2015-02-24T20:00:03.544Z - info: [sitespeed] Analyze 4 sites
2015-02-24T20:00:03.668Z - info: [sitespeed] Will analyze 1 pages
</pre>
You are sure the sitespeed.io log match the parameters you run? Then there's another bug.

Best
Peter

**Comment by Vandrix** [comment] 2015-02-24 22:22
I've updated sitespeed to version 3.1.7., so let's see if error still occurs. I'm running hourly by cron.

>There's one thing that seems strange in the logs

Sorry I've pasted the wrong arguments. I'm running sitespeed with master file for multiple sites like this:

xvfb-run --server-args="-screen 0 1920x1080x24" sitespeed.io --verbose --sites benchmark.master -r benchmark_domain_tld -b chrome --viewPort 1920x1080 --screenshot --gpsiKey private --wptConfig wpt.json --wptHost private --wptKey private--graphiteHost private graphitePort 2003 --graphiteNamespace sitespeed

Thnx for your help!
Regards,

**Comment by soulgalore** [comment] 2015-02-25 08:30
cool, get back to me if it doesn't work and I will start testing it.

Best
Peter

**Comment by Vandrix** [comment] 2015-02-25 20:18
I don't see any errors now, but sometimes the Sitespeed test suddenly hangs after running Browsertime. I'm running hourly tests by cron with flock, only 2 failed today. Checked all logs, no errors there.
When it happens I'm seeing couple of Chrome processes in processlist (ps faux / htop) doing nothing, just sitting there. After using strace on the process I'm seeing lots of time out messages.
Don't think this is related to issue above.

Using:
- ChromeDriver 2.14.313457
- chromium-browser 40.0.2214.111-0ubuntu0.14.04.1.1069 amd64

Regards,

**Comment by soulgalore** [comment] 2015-02-25 20:33
Hi @Vandrix, yes I know about the problem (we have it on the FAQ and https://github.com/tobli/browsertime/issues/70). What happens is that Chrome/Chromedriver fails, and right now we are not able to catch/recover. We have it reported to Selenium (we use it internally) and they have been able to reproduce. https://code.google.com/p/selenium/issues/detail?id=8261

However, the main problem for us is that when Chrome fails, we aren't able to recover. We are working on a fix (meaning skipping the Selenium NodeJS version, because handling errors could be easier/better). We will probably start testing the new solution early next week. I'll keep you updated.

Best
Peter

**Comment by Vandrix** [comment] 2015-02-25 20:40
Thnx!

**Comment by Vandrix** [comment] 2015-03-01 15:01
Hi @soulgalore,

I'm getting the same type of error on a specific site only. I'm running Sitespeed 3.1.8.

info: Taking screenshot for ....
error: Could not fetch data for aggregator: harTimeMetrics: err: [TypeError: Cannot read property 'entries' of undefined]
error: Catched an uncaught exception:TypeError: Cannot read property 'entries' of undefinedTypeError: Cannot read property 'entries' of undefined
    at /usr/local/lib/node_modules/sitespeed.io/lib/collectors/assetsByTiming.js:27:12
    at Array.forEach (native)
    at Object.exports.processPage (/usr/local/lib/node_modules/sitespeed.io/lib/collectors/assetsByTiming.js:26:11)
    at /usr/local/lib/node_modules/sitespeed.io/lib/collector.js:126:7
    at Array.forEach (native)
    at Collector.collectPageData (/usr/local/lib/node_modules/sitespeed.io/lib/collector.js:125:19)
    at processAnalysisResults (/usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:134:17)
    at /usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:69:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:157:25
info: Stopping proxy

When I go to the WPT test URL and Export HTTP Archive (.har) manually it's 0 kb. So I guess WPT is failing to generate HAR for some reason and Sitespeed fails on fetching HAR from WTP?

**Comment by soulgalore** [comment] 2015-03-02 13:53
Hi @Vandrix ,
hmm yes maybe. You can check that by go the your webpagetest instance. Do you genereate HTML output? then you will have a link on the specific page that links to WebPageTest, where you can check if the HAR there is ok. Let me know if you don't find and I can help.

Best
Peter

**Comment by soulgalore** [comment] 2015-03-02 13:56
Hi again @Vandrix ,
about **I don't see any errors now, but sometimes the Sitespeed test suddenly hangs a** 
upgrade to the latest sitespeed.io 3.1.10. We have upgraded Selenium that in best case fixes one of the hanging problems and added a timeout when fetching the URL:s from drivers/browsers that hopefully will solve it. We are running tests tonight but you can safely try it now if you want.

Best
Peter

**Comment by Vandrix** [comment] 2015-03-02 15:36
Hi @soulgalore 

>You can check that by go the your webpagetest instance. Do you genereate HTML output? then you will have a link on the specific page that links to WebPageTest, where you can check if the HAR there is ok.

I've checked but the HAR isn't there...

>When I go to the WPT test URL and Export HTTP Archive (.har) manually it's 0 kb.

Thnx!

**Comment by soulgalore** [comment] 2015-03-02 17:07
ok cool.

> I don't see any errors now, but sometimes the Sitespeed test suddenly hangs a

argh, tested new version and still see this happens, but still good to update to latest version.

**Comment by soulgalore** [comment] 2015-03-06 07:33
Hi again @Vandrix ,
about the hanging problem: been testing the new version now, yep the problem is still there using Chrome, trying to debug and we can at least see where and how, need to check with the Selenium team to see what they can do.

However using Firefox works good for me, haven't seen any issues there. Can you try using it? 

Best
Peter

**Comment by Vandrix** [comment] 2015-03-06 12:04
Hi @soulgalore 

HAR problem is also with specific site in other browsers (IE and Firefox) getting the same error message:

error: Could not fetch data for aggregator: harTimeMetrics: err: [TypeError: Cannot read property 'entries' of undefined]
error: Catched an uncaught exception:TypeError: Cannot read property 'entries' of undefinedTypeError: Cannot read property 'entries' of undefined
    at /usr/local/lib/node_modules/sitespeed.io/lib/collectors/assetsByTiming.js:27:12
    at Array.forEach (native)
    at Object.exports.processPage (/usr/local/lib/node_modules/sitespeed.io/lib/collectors/assetsByTiming.js:26:11)
    at /usr/local/lib/node_modules/sitespeed.io/lib/collector.js:126:7
    at Array.forEach (native)
    at Collector.collectPageData (/usr/local/lib/node_modules/sitespeed.io/lib/collector.js:125:19)
    at processAnalysisResults (/usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:134:17)
    at /usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:69:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:157:25
info: Stopping proxy

HAR is not available in WPT test also. Could you do some error handling there? So test will not fail if Sitespeed can't fetch harTimeMetrics from WPT?

I will test the hanging problem in Firefox. I'll schedule a job for a hourly run and share the results.

**Comment by soulgalore** [comment] 2015-03-06 12:53
yep, good, I will handle the case with no HAR better, thanks!

**Comment by soulgalore** [comment] 2015-03-06 12:58
hmm @Vandrix maybe I was to fast, on one of my machines firefox also freezed, will continue to test.

**Comment by soulgalore** [comment] 2015-03-09 03:38
hey @Vandrix is it possible for you to share the URL that fails with the HAR (peter [at] soulgalore [.] com) so that I can verify the fix before I release it? 

Thanks!
Peter

**Comment by soulgalore** [comment] 2015-03-23 13:36
closing this now, get back to me if there is still a problem. with the hanging issue: The problem om Linux still exists for Chrome & the driver, however we now kills the process, so that URL will fail and we will continue with the next one. In coming version we may change so we retry with failing URL:s.

**Closed by soulgalore** 2015-03-23 13:36 UTC
