### ISSUE TITLE
Scripting click does not work after measure.stop()

### ISSUE THREAD

**Issue by Karalina763** [sitespeedio/sitespeed.io#2554] opened 2019-07-26 09:19 UTC
Hello,

I have a part of script 
`await commands.measure.start('Choose plan');
await commands.click.byXpathAndWait('//*[@aria-label="Choose Essential Plan"]');
await commands.measure.stop();
await commands.wait.byTime(2000);
await commands.click.byXpath('//*[@id="main"]/div/div/div[1]/div/section[2]/div[3]/div[1]/div[1]/div/div[2]/div[2]/div/label/div[2]/span');`
 and the following error 
"ERROR: JavascriptError: javascript error: Cannot read property 'click' of null". 
If I make script in the following way
`await commands.measure.start('Choose plan');
await commands.click.byXpathAndWait('//*[@aria-label="Choose Essential Plan"]');
await commands.measure.stop();
await commands.navigate('url_of_page_where_script_is');
await commands.wait.byTime(2000);
await commands.click.byXpath('//*[@id="main"]/div/div/div[1]/div/section[2]/div[3]/div[1]/div[1]/div/div[2]/div[2]/div/label/div[2]/span');` 

script works without error. The Xpath works in devtools. I use sitespeed.io:9.0.0-plus1 version. What should I do, could you help me, please?

**Comment by soulgalore** [comment] 2019-07-26 13:46
Hi @Karalina763 what version of sitespeed.io are you using? The error log looks like an older than the current stable version. If the element doesn't exist on the page it should log that so its easier to understand.

I think the problem is that the element doesn't exist. Here's the documentation with some tips on how you can debug:: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug

Best
Peter

**Comment by Karalina763** [comment] 2019-07-26 14:08
Еhanks for the reply
I've tried on 9.6.0-plus1 sidespeed version.
Element exists. I saw on video, that item appeared and Xpath for it works in devtools.
What else it can be?

**Comment by soulgalore** [comment] 2019-07-26 16:17
Did you get another error message? Try on your lical machine without Docker, that makes it easier to see.

**Comment by Karalina763** [comment] 2019-07-29 15:38
I've tried locally without docker:
`module.exports = async function(context, commands) {
 try {
    await commands.measure.start('https://XXX', 'Homepage');
    await commands.click.byXpath("//*[@role='dialog']//*[@class='cookie-banner__link-cont']/button");
    await commands.measure.start('Pay monthly');
    await commands.click.byPartialLinkTextAndWait('Pay monthly phones');
    return commands.measure.stop();
} catch (e) {
        throw e;
    }
}`
and saw in browser that `await commands.click.byXpath("//*[@role='dialog']//*[@class='cookie-banner__link-cont']/button");`was not executed. When script in following way:
`module.exports = async function(context, commands) {
 try {
    await commands.navigate('https://XXX');
    await commands.click.byXpath("//*[@role='dialog']//*[@class='cookie-banner__link-cont']/button");
    await commands.measure.start('https://XXX', 'Homepage');
    await commands.measure.start('Pay monthly');
    await commands.click.byPartialLinkTextAndWait('Pay monthly phones');
    return commands.measure.stop();
} catch (e) {
        throw e;
    }
}`
`await commands.click.byXpath("//*[@role='dialog']//*[@class='cookie-banner__link-cont']/button");`was executed. What wrong with the first script?

**Comment by soulgalore** [comment] 2019-07-29 20:48
Hi @Karalina763 so if I understand correctly you can get the element you want when navigating but when navigating and measuring it isn't there? They should both use the same pageCompleteCheck (=check when the page has finished loading) ... I wonder if there's a bug there. Can you see something more?

Best
Peter

**Comment by Karalina763** [comment] 2019-07-30 08:29
Hello @soulgalore it looks like "commands.click.by.." and "commands.wait.by.." don't work after measure.start(url), measure.start(url, alias) and measure.stop(). It's strange, because I saw during running script locally that my Xpath looked like be found, but then there was an error in output `"javascript error: Cannot read property 'click' of null\n`

**Comment by soulgalore** [comment] 2019-07-30 08:40
> javascript error: Cannot read property 'click' of null\

That means that the element you try to click on doesn't exist.

**Comment by Karalina763** [comment] 2019-07-30 08:44
@soulgalore but after measure.start() and navigate(url) it works fine. What the difference?

**Comment by soulgalore** [comment] 2019-07-30 14:49
I don't know, what do you try to do? :) I don't see that there's bug there, I think its how you try to get things on your page. Easiest way for you is to test on your local machine, watch the browser and see what happens. Try to log from your script, validate that element exists before you try to click on them etc.

**Comment by shubh1212** [comment] 2019-11-08 05:38
experiencing the same issue. @Karalina763 @soulgalore 
if i write the same click code inside the start()-stop(), it performs the job, but not while writing outside the stop().
I don't want to measure this click operation.

**Comment by soulgalore** [comment] 2019-11-08 06:52
@shubh1212 can you show me the code with some comments so I understand?

Thanks!
Peter

**Comment by shubh1212** [comment] 2019-11-08 08:55
Below is the error m getting while writing the code outside the stop():

[2019-11-08 00:21:08] DEBUG: [browsertime.chrome] Getting performance logs from Chrome
**[2019-11-08 00:21:23] ERROR:** [browsertime.command.wait] Element by xpath //span[contains(text(),'Published')]/preceding::div[1] was not located in 10000 ms
[2019-11-08 00:21:23] DEBUG: [browsertime] Closed the browser.

it throw error related to xpath.

but when i put the same click code inside the start()-stop() measure- it works fine.

below is the code snippet:

**this runs fine-**
```javascript
await commands.measure.start('KZ-Draft');
       await commands.click.byXpathAndWait("//span[contains(text(),'Draft')]/preceding::div[1]");
      
       
       await commands.wait.byXpath("//div[@data-qa='bricks-Header']/a[@href='/promote-inbox']/span[1]", 10000);
        
      await commands.click.byXpath("//div[@data-qa='bricks-Header']/a[@href='/promote-inbox']/span[1]");
      
       await commands.measure.stop();
```

below code throws error as mentioned above:

```javascript
await commands.measure.start('KZ-Draft');
       await commands.click.byXpathAndWait("//span[contains(text(),'Draft')]/preceding::div[1]");
      
            await commands.measure.stop();

       await commands.wait.byXpath("//div[@data-qa='bricks-Header']/a[@href='/promote-inbox']/span[1]", 10000);
        
      await commands.click.byXpath("//div[@data-qa='bricks-Header']/a[@href='/promote-inbox']/span[1]");
      

```

**Comment by soulgalore** [comment] 2019-11-08 11:39
If you look at the browser when it happens following  https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug 

Can you see then what's going wrong?

**Comment by soulgalore** [comment] 2020-07-06 08:03
Closing since no more feedback.

**Closed by soulgalore** 2020-07-06 08:03 UTC
Labels: need more info
