### ISSUE TITLE
report annotations for each script step

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#3033] opened 2020-06-11 10:07 UTC
Hello, 
I think it would be super useful to start pushing annotation events for each measured step from scripts. 
For current moment I can see annotations for the latest step leading to full HTML report. It's not convenient if you are interested in steps before and also confusing for the people who are not aware of all details.

Best Regards

**Comment by soulgalore** [comment] 2020-06-12 08:20
Hi @Icecold777 you are using InfluxDB right? If that's the case I think this is the same as https://github.com/sitespeedio/sitespeed.io/issues/2998 ?

I wanna fix this, you can help me with one thing: I'm no InfluxDB user but if I understand correctly as reported in #2998 the problem Is that if you send two annotations with the same timestamp (but different tags) only one will be saved in InfluxDB? Can you check if my assumption is right?  I've been thinking about it a lot and I think the easiest way to fix it is to use the timestamp of the first run for that URL from Browsertime, I made a POC for that a couple of weeks ago but didn't have the time to test it. I can probably do that next week, can you help me try that out in that case?

**Comment by soulgalore** [comment] 2020-06-13 20:02
@Icecold777 can you try out 13.3.1, I hope it works there.

**Comment by soulgalore** [comment] 2020-07-06 07:40
I think this was fixed in 13.3.1, let me know if it didn't work out.

**Closed by soulgalore** 2020-07-06 07:40 UTC
