### ISSUE TITLE
Cert issue on internal url. 

### ISSUE THREAD

**Issue by jab2805rakuten** [sitespeedio/sitespeed.io#2041] opened 2018-05-16 20:42 UTC
Trying to test internal dev site with no cert  I get the belo errors. 

docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.5.4  https://dev1.nj01/index.jsp --browsertime.chrome.args ignore-certificate-errors --firefox.acceptInsecureCerts --browsertime.firefox.acceptInsecureCerts
Google Chrome 63.0.3239.132 
Mozilla Firefox 54.0.1
[2018-05-16 20:40:42] INFO: Versions OS: linux 4.13.0-26-generic nodejs: v8.9.4 sitespeed.io: 6.5.4 browsertime: 2.5.0 coach: 1.3.0
[2018-05-16 20:40:42] INFO: Starting chrome for analysing https://dev1.nj01/index.jsp 3 time(s)
[2018-05-16 20:40:42] INFO: Testing url https://dev1.nj01/index.jsp run 1
[2018-05-16 20:40:44] ERROR: Could not load URLUrlLoadError: Failed to load https://dev1.nj01/index.jsp
[2018-05-16 20:40:44] ERROR: https://dev1.nj01/index.jsp generated the following error in Browsertime UrlLoadError: Failed to load https://dev1.nj01/index.jsp
    at getUrl.then.then.catch.catch.e (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:176:15)
    at tryCatcher (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2018-05-16 20:40:45] INFO: HTML stored in /sitespeed.io/sitespeed-result/dev1.nj01/2018-05-16-20-40-42
[2018-05-16 20:40:45] INFO: Finished analysing https://dev1.nj01/index.jsp

**Comment by soulgalore** [comment] 2018-05-16 20:57
Hi @jab2805rakuten is the URL you use reachable from within Docker?

Best
Peter

**Comment by jab2805rakuten** [comment] 2018-05-17 12:51
Yes it is. Thanks

**Comment by soulgalore** [comment] 2018-06-15 19:42
So can you help us how we should do to reproduce this issue? 
Thanks 
Peter

**Comment by soulgalore** [comment] 2019-01-26 19:56
Closing since we didn't get any feedback on how to reproduce.

**Closed by soulgalore** 2019-01-26 19:56 UTC
