### ISSUE TITLE
Browsertime async error - [Error: Callback was already called]

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/sitespeed.io#863] opened 2016-04-08 16:26 UTC
Hello @soulgalore @tobli .

We have been running sitepseed.io in our CI Jenkins box every hour. Each job runs 10 executions for one url. From time to time (atleast twice a day) we see Chromedriver hanging throwing following error:
```22:42:15 Killed the Chromedriver instance because Chrome/driver was hanging.
22:42:21 Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called.
22:42:21     at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:43:36
22:42:21     at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:723:17
22:42:21     at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:167:37
22:42:21     at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:94:7```

Other times, even if chromedriver is not hung, I see the exception 
```Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called.
22:42:21     at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:43:36
22:42:21     at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:723:17
22:42:21     at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:167:37
22:42:21     at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:94:7```
thrown without any other stack trace.

Version Info:  (this is inside docker container)
``  OS: 'linux 3.10.0-123.el7.x86_64', Node.js: 'v4.2.6', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.7.0_91', browsertime: '0.12.2'```

Any ideas?

**Comment by soulgalore** [comment] 2016-04-11 19:04
Hey @abhagupta 
yes that's one of the main issues of the major rewrite for 4.0. Or more a couple of things. Things I've seen is that sometimes the chrome & chromedriver gets out of sync (the driver tries to reach chrome on wrong port), it happens in nodejs, that's why we also include the selenium jar in the docker container. The other (major) problem that happens is that Chrome don't start (mostly on some Linux). So that is usually the causes, the symptoms (that you listed) is that in the current version it's callback hell and it's hard to actually handle the errors.

In the new version, we use promises so it's cleaner,  we can catch things in a better way and we also have retry functionality.

When we tested the new version on Digital Ocean we haven't seen any others like this, so lets hope it is fixed now and works better. Still, there's some time until we release 4.0.

Best
Peter

**Comment by soulgalore** [comment] 2016-10-28 09:46
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Closed by soulgalore** 2016-10-28 09:46 UTC
