### ISSUE TITLE
Unable to see the metrics in pages tab 

### ISSUE THREAD

**Issue by QTSankarRajan** [sitespeedio/sitespeed.io#3797] opened 2023-03-23 07:33 UTC
### Your question

In the sitespeed report, I observe that metrics for measurements like Total transfer size, total requests, Third party requests etc are reported as 0 which cant be reported as zero as there where requests and response received as we could see in HAR file and screenshots are recorded confirming required actions have happened. 

Can someone help me understand why this is reported as zero. Is it something expected.

![image](https://user-images.githubusercontent.com/100260268/227134227-9f2fd982-7c85-4135-9f10-5bc9a0f31a11.png)

**Comment by soulgalore** [comment] 2023-03-23 07:48
Hi @QTSankarRajan what browser are you using? How can I reproduce it, it looks like a potential bug?

**Comment by QTSankarRajan** [comment] 2023-03-23 08:04
> Hi @QTSankarRajan what browser are you using? How can I reproduce it, it looks like a potential bug?

Thanks for responding.

I am using chrome as browser as that is the targeted browser for my application that I am testing. 

I have created a JS based script and executed a test with the script. 

Note : I am using sitespeed 26.0 version

**Comment by soulgalore** [comment] 2023-03-23 09:03
Can you share the HAR file? If you cannot share the script, I can at least look at the HAR, the data in the HAR should generate the sizes in that table, so it looks like something is wrong.

**Comment by QTSankarRajan** [comment] 2023-03-24 06:30
I am testing the application from secured network. Hence I dont have permissions to share the HAR file. Anyways I have shared the screenshot of the HAR file to show you the size of the requests.

![image](https://user-images.githubusercontent.com/100260268/227442723-8c6a9ede-f611-4d8a-8ca7-88d29cbfe843.png)

**Comment by QTSankarRajan** [comment] 2023-04-03 08:09
@soulgalore I recently observed that summary metrics in Paes tab like Total Requests, Total Transfer Size etc are captured only for the tests done with direct URL in command line whereas same is not being captured for the test done through JS script for same URL too. Is this actual behavior of the tool? Or is it a bug?

**Comment by QTSankarRajan** [comment] 2023-08-08 11:55
@soulgalore  Could you please help in letting me know if fix available for this?

**Comment by soulgalore** [comment] 2023-08-08 14:20
@QTSankarRajan sorry I missed that. So can you share how you run? When I test it seems to work:

test.mjs
```
export default async function (context, commands) {
  await commands.navigate('https://www.sitespeed.io');

  await commands.measure.start();
  // Click on the link and wait on navigation to happen but try catch it so we can catch if it fails
  try {
    await commands.click.bySelectorAndWait(
      'body > nav > div > div > div > ul > li:nth-child(2) > a'
    );
    await commands.measure.stop();
  } catch {
    context.log.error('Could not click on ....');
  }
}
```

`sitespeed.io test.mjs --multi -n 1 -o`


<img width="1185" alt="Screenshot 2023-08-08 at 16 19 32" src="https://github.com/sitespeedio/sitespeed.io/assets/540757/5d0b9591-4b63-427f-a02d-fa4cae81ac38">


Can you please share an example where it doesn't work so I can reproduce it? Thanks!

**Comment by soulgalore** [comment] 2023-12-28 05:28
Didn't get a response so closing.

**Closed by soulgalore** 2023-12-28 05:28 UTC
