### ISSUE TITLE
How to  get Webpage test summery in grafana

### ISSUE THREAD

**Issue by nagamallala** [sitespeedio/sitespeed.io#1388] opened 2016-12-20 05:25 UTC
Hi 
I setup the grafana by using Up and running in 5 minutes in site speed.io
 and setup the browser time using  docker file and running $ docker build -t sitespeedio/browsertime .

I Ran the command 

docker run  --rm -v "$(pwd)":/browsertime-results sitespeedio/browsertime  https://www.wyndhamhotels.com -b firefox

by running above command I was getting  the .json file and .hra file in the root directory.

I would like the see the result in grafana. I was running the command 

docker run  --rm -v "$(pwd)":/browsertime-results sitespeedio/browsertime  https://www.wyndhamhotels.com -b firefox —-graphite.host 10.187.31.112

 but unable to see the Webpage Test Summery in grafana please help me out.

thanks in advance

**Comment by tobli** [comment] 2016-12-20 06:41
Hi!
You'll want to use the sitespeed.io image, not the browsertime image (browsertime is just the component in Sitespeed.io that interacts with the browser). Also there's no need to Docker build the image yourself from source, unless you're planning to contribute to development. Just pull the pre-built image from Docker hub.

**Comment by nagamallala** [comment] 2016-12-20 07:20
HI tobli thanks for response.
I used site speed.io image as well but unable to get WPT summary in grafana, able to get page summary and site summary only.

I ran the below command able to get site and page summary but unable to get WPT.
docker run sitespeedio/sitespeed.io https://www.wyndhamhotels.com  -b firefox --graphite.host 10.187.31.112

**Comment by soulgalore** [comment] 2016-12-20 07:22
Hey @nagamallala you already created an issue for this and I answered: https://github.com/sitespeedio/sitespeed.io/issues/1383

:)

If you want WebPageTest data, you need setup WebPageTest following the instructions in the docs :)

Best
Peter

**Comment by nagamallala** [comment] 2016-12-20 07:29
Yup Soulgalore I have done setup and able to get .json and .hra files as result.
But I would like see WPT summary in grafana.

**Comment by soulgalore** [comment] 2016-12-20 07:37
I did not see in your example that you provide the WebPageTests host URL nor the optional key?

**Comment by julrich** [comment] 2016-12-20 19:31
Btw., I'm seeing problems getting WPT data into Graphite, too. Would probably lead to similar problems in Grafana, when used as a Datasource. 

It outputs "Got https://domain.com analysed from wpt.instance.com" in the output, which seems to be directly followed by "Send data to Graphite graphite.host:2003". But inside Graphite there are only subdirectories _pageSummary_ and _summary_,  with _pageSummary_ having entries _chrome_ and _gpsi_ for the scanned domain, but no _wpt_ anywhere.

Inside the generated result report there's an empty entry `{ "webpagetest": {} }` when looking at the Errors tab.


Dec 20 18:59:15 momcorpofro docker[17489]: [2016-12-20 18:59:15] Send data to Graphite graphite.services.ruhmesmeile.local:2003
Dec 20 18:59:29 momcorpofro docker[17489]: [2016-12-20 18:59:29] Got https://ruhmesmeile.com analysed from wpt.ruhmesmeile.tools

**Comment by soulgalore** [comment] 2016-12-20 19:37
hey @julrich I don't think it is the same issue, it seems like (at least in the example) @nagamallala didn't configure to run WebPageTest.

Wanna check, do you run latest 4.2.0? There was a fix there for testing multiple URLs in WebPageTest #1367 before that fix it failed if you tested more than one URL (puh).

**Comment by julrich** [comment] 2016-12-20 19:41
Okay, that's very possible :) Running latest 4.2.0, yep. Im only testing one url, though. Directly by passing it to the Docker image.

Want me to open another issue for this?

**Comment by soulgalore** [comment] 2016-12-20 19:47
Yes if you can do that it would be super, thanks! And if you can show me exactly how you run it would be great, I can probably fix it tonight and have 4.2.1 out.

**Comment by julrich** [comment] 2016-12-20 19:47
Sure, no problem!

**Comment by soulgalore** [comment] 2017-03-03 08:38
This should work now. Closing, let us know if this is still an issue.

**Closed by soulgalore** 2017-03-03 08:38 UTC

**Comment by CaptainJojo** [comment] 2017-12-14 12:21
Sorry but I have same problem my graphana haven't WPT data, how to configurure correctly my config.json is


```
{
  "metrics": {
    "filter": [
      "webpagetest.pageSummary.*"
    ]
  }
}
```

**Comment by soulgalore** [comment] 2017-12-14 12:30
@CaptainJojo the dashboard run with the default configuration, it should if there'n not a bug in the dashboard. Grafana has had bug saving the dashboards that includes constants but I think it should be fixed. You do run your own WebPageTest instance right?

**Comment by CaptainJojo** [comment] 2017-12-14 12:43
Thank for your response, no I use directly webpagetest.org is not good ?

**Comment by soulgalore** [comment] 2017-12-14 12:49
No that works. As long as you configured sitespeed.io to send the metrics, both Browsertime and WebPageTest metrics goes to Graphite. You get other metrics but no WebPageTest metrics?

If you log into Grafana and check, do you see the metrics in the raw queries? The query looks something like **$base.$path.pageSummary.$domain.$page.webpagetest.$location.$connectivity.data.median.$view.render** ... you can just go step by step depending on what base you choosed.

**Comment by CaptainJojo** [comment] 2017-12-14 12:50
ok thank :)
