### ISSUE TITLE
WPT custom metric : is it implemented ?

### ISSUE THREAD

**Issue by jpvincent** [sitespeedio/sitespeed.io#1348] opened 2016-11-24 17:31 UTC
Hi

I'm trying to graph some WPT custom metrics, as indicated into the [documentation](https://www.sitespeed.io/documentation/sitespeed.io/webpagetest/#custom-metrics)

My custom metric correctly appears in the WPT UI for this test, but nothing seems to be sent to the  the graphite instance (I console.log all what is sent to graphite).

When looking in the source in the [libs/plugins/webpagetest/aggregator.js](https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/webpagetest/aggregator.js#L38) file, I see a nice little comment (line 38) :

``` javascript
// TODO get all custom metrics
```

I confirm I'd like to see it implemented :)
Nothing vital though

**Comment by soulgalore** [comment] 2016-11-24 19:50
Hehe :) Yep, we needed to cut some corners to get things implemented for 4.0. Would you be up for give it a try? There's some work that needs to be done: pick up the values, display them on the HTML page and make sure the automagically is sent to Graphite. Else I'll fix this the coming weeks I think.

**Comment by jpvincent** [comment] 2016-11-28 08:32
I have a stressful agenda in december, but I would like to add that to my project, so I will try to code it in 2 weeks or so : at least picking up the values and sending them to graphite because I think I now see how to to it. If time allows, I will try to display that in the HTML too.

**Comment by soulgalore** [comment] 2016-12-14 14:46
We released this today!

**Comment by jpvincent** [comment] 2016-12-29 15:48
Hi, sorry to re-open this, but it looks like 

For example, that is sent to graphite :
`sitespeed_io.default.pageSummary.www_sitespeed_io._.webpagetest.first_wptdriver-chrome.custom.data.median.firstView.gifNumber 0 1483024318`
where gifNumber is the custom metrics. 
However, it seemed to me that you were putting all of the custom metrics under an additional .custom path, something like
`sitespeed_io.default.pageSummary.www_sitespeed_io._.webpagetest.first_wptdriver-chrome.custom.data.median.firstView.custom gifNumber 0 1483024318`

I think it was this way because I had a dashboard that looks for this path, that does not work since some days (this fix maybe ? https://github.com/sitespeedio/sitespeed.io/commit/fc6a06e8f3a4108ac220c14c4cffadbdb1a40cab ) and because, it is the way it is done for the summary : 
`sitespeed_io.default.summary.www_sitespeed_io.webpagetest.first_wptdriver-chrome.custom.custom.firstView.custom.gifNumber.median 0 1483024318 `

And that is so much easier

**Comment by soulgalore** [comment] 2016-12-29 19:15
Hey @jpvincent yes that could be true, it doesn't work as in 3.x. I know having a custom label would make it easier, but this time I just followed the JSON structure of WebPageTest :| For custom metrics that is just flat (meaning no extra key part telling it is a custom metric. We automagically detect it and send it to Graphite, but as you say, making a generic dashboard for custom metrics is hard then. Lets see if we ca fix that + best case we could change WPT so that it has the same behaviour for both UserTimings and Custom metrics (user timings has better structure).

**Comment by soulgalore** [comment] 2018-06-16 16:49
I think we can close this: the problem is the JSON from WPT and if that is fixed in the future, we can fix that here too.

**Closed by soulgalore** 2018-06-16 16:49 UTC
Labels: enhancement
