### ISSUE TITLE
x-axis value disappearing in waterfall model representation of page load

### ISSUE THREAD

**Issue by manjunathpremkumar** [sitespeedio/sitespeed.io#3725] opened 2022-09-19 04:32 UTC
Hi, 

We noticed that in our one of scripted journey test, x-axis values (in seconds) are not appearing for waterfall model representation of page load. We are able to reproduce this issue multiple times. Attached the HAR file for the page loaded and screenshot of the issue.

Note: This is happening for this particular user journey and not for other journeys.
[IBE_Guest_PassengerDetails_Page_Load-chrome-2022-09-07183603.har.gz](https://github.com/sitespeedio/sitespeed.io/files/9596147/IBE_Guest_PassengerDetails_Page_Load-chrome-2022-09-07183603.har.gz)
![X-axis](https://user-images.githubusercontent.com/43643055/190950196-2b68bad1-852d-4d3a-a287-5fdd34c89514.JPG)

**Comment by soulgalore** [comment] 2022-09-19 12:46
Thank you @manjunathpremkumar for creating the issue (and attaching the HAR, very helpful!). I tested and I could see the same on https://micmro.github.io/PerfCascade/ (that's the thing we use to display the HAR). Do you have time to create an issue in [that repo](https://github.com/micmro/PerfCascade)? Else I can do it later this week.

**Comment by manjunathpremkumar** [comment] 2022-09-20 06:40
@soulgalore  - I have raised the issue as suggested  and issue number #288

**Comment by soulgalore** [comment] 2023-12-27 16:37
Closing since the root cause is not in sitespeed.io

**Closed by soulgalore** 2023-12-27 16:37 UTC
