### ISSUE TITLE
URL not reachable when sitespeed.io command executed with webpagetest parameters

### ISSUE THREAD

**Issue by senz79** [sitespeedio/sitespeed.io#2243] opened 2019-01-07 12:02 UTC
Hello 
I am getting issue to run the sitespeed.io command with webpagetest parameters. I get the below error 

[2019-01-07 11:54:36] INFO: Versions OS: linux 3.10.0-957.1.3.el7.x86_64 nodejs: v10.13.0 sitespeed.io: 7.7.3 browsertime: 3.11.1 coach: 2.4.0
[2019-01-07 11:54:37] INFO: Sending url http://w3schools.com to test on http://xxxxxx
[2019-01-07 11:54:37] INFO: Starting chrome for analysing http://w3schools.com 1 time(s)
[2019-01-07 11:54:37] INFO: Testing url http://w3schools.com iteration 1
[2019-01-07 11:54:51] INFO: 36 requests, 514.52 kb, backEndTime: 46ms, firstPaint: 209ms, firstVisualChange: 200ms, DOMContentLoaded: 327ms, Load: 2.73s, speedIndex: 201, visualComplete85: 200ms, lastVisualChange: 333ms, rumSpeedIndex: 209
[2019-01-07 11:55:27] INFO: Got http://w3schools.com analysed with id 190107_XK_2cb50e3d533447b8b3b07dcc75b288a0 from http://xxxxxx
[2019-01-07 11:55:27] WARN: Couldn't get screenshot for id 190107_XK_2cb50e3d533447b8b3b07dcc75b288a0, run 1: Not Found (url = http://w3schools.com)
[2019-01-07 11:55:27] ERROR: Incomplete first view data for WPT test 190107_XK_2cb50e3d533447b8b3b07dcc75b288a0, run 1
[2019-01-07 11:55:28] ERROR: TypeError: /usr/src/app/lib/plugins/html/templates/pages.pug:8
    6|     - p = pageInfo.data.pagexray ? pageInfo.data.pagexray.pageSummary : {}
    7|     - b = pageInfo.data.browsertime ? pageInfo.data.browsertime.pageSummary : {}
  > 8|     - t = p.contentTypes || {javascript: {transferSize: ''}, css: {transferSize: ''}, image: {transferSize: ''}}

My Command is 
=============================
  docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.7.3 http://w3schools.com  --graphite.host xxxxxxxx --graphite.auth graphite:password -n 1 --browsertime.proxy.http http://xxxxxxxxx:8080 --browsertime.proxy.https http://xxxxxxxx:8080 --browsertime.chrome.args no-sandbox --webpagetest.host http://xxxxxxxx --webpagetest.location Local-WPTDriver --webpagetest.includeRepeatView true --webpagetest.timeout 3600 --webpagetest.runs 1 --webpagetest.connectivity Cable --webpagetest.useragent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

Few Insights
===========================
1. When i run the sitespeed.io command without webpagetest parameter, it is success
2. When i run the URL from private instance of webpagetest, it is success
3. when i run the sitespeed.io command with webpagetest parameter, the webpagetest driver accepts the work, opens the browser but the url is not reachable

**Comment by soulgalore** [comment] 2019-01-07 20:15
Hi @senz79 thanks for reporting!

I think this is more a WebPageTest error than sitespeed.io, but I can have a go: `--webpagetest.location Local-WPTDriver` doesn't look right, what is expected there or what do you want to happen?

Best
Peter

**Comment by senz79** [comment] 2019-01-08 04:12
This is how my location.inin files looks like in WebPageTest Private Instance Installation
=========================================================
[locations]

1=Local

default=Local


[Local]

1=Local-URLBlast

2=Local-WPTDriver

label="Local"

default=Local-WPTDriver


[Local-URLBlast]

browser=IE 9

latency=0

label="Local - IE 9"


[Local-WPTDriver]

browser=Chrome,IE

label="Local-wptdriver"

**Comment by soulgalore** [comment] 2019-01-08 15:36
Ok. So if I understand correctly: Your instance work fine if you it with the GUI, but when. you use site speed.io and choose Local-WPTDriver it fails? I don't think we do anything with the location before sending it to WebPageTest (through the WPT-API but I need to verify. If you run with` --verbose` it will log log how the configuration is interpreted and I think also what we send to WebPageTest.

Best
Peter

**Comment by senz79** [comment] 2019-01-09 03:59
Thanks for the reply Peter, and sorry for the delayed response due to different timezone. below is the verbose log

Log
===========================
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.7.3 http://w3schools.com  --graphite.host xxxxxxxx --graphite.auth graphite:password -n 1 --browsertime.proxy.http xxxxxxxx --browsertime.proxy.https xxxxxxxxx --browsertime.chrome.args no-sandbox --webpagetest.host http://xxxxxxxx --webpagetest.location Local-WPTDriver --webpagetest.includeRepeatView true --webpagetest.timeout 3600 --webpagetest.runs 1 --webpagetest.connectivity Cable --verbose
Google Chrome 71.0.3578.80
Mozilla Firefox 64.0
[2019-01-09 03:50:57] INFO: [sitespeedio] Versions OS: linux 3.10.0-957.1.3.el7.x86_64 nodejs: v10.13.0 sitespeed.io: 7.7.3 browsertime: 3.11.1 coach: 2.4.0
[2019-01-09 03:50:57] DEBUG: [sitespeedio.plugin.graphite] Setting up Graphite xxxxxxxx:2003 for namespace sitespeed_io.default
[2019-01-09 03:50:58] INFO: [sitespeedio.plugin.webpagetest] Sending url http://w3schools.com to test on http://xxxxxxxx
[2019-01-09 03:50:58] INFO: [sitespeedio.plugin.browsertime] Starting chrome for analysing http://w3schools.com 1 time(s)
[2019-01-09 03:50:58] INFO: [browsertime] Testing url http://w3schools.com iteration 1
[2019-01-09 03:50:59] DEBUG: [browsertime.video] Add orange color
[2019-01-09 03:50:59] DEBUG: [browsertime.video] Started ffmpeg with -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast /tmp/browsertime-HOkY32/x11.mp4
[2019-01-09 03:51:03] DEBUG: [browsertime] Waiting for script pageCompleteCheck at most 300000 ms
[2019-01-09 03:51:05] DEBUG: [browsertime.video] Stop screen recording
[2019-01-09 03:51:05] DEBUG: [browsertime.video] Stopped ffmpeg
[2019-01-09 03:51:05] DEBUG: [browsertime.video] Converting video to viewable format with args ["-nostdin","-i","/tmp/browsertime-HOkY32/x11.mp4","-c:v","libx264","-crf",23,"-preset","medium","-vf","format=yuv420p","/sitespeed.io/sitespeed-result/w3schools.com/2019-01-09-03-50-57/pages/w3schools.com/data/video/1.mp4"]
[2019-01-09 03:51:07] DEBUG: [browsertime.video] Writing to /sitespeed.io/sitespeed-result/w3schools.com/2019-01-09-03-50-57/pages/w3schools.com/data/video/1.mp4
[2019-01-09 03:51:08] DEBUG: [browsertime.chrome] Getting performance logs from Chrome
[2019-01-09 03:51:08] DEBUG: [browsertime.video] Running visualMetrics
[2019-01-09 03:51:09] DEBUG: [browsertime.video] Collected metrics {"SpeedIndex":968,"PerceptualSpeedIndex":967,"FirstVisualChange":967,"LastVisualChange":1033,"VisualProgress":"0=0%, 967=97%, 1000=99%, 1033=100%"}
[2019-01-09 03:51:13] DEBUG: [browsertime] Telling browser to quit.
[2019-01-09 03:51:14] INFO: [browsertime] 36 requests, 516.69 kb, backEndTime: 794ms, firstPaint: 958ms, firstVisualChange: 967ms, DOMContentLoaded: 1.04s, Load: 3.74s, speedIndex: 968, visualComplete85: 967ms, lastVisualChange: 1.03s, rumSpeedIndex: 958
[2019-01-09 03:51:14] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite xxxxxxxx
[2019-01-09 03:51:14] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite xxxxxxxx
[2019-01-09 03:51:14] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite xxxxxxxx
[2019-01-09 03:53:59] INFO: [sitespeedio.plugin.webpagetest] Got http://w3schools.com analysed with id 190109_FS_ef7729c14903ad5ffe2724c209f54e5b from http://10.211.164.178
[2019-01-09 03:53:59] WARN: [sitespeedio.plugin.webpagetest] Couldn't get screenshot for id 190109_FS_ef7729c14903ad5ffe2724c209f54e5b, run 1: Not Found (url = http://w3schools.com)
[2019-01-09 03:53:59] ERROR: [sitespeedio.plugin.webpagetest] Incomplete first view data for WPT test 190109_FS_ef7729c14903ad5ffe2724c209f54e5b, run 1
[2019-01-09 03:53:59] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite xxxxxxxx
[2019-01-09 03:53:59] DEBUG: [plugin.browsertime] Generate summary metrics from Browsertime
[2019-01-09 03:53:59] DEBUG: [plugin.coach] Generate summary metrics from the Coach
[2019-01-09 03:53:59] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite xxxxxxxx
[2019-01-09 03:53:59] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite xxxxxxxx
[2019-01-09 03:53:59] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite xxxxxxxx
[2019-01-09 03:53:59] DEBUG: [plugin.pagexray] Generate summary metrics from PageXray
[2019-01-09 03:53:59] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite xxxxxxxx
[2019-01-09 03:53:59] DEBUG: [sitespeedio.plugin.html] Render HTML for 1 page(s)
[2019-01-09 03:53:59] DEBUG: [sitespeedio.plugin.html] Render summary page pages
[2019-01-09 03:53:59] ERROR: [sitespeedio.queuehandler] TypeError: /usr/src/app/lib/plugins/html/templates/pages.pug:8
    6|     - p = pageInfo.data.pagexray ? pageInfo.data.pagexray.pageSummary : {}
    7|     - b = pageInfo.data.browsertime ? pageInfo.data.browsertime.pageSummary : {}
  > 8|     - t = p.contentTypes || {javascript: {transferSize: ''}, css: {transferSize: ''}, image: {transferSize: ''}}
    9|     - display = (options.urlsMetaData && options.urlsMetaData[url] && options.urlsMetaData[url].alias) ? options.urlsMetaData[url].alias : url
    10|     tr
    11|       td.url.pagesurl(data-title='URL')

Cannot read property 'contentTypes' of undefined
    at Object.eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:165:7)
    at Object.pug_interp [as rows] (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:217:4)
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:378:19)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:417:199)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:27:37)
    at HTMLBuilder._renderSummaryPage (/usr/src/app/lib/plugins/html/htmlBuilder.js:340:16)
    at Object.keys.map.name (/usr/src/app/lib/plugins/html/htmlBuilder.js:150:12)
    at Array.map (<anonymous>)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:149:54)
    at Object.processMessage (/usr/src/app/lib/plugins/html/index.js:201:35)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
[2019-01-09 03:53:59] INFO: [sitespeedio] Finished analysing http://w3schools.com

**Comment by soulgalore** [comment] 2019-01-09 07:59
And off you go to the result page at your WebPageTest server ( 190109_FS_ef7729c14903ad5ffe2724c209f54e5b)? Can you see something there? I think the original problem is there but it seems we need to catch the case better.

Best
Peter

**Comment by soulgalore** [comment] 2019-01-09 08:45
I mean if you go to that result page on your WebPageTest server with id 190109_FS_ef7729c14903ad5ffe2724c209f54e5b ? Or do you mean you cannot find the run?

**Comment by senz79** [comment] 2019-01-09 09:48
Peter - I cannot find the run, the same is not created.

**Comment by senz79** [comment] 2019-01-09 09:52
Screenshot of the same folder
![image](https://user-images.githubusercontent.com/12895992/50891494-66580980-1422-11e9-838e-9837f2436f06.png)

**Comment by soulgalore** [comment] 2019-01-09 09:54
Please ask at https://github.com/WPO-Foundation/webpagetest I think Pat has more knowledge of what's wrong.

Best
Peter

**Comment by senz79** [comment] 2019-01-09 09:56
According to https://github.com/WPO-Foundation/webpag...ch?q=12029 this error code can mean ERR_ADDRESS_UNREACHABLE, ERR_CONNECTION_REFUSED, or ERR_CONNECTION_TIMED_OUT.

**Comment by pmeenan** [comment] 2019-01-09 15:50
12029 is the error for a connect fail from the agent. When you go to the test result page for the test ID on your private WebPageTest instance, what does it show for the URL, browser, location and connectivity (a screenshot of the WebPageTest result page might help)?

If you test the same URL through the WebPageTest UI of the private instance does it work (and what does the screen shot look like)?

The log looks a little strange but I'm not used to what sitespeed log files look like.  I wouldn't have expected to see browsertime log entries for a wptagent test.

**Comment by soulgalore** [comment] 2019-01-16 07:20
@senz79 sorry I got caught up in other things. Yeah I'm also a little confused. Could you show me exact how I can reproduce as in https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue and when it works and when not, so I can look into it?

**Comment by soulgalore** [comment] 2019-02-17 17:11
Closing this since we never heard back, but please ping the issue again if you still have the issue so we can help you!

**Closed by soulgalore** 2019-02-17 17:11 UTC
Labels: need more info
