### ISSUE TITLE
Unable to run npm browsertest in RHEL7

### ISSUE THREAD

**Issue by Manigunner** [sitespeedio/sitespeed.io#2495] opened 2019-06-04 17:26 UTC
Command Used:

npm install browsertime -g

Versions:
Node: v6.0.0
npm: v3.8.6
OS: RHEL7

Expected result: browsertime should get installed

Actual result:
/test/user/jenkins/.nvm/versions/node/v6.0.0/bin/browsertime -> /test/user/jenkins/.nvm/versions/node/v6.0.0/lib/node_modules/browsertime/bin/browsertime.js

> @sitespeed.io/chromedriver@74.0.372-9.6-1 install /test/user/jenkins/.nvm/versions/node/v6.0.0/lib/node_modules/browsertime/node_modules/@sitespeed.io/chromedriver
> node install.js

/test/user/jenkins/.nvm/versions/node/v6.0.0/lib/node_modules/browsertime/node_modules/@sitespeed.io/chromedriver/install.js:50
async function download() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
/test/user/jenkins/.nvm/versions/node/v6.0.0/lib
└── (empty)

npm ERR! Linux 3.10.0-957.10.1.el7.x86_64
npm ERR! argv "/test/user/jenkins/.nvm/versions/node/v6.0.0/bin/node" "/test/user/jenkins/.nvm/versions/node/v6.0.0/bin/npm" "install" "browsertime" "-g"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! @sitespeed.io/chromedriver@74.0.372-9.6-1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sitespeed.io/chromedriver@74.0.372-9.6-1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @sitespeed.io/chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @sitespeed.io/chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @sitespeed.io/chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /test/user/jenkins/.npm/npm-debug.log
npm ERR! code 1

i tried upgrading Node version to 8.9.1 on running the npm command, getting the rollback error
$ npm install browsertime -g
npm ERR! code E418
npm ERR! 418 I'm a teapot: browsertime@latest

Please help on steps to resolve the error. TIA

**Comment by soulgalore** [comment] 2019-06-04 17:28
Hi @Manigunner you need to upgrade NodeJs to use latest LTS https://nodejs.org/en/. Async/await didn't exist in node 6.

Best
Peter

**Comment by Manigunner** [comment] 2019-06-07 16:47
Hi @soulgalore, Thanks your suggestion worked by upgrading Node LTS. I used yarn setup and installation was successful
Now am using the set of commands inside the Docker file and struck up at installation command

Dockerfile:
Step 22/22 : RUN sudo http_proxy='http://prod-proxy-out.ttv.com:8080' https_proxy='http://prod-proxy-out.ttv.com' yarn global add sitespeed.io
 ---> Running in 301490da7897
/usr/local/lib/node_modules/yarn/lib/cli.js:45703
  let {
      ^



SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

Please help on the issue.

**Comment by soulgalore** [comment] 2019-11-18 00:08
"let" is also from a newer NodeJS version, I'm thinking the upgrade to correct version didn't happen?

Closing this since the issue is so old. Let me know if you still need help!

**Closed by soulgalore** 2019-11-18 00:08 UTC
