### ISSUE TITLE
Steps are not clear in documentation of sitespeed.io site for installation

### ISSUE THREAD

**Issue by swapnaadusumilli** [sitespeedio/sitespeed.io#736] opened 2015-08-27 16:43 UTC
Hi, I have tried to configure this tool both in windows and Linux but second step in download and installation is not only work. It's not that much information to follow the steps in all OS systems. Please share if you have any documentation steps fro windows and Linux.

**Comment by rafalSuntimes** [comment] 2015-08-27 18:03
npm install sitespeed.io // this installs sitespeed.io locally
    npm install -g sitespeed.io // this installs sitespeed.io globally

Are you getting any errors? Can you show us what the problem is?

**Comment by swapnaadusumilli** [comment] 2015-08-27 18:15
I have installed it successfully (global) and able to test the sites in local. But I'm trying to configure the other steps after this like Vagrant, Docker, Graphite and Grafana. 

https://www.sitespeed.io/documentation/installation/

I wanted to install all these in windows and linux. So, steps are not very clear to install all other steps. Will you have any other document to refer to install other steps?

I have one more question, If site performance or any page is down then, is there any settings are there to send alerts or not?

Thank you!

**Comment by rafalSuntimes** [comment] 2015-08-27 23:13
Not sure if you know the difference between Vagrant and Docker, so I will just throw it out here. On a very high level, Vagrant box gives you a standalone Virtual Machine box, with an operating system, and so on, whereas a Docker image is just a program, a library, or any other binaries that the author put together, but it is not a standalone system image.

If you choose to go ahead with Docker, then the team has made available Docker images that you can use (https://hub.docker.com/u/sitespeedio/). Of course you need Docker installed on your host first (https://docs.docker.com/installation/).

For example, to use Sitespeed.io docker image, you would do the following:

    sudo docker pull sitespeedio/sitespeed.io
    sudo docker run --privileged --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u https://www.sitespeed.io -b firefox

Notice that the last section of the second command (namely "-u https://www.sitespeed.io -b firefox") is just composed of regular Sitespeed.io flags (https://www.sitespeed.io/documentation/configuration/#the-options).

To use all other Docker images, you follow similar commands.

If you choose to use Vagrant, the team provides a Vagrant box with Ubuntu 14 or CentOS 7.
- Ubuntu Vagrant box: https://github.com/sitespeedio/sitespeed.io-vagrant/tree/master/sitespeed-ubuntu14
- CentOS 7 box: https://github.com/sitespeedio/sitespeed.io-vagrant/tree/master/sitespeed-centos7

Read what each box contains. 

Since those spin up real virtual machines, you can do anything you want to them. If you have no prior exposure to Vagrant, I recommend going through the Getting Started docs form Vagrant first (http://docs.vagrantup.com/v2/getting-started/index.html). They will teach you the basics on how to set up, use, and access a vagrant box.

Now, if you are interested in setting up Graphite and Grafana as well, you can find Vagrant boxes online. I may be mistaken, but I don't think they are referenced in the Sitespeed.io documentation. 

If you choose to install Graphite and Grafana yourself, follow these two tutorials, which is what I did when I set them up for my environment. 

- Graphite on Ubuntu 14.04: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-graphite-on-an-ubuntu-14-04-server
- Grafana on Ubuntu / Debian: http://docs.grafana.org/installation/debian/

That was a lot... I hope I cleared some things up.

**Comment by soulgalore** [comment] 2015-08-28 06:14
thanks @rafalSuntimes for explaining.

@swapnaadusumilli if Docker is ok for you I think that is the easiest way forward.

**Comment by swapnaadusumilli** [comment] 2015-08-28 14:10
Thank you @rafalSuntimes for the explanation.

Do we get notifications also if something is down or not working? or Is this only to check the performance of site and checking scalability?

**Comment by rafalSuntimes** [comment] 2015-08-28 14:30
Not sure what you mean by notification. Since sitespeed.io in a binary, it can only throw an error when it fails.

**Comment by swapnaadusumilli** [comment] 2015-08-28 14:37
oh ok. So, there is no option that can send email alerts right when there is an error in site.
Is it also supports to check site availability for 24 hours automatically? If yes, what are the steps to configure it for 24 hours?
Thank you!

**Comment by rafalSuntimes** [comment] 2015-08-28 14:43
Don't be sorry, that's what the community is for. Have you ever used Jenkins, or any other Continuous Integration tool? If sitespeed.io simply fails, you can trigger there Jenkins build as a failure. In Jenkins, you can absolutely notify anyone, via email, that a build has failed. You can play around with it and suit it for your needs. I have never set that up myself, but it could be interesting to see that in action.

ref: https://www.sitespeed.io/documentation/continuous-integration/

**Comment by rafalSuntimes** [comment] 2015-08-28 14:45
On thins to remember is that no tool should try to be a God tool, so to speak. Let's let sitespeed.io collect tools, graphite to store and aggregate it, grafana to display it and Jenkins to make it all run continuously. It's good to make everything as modular as possible, low in coupling and high in cohesion sort of thing..

**Comment by swapnaadusumilli** [comment] 2015-08-28 15:11
ok got you. Thanks @rafalSuntimes.

**Comment by swapnaadusumilli** [comment] 2015-09-01 18:02
@rafalSuntimes , Can we have option to do sequence of steps in UI using sitespeed? Example: If I have one scenario(sequence of steps) in UI and wanted to schedule that particular scenario in jenkens. Is it possible to do it via this tool?

**Comment by rafalSuntimes** [comment] 2015-09-01 18:06
Are you asking if you can test (not performance, but correct logic) of particular events on a website, such as clicking, scrolling, hover effect, etc?

**Comment by swapnaadusumilli** [comment] 2015-09-01 18:07
@rafalSuntimes yes correct logic.

**Comment by rafalSuntimes** [comment] 2015-09-01 18:14
Sitespeed.io library is a very good web performance tool. I am not a creator of it, or even a developer, but I would personally not want this library to take on the task you described. There is a separate excellent tool that does just that - Selenium (http://seleniumhq.org).

Selenium utilizes a WebDriver library that makes performing such logic tests very easily. If you have never worked with WebDriver and/or Selenium, I *highly* recommend checking it out. As a QA engineer, I wrote all of our website visual testing using Selenium, and it works flawlessly. 

As a matter of fact, Sitespeed.io connects **to a Selenium Server** to run its 'stuff' in a browser; the server works as a link between Sitespeed.io and Firefox, for example.

Does that help you at all?

**Comment by swapnaadusumilli** [comment] 2015-09-01 18:16
yes. Thanks @rafalSuntimes

**Comment by rafalSuntimes** [comment] 2015-09-01 18:17
no problem.

**Comment by swapnaadusumilli** [comment] 2015-09-01 19:56
@rafalSuntimes Do you have any idea where we can configure the application related configurations like login, etc? I'm using this $sitespeed.io -u http://yoursite.com  --screenshot command for monitoring the UI. Suppose, If my app contains login credentials to login then where we can configure those configurations. Any idea?

**Comment by rafalSuntimes** [comment] 2015-09-01 20:03
If your website has basic HTTP authentication set up, then "--basicAuth <USERNAME:PASSWORD>" is your friend. Otherwise, I think there is no built in option (@soulgalore ?). With Selenium mentioned above, you can simply requests that specific credentials are "typed in" and "enter" button clicked, but Sitespeed.io would not be able to access that site natively.

**Comment by swapnaadusumilli** [comment] 2015-09-01 20:31
@rafalSuntimes and @soulgalore. Not sure why basicAuth is not working. When I used this in my command also, it is not able to login into the UI. Any Idea?

$ sitespeed.io -u http://abc.com  --basicAuth abcstage:Test@123 --screenshot

**Comment by rafalSuntimes** [comment] 2015-09-01 20:33
Not sure. This would be a good separate GitHub issue.

**Comment by swapnaadusumilli** [comment] 2015-09-01 20:36
ok that's fine @rafalSuntimes . Any idea, Is there any community forum for sitespeed.io?

**Comment by rafalSuntimes** [comment] 2015-09-01 20:38
I'm not aware of any, sorry.

**Comment by soulgalore** [comment] 2015-09-07 10:24
Hi @swapnaadusumilli 
sorry for not answering this, been away for some time. About the basic auth: I usually uses http://browserspy.dk/password-ok.php (test/test) to verify that it works. Does it fail in the screenshot part? Or doesn't work at all?

**Comment by soulgalore** [comment] 2016-10-28 09:26
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Closed by soulgalore** 2016-10-28 09:26 UTC
