### ISSUE TITLE
Broken link(s) in results dashbaord when using urls.txt in combination with Aliases

### ISSUE THREAD

**Issue by AntoniusGolly** [sitespeedio/sitespeed.io#3244] opened 2021-01-11 19:59 UTC
# Prerequisits:

This is the command I use:
```
 docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.2.1 urls.txt --cookie remember_web_xxx=eyJpdiI6IkRoXC8wSExZZkIyM0t
```
This is my urls.txt:
```
https://staging.example.org/admin/dashboard Admin_Dashboard
https://staging.example.org/admin/users Admin_Members
```
(according to https://www.sitespeed.io/documentation/sitespeed.io/configuration/)

# Issue
When I navigate through the results on Pages, the links to the subpages are broken:
![image](https://user-images.githubusercontent.com/3856505/104231586-7b236980-544f-11eb-88cc-6beec9d69b7e.png)

There is a mismatch between the URL of the actual Admin_Dashboard Link:
`./2021-01-11-19-31-14/pages/staging_example_org/admin/dashboard/index.html`
and the location where I find the file in my folder:
`./2021-01-11-19-31-14/pages/staging_example_org/Admin_Dashboard/index.html`

**Comment by soulgalore** [comment] 2021-01-11 21:53
Hi @AntoniusGolly thanks for creating the bug report, yep I've broke that when changing the how alias work (alias are now also used in the path-name). I'll have a look and try to fix it tomorrow.

**Comment by soulgalore** [comment] 2021-01-12 04:56
I've fixed this and will release it either tonight or early tomorrow.

**Comment by AntoniusGolly** [comment] 2021-01-12 09:00
Absolutely terrific.

**Comment by soulgalore** [comment] 2021-01-13 02:53
I just released the fix in 16.3.0, please verify that it works for you @AntoniusGolly when you have time!

**Comment by fmacgregor-wt** [comment] 2021-01-13 09:25
@soulgalore I had the same issue and have just run with 16.3 the link from the annotation in grafana works OK, but we have a slack hook and the link from slack has the full url in rather than the alias
e.g. grafana link (works)
https://s3.xxxxxxxxxxxxxx/www.theoutnet.com/20210113-08:21:22.116/pages/www_theoutnet_com/pdp/index.html
slack link
https://s3.xxxxxxxxxxxxxx/www.theoutnet.com/20210113-08:21:22.116/pages/www_theoutnet_com/en-gb/shop/product/17476499599333733/index.html

I assume this is part of the same issue

**Comment by soulgalore** [comment] 2021-01-13 09:44
@fmacgregor-wt can you show me how you add the alias? At the moment its three different ways: inside a script, through the cli and using a file. If I know that its easier for me to reproduce and fix. Thanks!

**Comment by fmacgregor-wt** [comment] 2021-01-13 10:16
I use a url file
`# list of URLs and aliases to run sitespeed.io tests on
# for example, to test the theoutnet home page
# http://www.theoutnet.com/ home
#
https://www.theoutnet.com/ home
https://www.theoutnet.com/en-gb/shop/clothing plp
https://www.theoutnet.com/en-gb/shop/designers/valentino dlp 
https://www.theoutnet.com/en-gb/shop/search/dresses search
https://www.theoutnet.com/en-gb/shop/product/17476499599333733 pdp
https://www.theoutnet.com/en-at/shop/clothing test`

**Comment by soulgalore** [comment] 2021-01-13 10:33
Thanks for sharing @fmacgregor-wt let me fix that tonight.

**Comment by shaqb** [comment] 2021-01-13 14:15
Hi @soulgalore - we have another use case where the alias change is causing issues. From within the 'Pages' section of the HTML report, the links are also not referencing the alias correctly.

![image](https://user-images.githubusercontent.com/19668009/104463299-825e8a80-55a9-11eb-9df6-87f4fefaf950.png)

The aliases are there, but the hyperlink for the reports does not use the alias, so the report is effectively a broken link.

In this example the link is: http:/xxx.xxx.xxx/desktop/www.bottegaveneta.com/2021-01-13-13-35-11/pages/www_bottegaveneta_com/gb/women/onlineboutique/bags/index.html

whereas it should be: http://xxx.xxx.xxx/desktop/www.bottegaveneta.com/2021-01-13-13-35-11/pages/www_bottegaveneta_com/Product_Details_Page/index.html

**Comment by soulgalore** [comment] 2021-01-13 15:10
Hi @shaqb can you share how you add the alias? See https://github.com/sitespeedio/sitespeed.io/issues/3244#issuecomment-759332093

**Comment by shaqb** [comment] 2021-01-13 15:12
Hi @soulgalore - I use a url file.

https://www.bottegaveneta.com/gb Homepage
https://www.bottegaveneta.com/gb/women/onlineboutique/bags Product_List_Page
https://www.bottegaveneta.com/Search/Index?textsearch=bags&siteCode=BOTTEGAVENETA_GB&season=&department=llmnwmn&gender=D%2CU%2CE Search
https://www.bottegaveneta.com/gb/clutch_cod45459788pd.html Product_Details_Page

**Comment by soulgalore** [comment] 2021-01-13 19:40
@shaqb hmm that is strange that works for me. I made a generic fix, when the Docker container is built you can have a bio and see if fixes it. I'll ping the issue when its done.

**Comment by soulgalore** [comment] 2021-01-14 18:39
@shaqb I pushed a new release today, can you check if it works there? @fmacgregor-wt that release also contains a fix for Slack, so if you also can test that would be great! Thanks.

**Comment by shaqb** [comment] 2021-01-14 18:51
Hi @soulgalore - tested and confirmed it’s working now. Thanks for sorting so quickly!

**Comment by AntoniusGolly** [comment] 2021-01-14 19:00
Same here👌
Thanks for the fast response.

**Comment by soulgalore** [comment] 2021-01-14 19:58
Well I broke it so I needed to fix it, isn't that how it works :) Thank you both for testing!

**Comment by fmacgregor-wt** [comment] 2021-01-15 08:25
Hi @soulgalore  yes the slack links are fixed now - thank you

**Closed** 2021-01-15 12:05 UTC
Labels: bug
