### ISSUE TITLE
Firefox visualmetrics are not recorded for long URL, even with alias - [sitespeedio.queuehandler] Error: PageIndex out of range

### ISSUE THREAD

**Issue by washingon** [sitespeedio/sitespeed.io#2425] opened 2019-04-15 23:24 UTC
docker:  sitespeedio/sitespeed.io:8.12.0
  browsers:  firefox and chrome
  script.js
  ubuntu 16.04

When the URL is long (in my case more than 245 characters), visual metrics are not recorded for browser firefox but are recorded for chrome.  Even when alias is used.

In chrome, the visual metrics (first visual change, speed index, last visual change) are shown in the HTML and sent to the graphite.host for all 4 of the alias urls in the script.  
In firefox, the HTML and graphite measures are recorded for the first 3 measure.start alias URLs in the same script but shows 0's for the 4th measure.start and stop()  'update_my_details'.

The script sequence is shown below.  the my-details page that is getting measured has a long hashed url that looks like https://www.mydomain.com/my-details/kjluioiausdofjakdhp797979  (192 characters after /my-details/)    and after clicking update button, the URL changes to different long URL with 192 characters after /my-details.

I also included --verbose output for the firefox run.
The firefox run also includes an error referencing HAR file.    I suspect the file name and path is longer than the linux file name and path size of 255 characters.

```
module.exports = async function(context, commands) {
  try {

                await commands.measure.start('login_page')
                await commands.navigate(
                                'https://www.mydomain.com/login'
                  );
                await commands.measure.stop()

                  await commands.addText.byId('myemail@mydomain.com', 'user');
				  await commands.addText.byId('password', 'password');

                await commands.measure.start('login')
                        await commands.click.byClassNameAndWait('submit_button');
                        await commands.wait.byId('my_page_results',15000)
                await commands.measure.stop()

                // navigate to my-details page
                await commands.measure.start('menu-my-details')
                  await commands.click.byClassNameAndWait('navbar-user');
                  await commands.click.byIdAndWait('my_details');
                  await commands.wait.byId('update_button',30000)
                await commands.measure.stop()

                // click submit on my-detail page and time the refresh
                await commands.measure.start('update_my_details')
                  await commands.click.byIdAndWait('update_button');
                  await commands.wait.byId('update_button',30000)
                await commands.measure.stop()

                return
  } catch (e) {
                context.log.info('in catch');
  }
};

```  
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.12.0 --useHash -b chrome --multi --browsertime.userAgent sitespeed.io click_update.js  -n 1 --graphite.host=${GraphiteHost} --browsertime.visualMetrics --browsertime.visualElements --budget.configPath budget.json -spa --html.showScript
```

```
Google Chrome 74.0.3729.75 beta
Mozilla Firefox 66.0
[2019-04-15 22:09:49] INFO: Versions OS: linux 4.4.0-145-generic nodejs: v10.13.0 sitespeed.io: 8.12.0 browsertime: 4.6.2 coach: 3.3.0
[2019-04-15 22:09:49] INFO: Running tests using Chrome - 1 iteration(s)
[2019-04-15 22:09:50] INFO: Start to measure login_page
[2019-04-15 22:09:51] INFO: Navigating to url https://www.mydomain.com/login iteration 1
[2019-04-15 22:10:05] INFO: Start to measure login
[2019-04-15 22:10:23] INFO: Start to measure menu-my-details
[2019-04-15 22:10:42] INFO: Start to measure update_my_details-150
[2019-04-15 22:11:39] INFO: https://www.mydomain.com/login 16 requests, 170.07 kb, backEndTime: 185ms, firstPaint: 608ms, firstVisualChange: 733ms, DOMContentLoaded: 582ms, Load: 820ms, speedIndex: 738, visualComplete85: 733ms, lastVisualChange: 1s, rumSpeedIndex: 608
[2019-04-15 22:11:39] INFO: https://www.mydomain.com/todo27 requests, 796.20 kb, backEndTime: 398ms, firstPaint: 621ms, firstVisualChange: 100ms, DOMContentLoaded: 1.24s, Load: 1.28s, speedIndex: 1228, visualComplete85: 933ms, lastVisualChange: 3.30s, rumSpeedIndex: 626
[2019-04-15 22:11:39] INFO: https://www.mydomain.com/my-details/eyJpdiI6InPizC9pYkRxM2ROSnFvTmlLSDA1V2FRPT0iLCJ2YWx1ZSI6IlhjeGd6VGNRVm1ZMVFtYVhsbm9zWGc9PSIsIm1hYyI6Ijg5NWFiMTg1YWYzMzI5ZDlkNTc1NjI3YjY0NOiONzViY2YyOWIwMzgwM2U5ZGU3MDI2MjJjOGY3ODRjMDY3NDkifQ== 13 requests, 698.08 kb, backEndTime: 2.43s, firstPaint: 3.05s, firstVisualChange: 133ms, DOMContentLoaded: 4.28s, Load: 4.30s, speedIndex: 4615, visualComplete85: 5.93s, lastVisualChange: 6s, rumSpeedIndex: 3047
[2019-04-15 22:11:39] INFO: https://www.mydomain.com/my-details/eyJpdiI6Imw2WHppbXBDUkNGcnlOYThVQmE5NUE9PSIsInZhbHVlIjoiSVNEV1Zza3QwTjExMTZIb3RmMDJwQT09IiwibWFjIjoiYjdlMzBjNzMzMDQ5YTlmYTk4ZjgwOWFjMDc5YjhiMDQ4Mjk0OTY0YWZmOGJlZmU3NWRmNmViMDMyYzdmZjk4ZiJ9 4 requests, 121.16 kb, backEndTime: 3.98s, firstPaint: 4.29s, firstVisualChange: 4.87s, DOMContentLoaded: 5.16s, Load: 5.18s, speedIndex: 4925, visualComplete85: 4.87s, lastVisualChange: 10.47s, rumSpeedIndex: 4293
[2019-04-15 22:11:40] ERROR: Failing budget timings.SpeedIndex for https://www.mydomain.com/my-details/eyJpdiI6InlvXC9pYkRxM2ROSnFvTmlLSDA1V2FRPT0iLCJ2YWx1ZSI6IlhjeGd6VGNRVm1ZMVFtYVhsbm9zWGc9PSIsIm1hYyI6Ijg5NWFiMTg1YWYzMzI5ZDlkNTc1NjI3YjY0NzgzNzViY2YyOWIwMzgwM2U5ZGU3MDI2MjJjOGY3ODRjMDY3NDkifQ== with value 4615 max limit 3000
[2019-04-15 22:11:40] ERROR: Failing budget timings.SpeedIndex for https://www.mydomain.com/my-details/eyJpdiI6Imw2WHppbXBDUkNGcnlOYThVQmE5NUE9PSIsInZhbHVlIjoiSVNEV1Zza3QwTjExMTZIb3RmMDJwQT09IiwibWFjIjoiYjdlMzBjNzMzMDQ5YTlmYTk4ZjgwOWFjMDc5YjhiMDQ4Mjk0OTY0YWZmOGJlZmU3NWRmNmViMDMyYzdmZjk4ZiJ9 with value 4925 max limit 3000
[2019-04-15 22:11:40] INFO: Budget: 2 working and 2 failing tests
[2019-04-15 22:11:42] INFO: HTML stored in /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-09-49
```

```
`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.12.0 --useHash -b firefox --multi --browsertime.userAgent sitespeed.io click_update.js  -n 1 --graphite.host=${GraphiteHost} --browsertime.visualMetrics --browsertime.visualElements --budget.configPath budget.json -spa --html.showScript --verbose`
```

```
Google Chrome 74.0.3729.75 beta
Mozilla Firefox 66.0
[2019-04-15 22:40:11] INFO: [sitespeedio] Versions OS: linux 4.4.0-145-generic nodejs: v10.13.0 sitespeed.io: 8.12.0 browsertime: 4.6.2 coach: 3.3.0
[2019-04-15 22:40:11] DEBUG: [sitespeedio.plugin.graphite] Setting up Graphite ec2-xx-xx-xx-xxx.compute-1.amazonaws.com:9999 for namespace sitespeed_io.default
[2019-04-15 22:40:11] DEBUG: [browsertime] Running with options: {
  "scripts": [],
  "iterations": 1,
  "delay": 0,
  "videoParams": {
    "addTimer": true,
    "filmstripFullSize": false,
    "createFilmstrip": true,
    "framerate": 30,
    "crf": 23,
    "filmstripQuality": 75
  },
  "statistics": true,
  "browser": "firefox",
  "connectivity": {
    "details": "native",
    "engine": "external"
  },
  "screenshot": true,
  "screenshotParams": {
    "type": "png",
    "png": {
      "compressionLevel": 6
    },
    "jpg": {
      "quality": 80
    },
    "maxSize": 2000
  },
  "viewPort": "1366x708",
  "xvfbParams": {
    "display": 99
  },
  "spa": false,
  "pageCompleteCheckInactivity": false,
  "visualMetrics": true,
  "visualElements": true,
  "video": true,
  "firefox": {
    "nightly": false,
    "beta": false,
    "developer": false,
    "acceptInsecureCerts": false,
    "collectMozLog": false,
    "includeResponseBodies": "none"
  },
  "chrome": {
    "timeline": false,
    "collectNetLog": false,
    "collectConsoleLog": false,
    "cdp": {
      "performance": true
    }
  },
  "headless": false,
  "userAgent": "sitespeed.io",
  "docker": "true",
  "xvfb": "true",
  "pageCompleteWaitTime": 5000,
  "pageLoadStrategy": "normal",
  "useHash": true,
  "verbose": 1,
  "mobile": false,
  "screenshotType": "png",
  "coach": true,
  "resultDir": "/sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11"
}
[2019-04-15 22:40:11] INFO: [browsertime] Running tests using Firefox - 1 iteration(s)
[2019-04-15 22:40:16] INFO: [browsertime.command.measure] Start to measure login_page
[2019-04-15 22:40:16] DEBUG: [browsertime.video] Add orange color
[2019-04-15 22:40:16] DEBUG: [browsertime.video] Started ffmpeg with -hide_banner -video_size 1366x540 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,71 -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 /tmp/browsertime-fxdv5J/x11.mp4
[2019-04-15 22:40:16] INFO: [browsertime.command.measure] Navigating to url https://www.mydomain.com/login iteration 1
[2019-04-15 22:40:17] DEBUG: [browsertime] Waiting for script pageCompleteCheck at most 300000 ms
[2019-04-15 22:40:24] DEBUG: [browsertime.video] Stop screen recording
[2019-04-15 22:40:24] DEBUG: [browsertime.video] Stopped ffmpeg
[2019-04-15 22:40:24] DEBUG: [browsertime.video] Converting video to viewable format with args ["-nostdin","-i","/tmp/browsertime-fxdv5J/x11.mp4","-c:v","libx264","-crf",23,"-preset","medium","-vf","format=yuv420p","/sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/login/data/video/1.mp4"]
[2019-04-15 22:40:28] DEBUG: [browsertime.video] Writing to /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/login/data/video/1.mp4
[2019-04-15 22:40:28] INFO: [browsertime.firefox] Waiting on har-export-trigger to collect the HAR
[2019-04-15 22:40:29] INFO: [browsertime.command.measure] Start to measure login-single_role
[2019-04-15 22:40:29] DEBUG: [browsertime.video] Add orange color
[2019-04-15 22:40:29] DEBUG: [browsertime.video] Started ffmpeg with -hide_banner -video_size 1366x540 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,71 -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 /tmp/browsertime-EaHXuw/x11.mp4
[2019-04-15 22:40:30] DEBUG: [browsertime] Waiting for script pageCompleteCheck at most 300000 ms
[2019-04-15 22:40:38] DEBUG: [browsertime.video] Stop screen recording
[2019-04-15 22:40:38] DEBUG: [browsertime.video] Stopped ffmpeg
[2019-04-15 22:40:38] DEBUG: [browsertime.video] Converting video to viewable format with args ["-nostdin","-i","/tmp/browsertime-EaHXuw/x11.mp4","-c:v","libx264","-crf",23,"-preset","medium","-vf","format=yuv420p","/sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/todo/data/video/1.mp4"]
[2019-04-15 22:40:43] DEBUG: [browsertime.video] Writing to /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/todo/data/video/1.mp4
[2019-04-15 22:40:43] INFO: [browsertime.firefox] Waiting on har-export-trigger to collect the HAR
[2019-04-15 22:40:44] INFO: [browsertime.command.measure] Start to measure menu-my-details
[2019-04-15 22:40:44] DEBUG: [browsertime.video] Add orange color
[2019-04-15 22:40:44] DEBUG: [browsertime.video] Started ffmpeg with -hide_banner -video_size 1366x540 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,71 -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 /tmp/browsertime-sJtc0X/x11.mp4
[2019-04-15 22:40:46] DEBUG: [browsertime] Waiting for script pageCompleteCheck at most 300000 ms
[2019-04-15 22:40:47] DEBUG: [browsertime] Waiting for script pageCompleteCheck at most 300000 ms
[2019-04-15 22:40:47] INFO: [browsertime.command.measure] https://www.mydomain.com/todo has been tested before within the same run, it will get an extra query parameter named browsertime_run. Make sure to use alias to keep track of the URLs
[2019-04-15 22:40:49] DEBUG: [browsertime.video] Stop screen recording
[2019-04-15 22:40:49] DEBUG: [browsertime.video] Stopped ffmpeg
[2019-04-15 22:40:49] DEBUG: [browsertime.video] Converting video to viewable format with args ["-nostdin","-i","/tmp/browsertime-sJtc0X/x11.mp4","-c:v","libx264","-crf",23,"-preset","medium","-vf","format=yuv420p","/sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/todo/query-6bc054f4/data/video/1.mp4"]
[2019-04-15 22:40:53] DEBUG: [browsertime.video] Writing to /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/todo/query-6bc054f4/data/video/1.mp4
[2019-04-15 22:40:53] INFO: [browsertime.firefox] Waiting on har-export-trigger to collect the HAR
[2019-04-15 22:40:54] INFO: [browsertime.command.measure] Start to measure update_my_details-150
[2019-04-15 22:40:54] DEBUG: [browsertime.video] Add orange color
[2019-04-15 22:40:54] DEBUG: [browsertime.video] Started ffmpeg with -hide_banner -video_size 1366x540 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,71 -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 /tmp/browsertime-0zqjjP/x11.mp4
[2019-04-15 22:40:56] DEBUG: [browsertime] Waiting for script pageCompleteCheck at most 300000 ms
[2019-04-15 22:40:57] DEBUG: [browsertime.video] Stop screen recording
[2019-04-15 22:40:57] DEBUG: [browsertime.video] Stopped ffmpeg
[2019-04-15 22:40:57] DEBUG: [browsertime.video] Converting video to viewable format with args ["-nostdin","-i","/tmp/browsertime-0zqjjP/x11.mp4","-c:v","libx264","-crf",23,"-preset","medium","-vf","format=yuv420p","/sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/my-details/eyJpdiI6InRqQmRyQGVRT1NNbGxHVjdOTTdKV2c9PSIsInZhbHVlIjoidmlhTVZMdU51Z0hTQmxET3VPU1YxUT09IiwibWFjIjoiNGU2Yzk3YmZhYzc1YjZmYTAzYWRlYTcyMmNmNWMzZWNlNjQwTaEzOTE2MGY1MTU1MmYyMWM0YTI5MWRjYzk5YyJ9/data/video/1.mp4"]
[2019-04-15 22:40:59] DEBUG: [browsertime.video] Writing to /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/my-details/eyJpdiI6InRqQmRsWGVRT1NNbGxHVjdOTTdKV2c9PSIsInZhbQAlIjoidmlhTVZMdU51Z0hTQmxET3VPU1YxUT09IiwibWFjIjoiPOU2Yzk3YmZhYzc1YjZmYTAzYWRlYTcyoRNmNWMzZWNlNjQwMDEzOTE2MGY1MTU1MmYyMWM0YTI5MWRjYzk5YyJ9/data/video/1.mp4
[2019-04-15 22:41:00] INFO: [browsertime.firefox] Waiting on har-export-trigger to collect the HAR
[2019-04-15 22:41:00] ERROR: [browsertime.firefox] Could not get the HAR from Firefox JavascriptError: ReferenceError: HAR is not defined
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.executeScript()
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.executeAsyncScript (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:891:17)
    at SeleniumRunner.runAsyncScript (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:302:26)
    at FirefoxDelegate.onCollect (/usr/src/app/node_modules/browsertime/lib/firefox/webdriver/firefoxDelegate.js:74:38)
    at Measure.collect (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:249:31)
[2019-04-15 22:41:00] DEBUG: [browsertime] Telling browser to quit.
[2019-04-15 22:41:04] DEBUG: [browsertime.video] Running visualMetrics
[2019-04-15 22:41:04] DEBUG: [browsertime.video] Running visualmetrics.py --dir /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/login/data/video/images/1 --video /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/login/data/video/1.mp4 --orange --perceptual --force --renderignore 5 --json --viewport --herodata /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/1-visualElements.json.gz -q 75 --logfile /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/login/data/video/1.visualmetrics.log -vvvv
[2019-04-15 22:41:13] DEBUG: [browsertime.video] visualmetrics.py output:{"SpeedIndex": 1503, "FirstVisualChange": 1500, "LastVisualChange": 1866, "VisualProgress": "0=0%, 1500=98%, 1533=99%, 1833=99%, 1866=100%", "videoRecordingStart": 534, "PerceptualSpeedIndex": 1507, "LargestImage": 1500}
[2019-04-15 22:41:13] DEBUG: [browsertime.video] Collected metrics {"SpeedIndex":1503,"FirstVisualChange":1500,"LastVisualChange":1866,"VisualProgress":"0=0%, 1500=98%, 1533=99%, 1833=99%, 1866=100%","videoRecordingStart":534,"PerceptualSpeedIndex":1507,"LargestImage":1500}
[2019-04-15 22:41:18] DEBUG: [browsertime.video] Running visualMetrics
[2019-04-15 22:41:18] DEBUG: [browsertime.video] Running visualmetrics.py --dir /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/todo/data/video/images/1 --video /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/todo/data/video/1.mp4 --orange --perceptual --force --renderignore 5 --json --viewport --herodata /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/1-visualElements.json.gz -q 75 --logfile /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/todo/data/video/1.visualmetrics.log -vvvv
[2019-04-15 22:41:36] DEBUG: [browsertime.video] visualmetrics.py output:{"SpeedIndex": 1576, "FirstVisualChange": 1034, "LastVisualChange": 5267, "VisualProgress": "0=0%, 1034=87%, 1134=87%, 1167=87%, 1200=87%, 1234=87%, 1267=87%, 1300=87%, 1334=87%, 1367=87%, 1400=87%, 1434=87%, 1467=87%, 1500=87%, 1534=87%, 1567=87%, 1600=87%, 1634=87%, 1667=87%, 1700=87%, 1734=87%, 1767=87%, 1800=87%, 1834=87%, 1867=87%, 1900=87%, 1934=87%, 1967=87%, 2000=87%, 2034=87%, 2067=87%, 2100=87%, 2134=87%, 2167=87%, 2200=87%, 2234=87%, 2267=87%, 2300=87%, 2334=87%, 2367=87%, 2400=87%, 2434=87%, 2467=87%, 2500=87%, 2534=87%, 2567=87%, 2600=87%, 2634=87%, 2667=87%, 2700=87%, 2734=87%, 2800=87%, 2834=87%, 2900=87%, 2934=87%, 3000=87%, 3034=87%, 3100=87%, 3134=87%, 3167=87%, 3200=87%, 3234=87%, 3267=87%, 3300=87%, 3334=87%, 3367=92%, 3400=89%, 3434=92%, 3467=90%, 3500=90%, 3534=89%, 3567=88%, 3600=88%, 3634=88%, 3667=87%, 3700=87%, 3734=87%, 5267=100%", "videoRecordingStart": 500, "PerceptualSpeedIndex": 1676, "LargestImage": 3634}
[2019-04-15 22:41:36] DEBUG: [browsertime.video] Collected metrics {"SpeedIndex":1576,"FirstVisualChange":1034,"LastVisualChange":5267,"VisualProgress":"0=0%, 1034=87%, 1134=87%, 1167=87%, 1200=87%, 1234=87%, 1267=87%, 1300=87%, 1334=87%, 1367=87%, 1400=87%, 1434=87%, 1467=87%, 1500=87%, 1534=87%, 1567=87%, 1600=87%, 1634=87%, 1667=87%, 1700=87%, 1734=87%, 1767=87%, 1800=87%, 1834=87%, 1867=87%, 1900=87%, 1934=87%, 1967=87%, 2000=87%, 2034=87%, 2067=87%, 2100=87%, 2134=87%, 2167=87%, 2200=87%, 2234=87%, 2267=87%, 2300=87%, 2334=87%, 2367=87%, 2400=87%, 2434=87%, 2467=87%, 2500=87%, 2534=87%, 2567=87%, 2600=87%, 2634=87%, 2667=87%, 2700=87%, 2734=87%, 2800=87%, 2834=87%, 2900=87%, 2934=87%, 3000=87%, 3034=87%, 3100=87%, 3134=87%, 3167=87%, 3200=87%, 3234=87%, 3267=87%, 3300=87%, 3334=87%, 3367=92%, 3400=89%, 3434=92%, 3467=90%, 3500=90%, 3534=89%, 3567=88%, 3600=88%, 3634=88%, 3667=87%, 3700=87%, 3734=87%, 5267=100%","videoRecordingStart":500,"PerceptualSpeedIndex":1676,"LargestImage":3634}
[2019-04-15 22:41:39] DEBUG: [browsertime.video] Running visualMetrics
[2019-04-15 22:41:39] DEBUG: [browsertime.video] Running visualmetrics.py --dir /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/todo/query-6bc054f4/data/video/images/1 --video /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/todo/query-6bc054f4/data/video/1.mp4 --orange --perceptual --force --renderignore 5 --json --viewport --herodata /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/1-visualElements.json.gz -q 75 --logfile /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/todo/query-6bc054f4/data/video/1.visualmetrics.log -vvvv
[2019-04-15 22:41:42] DEBUG: [browsertime.video] visualmetrics.py output:{"SpeedIndex": 189, "FirstVisualChange": 167, "LastVisualChange": 1267, "VisualProgress": "0=0%, 167=98%, 1267=100%", "videoRecordingStart": 500, "PerceptualSpeedIndex": 187, "LargestImage": 0}
[2019-04-15 22:41:42] DEBUG: [browsertime.video] Collected metrics {"SpeedIndex":189,"FirstVisualChange":167,"LastVisualChange":1267,"VisualProgress":"0=0%, 167=98%, 1267=100%","videoRecordingStart":500,"PerceptualSpeedIndex":187,"LargestImage":0}
[2019-04-15 22:41:45] DEBUG: [browsertime.video] Running visualMetrics
[2019-04-15 22:41:45] DEBUG: [browsertime.video] Running visualmetrics.py --dir /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/my-details/eyJpdiI6InRqQmRsWGVRT1NNbGxHVjdOTTdKV2c9PSIsInZhbHVlIjoidmlhZYZMdU51Z0hTQmxET3VPU1YxUT09IiwibqtjIjoiNGU2Yzk3YmZhYzc1YjZmYTAzYWRlYTcyMmNmNWMzZWNlNjQwMDTqOTE2MGY1MTU1MmYyMWM0YTI5MWRjYzk5YyJ9/data/video/images/1 --video /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/my-details/eyJpdiI6InRqQmRsWGVRT1NNbGxHVjdOTTdKV2c9PSIsInZhbHVlIjoidmlhZYZMdU51Z0hTQmxET3VPU1YxUT09IiwibqtjIjoiNGU2Yzk3YmZhYzc1YjZmYTAzYWRlYTcyMmNmNWMzZWNlNjQwMDTqOTE2MGY1MTU1MmYyMWM0YTI5MWRjYzk5YyJ9/data/video/1.mp4 --orange --perceptual --force --renderignore 5 --json --viewport --herodata /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/1-visualElements.json.gz -q 75 --logfile /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11/pages/www.mydomain.com/my-details/eyJpdiI6InRqQmRsWGVRT1NNbGxHVjdOTTdKV2c9PSIsInZhbHVlIjoidmlhZYZMdU51Z0hTQmxET3VPU1YxUT09IiwibqtjIjoiNGU2Yzk3YmZhYzc1YjZmYTAzYWRlYTcyMmNmNWMzZWNlNjQwMDTqOTE2MGY1MTU1MmYyMWM0YTI5MWRjYzk5YyJ9/data/video/1.visualmetrics.log -vvvv
[2019-04-15 22:41:47] DEBUG: [browsertime.video] visualmetrics.py output:{"SpeedIndex": 0, "FirstVisualChange": 0, "LastVisualChange": 0, "videoRecordingStart": 500, "PerceptualSpeedIndex": 0, "VisualProgress": "0=100%", "VisuallyComplete": 0}
[2019-04-15 22:41:47] DEBUG: [browsertime.video] Collected metrics {"SpeedIndex":0,"FirstVisualChange":0,"LastVisualChange":0,"videoRecordingStart":500,"PerceptualSpeedIndex":0,"VisualProgress":"0=100%","VisuallyComplete":0}
[2019-04-15 22:41:50] DEBUG: [browsertime] Telling browser to quit.
[2019-04-15 22:41:50] ERROR: [sitespeedio.queuehandler] TypeError: Cannot set property '_meta' of undefined
    at Object.addExtrasToHAR (/usr/src/app/node_modules/browsertime/lib/support/har/index.js:145:34)
    at addExtraFieldsToHar (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:69:21)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:173:7)
[2019-04-15 22:41:50] DEBUG: [plugin.browsertime] Generate summary metrics from Browsertime
[2019-04-15 22:41:50] DEBUG: [plugin.coach] Generate summary metrics from the Coach
[2019-04-15 22:41:50] DEBUG: [plugin.pagexray] Generate summary metrics from PageXray
[2019-04-15 22:41:50] INFO: [sitespeedio.plugin.budget] Budget: 0 working and 0 failing tests
[2019-04-15 22:41:50] DEBUG: [sitespeedio.plugin.html] Render HTML for 0 page(s)
[2019-04-15 22:41:50] DEBUG: [sitespeedio.plugin.html] Render summary page pages
[2019-04-15 22:41:51] DEBUG: [sitespeedio.plugin.html] Render summary page index
[2019-04-15 22:41:51] DEBUG: [sitespeedio.plugin.html] Render summary page detailed
[2019-04-15 22:41:51] DEBUG: [sitespeedio.plugin.html] Render summary page domains
[2019-04-15 22:41:51] DEBUG: [sitespeedio.plugin.html] Render summary page assets
[2019-04-15 22:41:51] DEBUG: [sitespeedio.plugin.html] Render summary page toplist
[2019-04-15 22:41:52] DEBUG: [sitespeedio.plugin.html] Render summary page scripts
[2019-04-15 22:41:52] DEBUG: [sitespeedio.plugin.html] Render summary page budget
[2019-04-15 22:41:52] DEBUG: [sitespeedio.plugin.html] Render summary page help
[2019-04-15 22:41:52] INFO: [sitespeedio.plugin.html] HTML stored in /sitespeed.io/sitespeed-result/click_update_js/2019-04-15-22-40-11
```

**Comment by soulgalore** [comment] 2019-04-16 05:22
Hi @washingon thanks for creating the issue. So it must be some kind of filename issue then for the video, let me try and see if I can reproduce.

Best
Peter

**Comment by washingon** [comment] 2019-04-21 19:09
@soulgalore are you able to reproduce ?

**Comment by soulgalore** [comment] 2019-04-21 19:41
I haven't tried, do you have a URL I can use to test @washingon ?

**Comment by washingon** [comment] 2019-04-22 11:38
I just ran several sequences and think that the issue for firefox occurs when the page with long url has been visited previously.  chrome handles the sequence.

I don't have a public url that I can share to demonstrate for you.

**Comment by skhilko** [comment] 2019-06-25 17:42
The error trace looks the same as in https://github.com/sitespeedio/browsertime/issues/847

**Comment by soulgalore** [comment] 2019-06-28 12:32
At the moment you need to either navigate or make one request between start/stop for it to work.

Best
Peter

**Comment by soulgalore** [comment] 2019-11-18 00:15
Closing since we never got any feedback.

**Closed by soulgalore** 2019-11-18 00:15 UTC
Labels: bug, need more info
