### ISSUE TITLE
analysisstorer plugins throwing error

### ISSUE THREAD

**Issue by norbybaru** [sitespeedio/sitespeed.io#3321] opened 2021-03-25 09:38 UTC
I am getting this error when I enable `analysisstorer` plugin. I am not sure why it failing. `--plugins.add analysisstorer` I am running docker setup

```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (fs.js:1436:5)
    at go$writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:139:14)
    at Object.writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:136:12)
    at /usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:10:14
    at new Promise (<anonymous>)
    at Object.writeFile (/usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:7:14)
    at write (/usr/src/app/lib/core/resultsStorage/storageManager.js:15:13)
    at /usr/src/app/lib/core/resultsStorage/storageManager.js:40:9
```

**Comment by soulgalore** [comment] 2021-03-25 09:47
Hi @norbybaru do you have any more information on how you run or does it fails with a simple test? I wanna see how I can reproduce, it looks like some data is passed on in the wrong format.

**Comment by norbybaru** [comment] 2021-03-25 09:54
Hmm it fails with a simple test. On production we have few custom changes but on my local it still fails with simple test with just 1 url.

**Comment by norbybaru** [comment] 2021-03-25 09:55
I am not sure if this will help but I am pretty much runs this script

```bash
#!/bin/bash

# We use the autobuild to always test our new functionality. But YOU should not do that!
# Instead use the latest tagged version as the next row
DOCKER_CONTAINER=sitespeedio/sitespeed.io:16.10.3-plus1
#DOCKER_CONTAINER=sitespeedio/sitespeed.io-autobuild:main
DOCKER_SETUP="--cap-add=NET_ADMIN  --shm-size=2g --rm -v "$(pwd)"/config/:/config -v "$(pwd)":/sitespeed.io -v /etc/localtime:/etc/localtime:ro -e MAX_OLD_SPACE_SIZE=3072 --network=sitespeed-dashboard_default"
CONFIG="--config /sitespeed.io/config"
#BROWSERS=(chrome firefox)
PLUGINS_LOADER="--plugins.add analysisstorer --plugins.add /lighthouse"
BROWSERS=(chrome)

# We loop through all directories we have
# We run many tests to verify the functionality of sitespeed.io and you can simplify this by
# removing things you don't need!

for url in tests/$TEST/desktop/urls/*.txt ; do
    [ -e "$url" ] || continue
    for browser in "${BROWSERS[@]}" ; do
        POTENTIAL_CONFIG="./config/$(basename ${url%%.*}).json"
        [[ -f "$POTENTIAL_CONFIG" ]] && CONFIG_FILE="$(basename ${url%.*}).json" || CONFIG_FILE="desktopWithExtras.json"
        echo "testing desktop"
        echo "potential config file $POTENTIAL_CONFIG"
        echo "using config file $CONFIG_FILE"
        NAMESPACE="--graphite.namespace sitespeed_io.$(basename ${url%%.*})"
        docker run $DOCKER_SETUP $DOCKER_CONTAINER $NAMESPACE $CONFIG/$CONFIG_FILE -b $browser $url $PLUGINS_LOADER
        control
    done
done


for url in tests/$TEST/emulatedMobile/urls/*.txt ; do
    [ -e "$url" ] || continue
    POTENTIAL_CONFIG="./config/$(basename ${url%%.*}).json"
    [[ -f "$POTENTIAL_CONFIG" ]] && CONFIG_FILE="$(basename ${url%.*}).json" || CONFIG_FILE="emulatedMobile.json"
    echo "testing emulatedMobile"
    echo "potential config file $POTENTIAL_CONFIG"
    echo "using config file $CONFIG_FILE"
    NAMESPACE="--graphite.namespace sitespeed_io.$(basename ${url%%.*})"
    docker run $DOCKER_SETUP $DOCKER_CONTAINER $NAMESPACE $CONFIG/$CONFIG_FILE $url $PLUGINS_LOADER
    control
done


docker volume prune -f
# docker system prune --all --volumes -f
sleep 20

```

**Comment by soulgalore** [comment] 2021-03-25 10:07
OK then I guess it comes from the Lighthouse plugin, I did a quick try with the other settings and it works locally. Let me try Lighthouse later today.

**Comment by norbybaru** [comment] 2021-03-25 10:41
Ok no problem then. I will see if I can pick anything.

Is there possibly a plugin that can allow one to post let say results of `gpsi` to a webhook after the run? I want to find a way to easy share those results via api or webhook to one of internal tool as well or reporting.

**Comment by soulgalore** [comment] 2021-03-25 12:56
You need to build your own plugin for that. There's a queue where all messages/data is passed around. You can checkout the documentation: https://www.sitespeed.io/documentation/sitespeed.io/plugins/#how-to-create-your-own-plugin

And an example of a simple plugin: https://github.com/sitespeedio/sitespeed.io/blob/main/lib/plugins/analysisstorer/index.js#L39-L68

**Comment by soulgalore** [comment] 2021-04-12 14:35
I tried with the Lighthouse plugin but couldn't reproduce, strange. Closing since there was another way to fix what's needed.

**Closed by soulgalore** 2021-04-12 14:35 UTC
Labels: bug

**Comment by papey** [comment] 2022-03-01 16:41
Hi @soulgalore, I also have this error when I'm using `analysisstorer` + `sustainable` plugin, should I open a new issue ?

Thanks a lot :pray:

**Comment by soulgalore** [comment] 2022-03-01 16:50
@papey yes please, I will have a look later this week.

**Comment by papey** [comment] 2022-03-02 08:37
> @papey I pushed a fix for that error now, it will go out in the next release at the end of this week.

That was quick ! Thanks a lot :+1:
