### ISSUE TITLE
malformed URI error in graphiteCollector.js

### ISSUE THREAD

**Issue by roflmao** [sitespeedio/sitespeed.io#609] opened 2015-03-06 08:01 UTC
Not sure how to give you more data on this..

Command run:

```
sitespeed.io -r /var/www/sitespeed -u 'http://www.abcnyheter.no' -m 5 -d 0 --screenshot -b firefox -n 3 --graphiteData all --graphiteHost localhost --gpsiKey 'xxxxxxxxxxxxxxxxxxxxxxxxxx
```

```
info: OS: 'linux 3.2.0-4-amd64', Node.js: 'v0.10.36', sitespeed.io: '3.1.11', PhantomJS: '1.9.8', java: '1.7.0_75', browsertime: '0.8.26'
```

```
error: Catched an uncaught exception:URIError: URI malformedURIError: URI malformed
    at decodeURIComponent (native)
    at /usr/lib/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:191:49
    at Array.forEach (native)
    at /usr/lib/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:190:25
    at Array.forEach (native)
    at GraphiteCollector._getAssetsStats (/usr/lib/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:188:16)
    at GraphiteCollector._getPageStats (/usr/lib/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:53:22)
    at /usr/lib/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:25:24
    at Array.forEach (native)
    at GraphiteCollector.collect (/usr/lib/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:24:9)

**Comment by soulgalore** [comment] 2015-03-06 08:07
Hey @roflmao ,
could you please give me how you start sitespeed.io with the url:s you test etc, so I can reproduce. If it's a secret you can email me: peter [at] soulgalore [.] com

The problem is one of the URL:s that is tested, need to check what's picked up.

Best
Peter

**Comment by roflmao** [comment] 2015-03-06 08:11
Updated @soulgalore.

**Comment by soulgalore** [comment] 2015-03-06 08:16
thanks, will look at it asap

**Comment by soulgalore** [comment] 2015-03-06 08:35
thanks for the report, I was able to reproduce! I've fixed and working on one more thing, then I will do a release, will ping this thread when it's out (probably within the hour).

**Comment by roflmao** [comment] 2015-03-06 08:40
Excellent! :+1: 
Thanks alot! sitespeed++

**Comment by soulgalore** [comment] 2015-03-06 09:04
now 3.1.12 is available. please ping this thread when you have tested so I can close it if it works :)

**Comment by soulgalore** [comment] 2015-03-09 10:20
closing this, please reopen if you have any issues.

**Closed by soulgalore** 2015-03-09 10:20 UTC

**Comment by roflmao** [comment] 2015-03-09 13:38
Looks excellent!
