### ISSUE TITLE
[SPA] ERROR: Could not find the right index 3 for har

### ISSUE THREAD

**Issue by rockmax-rajat** [sitespeedio/sitespeed.io#2326] opened 2019-02-20 11:56 UTC
Command: sitespeed.io script.js --spa --multi

For script.js and steps to reproduce, please do this:
1.  Copy paste the code mentioned at https://www.sitespeed.io/documentation/sitespeed.io/spa/#example-performance-test-grafana in script.js file
2. Now run the command mentioned above
3. Result: No error occured and html report has been created successfully. This is because after hitting 'commands.measure.start', there was url change.
4. Now just replace this line:
await commands.click.byLinkTextAndWait('Last 30 days');
with:
await commands.click.byClassNameAndWait('navbar-page-btn');
5. Run the command mentioned above again

After step:5, following error occurred:
[2019-02-20 17:07:52] INFO: Versions OS: linux 4.15.0-43-generic nodejs: v10.6.0 sitespeed.io: 8.6.2 browsertime: 4.4.6 coach: 3.2.1
[2019-02-20 17:07:52] INFO: Running tests using Chrome - 3 iteration(s)
[2019-02-20 17:07:52] INFO: Testing url https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1 iteration 1
[2019-02-20 17:08:09] INFO: Start to measure pageTimingMetricsLast30Days
[2019-02-20 17:08:15] INFO: https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1 BackEndTime: 891 DomInteractiveTime: 6319 DomContentLoadedTime: 6319 FirstPaint: 2734 PageLoadTime: 6624
[2019-02-20 17:08:15] INFO: https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1 BackEndTime: 891 DomInteractiveTime: 6319 DomContentLoadedTime: 6319 FirstPaint: 2734 PageLoadTime: 6624
[2019-02-20 17:08:16] INFO: Testing url https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1 iteration 2
[2019-02-20 17:08:30] INFO: Start to measure pageTimingMetricsLast30Days
[2019-02-20 17:08:36] INFO: https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1 BackEndTime: 801 DomInteractiveTime: 4386 DomContentLoadedTime: 4386 FirstPaint: 2118 PageLoadTime: 4712
[2019-02-20 17:08:36] INFO: https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1 BackEndTime: 801 DomInteractiveTime: 4386 DomContentLoadedTime: 4386 FirstPaint: 2118 PageLoadTime: 4712
[2019-02-20 17:08:36] INFO: Testing url https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1 iteration 3
[2019-02-20 17:08:52] INFO: Start to measure pageTimingMetricsLast30Days
[2019-02-20 17:08:58] INFO: https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1 BackEndTime: 913 DomInteractiveTime: 6157 DomContentLoadedTime: 6157 FirstPaint: 2443 PageLoadTime: 6505
[2019-02-20 17:08:58] INFO: https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1 BackEndTime: 913 DomInteractiveTime: 6157 DomContentLoadedTime: 6157 FirstPaint: 2443 PageLoadTime: 6505
[2019-02-20 17:08:58] INFO: https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1 36 requests, 5630.64 kb, backEndTime: 868ms (±19.78ms), firstPaint: 2.43s (±102.72ms), DOMContentLoaded: 5.62s (±357.44ms), Load: 5.95s (±357.06ms), rumSpeedIndex: 2432 (±102.72) (6 runs)
[2019-02-20 17:08:58] ERROR: Could not find the right index 3 for har for url https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1 
[2019-02-20 17:08:58] ERROR: Error: PageIndex out of range
    at module.exports.pickAPage (/home/rajats/.nvm/versions/node/v10.6.0/lib/node_modules/sitespeed.io/node_modules/webcoach/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/home/rajats/.nvm/versions/node/v10.6.0/lib/node_modules/sitespeed.io/node_modules/webcoach/lib/index.js:130:12)
    at Object.processMessage (/home/rajats/.nvm/versions/node/v10.6.0/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:182:29)
[2019-02-20 17:08:59] INFO: HTML stored in /home/rajats/Rajat/Projects/git/CxTestApp/18Feb/CxTestApp/test/ui/response/urt1_new/sitespeed-result/script_js/2019-02-20-17-07-52

Conclusion:
"ERROR: Could not find the right index <n> for har" error occurs where n is number of iterations.
So, if you run with -n 1 then error will be "ERROR: Could not find the right index 1 for har".
This error occurs if after start() command neither url is changed nor any routes or url params. 

That means if we are not using any routes or url params then we can't measure metrics of single page application's internal workflow between start() and stop().

**Comment by soulgalore** [comment] 2019-02-20 12:03
Hmm what do you plan to measure? With your example you just open up another layer, you need to click on that new layer and actually choose something to trigger a new view in Grafana.

Best
Peter

**Comment by rockmax-rajat** [comment] 2019-02-20 12:30
I have given this script example so as to provide the steps for reproduction.

My use case is to measure metrics of specific user workflows of single page application 
i.e. after opening any url, I wants to measure metrics between some start and end points. Between these start and end points, I will do some SPA operations which sends request and receives response without adding anything in the url.

**Comment by soulgalore** [comment] 2019-02-20 12:44
Yeah but in your example you just open a layer, you don't actually render a new view or do any requests.

**Comment by rockmax-rajat** [comment] 2019-02-20 12:48
Right, but this error is reproducible in my private app even when I rendered a new view with req/resp to server. What I meant to say is that this error is not because of rendering any new view or not, but it is just because the url remains constant even if we render new view(when we do not use routes).

**Comment by soulgalore** [comment] 2019-02-20 13:00
Ah I see. If the the URL is constant that will break because we store the data per URL so then you need to manually add something in the URL so that different views  (see https://www.sitespeed.io/documentation/sitespeed.io/scripting/#test-the-same-page-multiple-times-within-the-same-run). If it's possible to share your exact example its much easier to help :)

Best
Peter

**Comment by rockmax-rajat** [comment] 2019-02-20 14:21
I already tried that hack but it leads me to another error - ERROR: TypeError: Cannot set property '_meta' of undefined.

Script.js:
`module.exports = async function(context, commands) {
 await commands.navigate('https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1');
 try {
 await commands.wait.byTime(1000);
 await commands.measure.start('spa_workflow');
 //Any internal SPA workflow which do not updates the url
 await commands.click.byClassNameAndWait('navbar-page-btn');
 await commands.measure.stop();
 } catch (e) {}
};`

Command: $ sitespeed.io script.js -n 1 --spa --multi

Error:
[2019-02-20 18:06:03] INFO: Versions OS: linux 4.15.0-43-generic nodejs: v10.6.0 sitespeed.io: 8.6.2 browsertime: 4.4.6 coach: 3.2.1
[2019-02-20 18:06:04] INFO: Running tests using Chrome - 1 iteration(s)
[2019-02-20 18:06:04] INFO: Navigating to url https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1 iteration 1
[2019-02-20 18:06:17] INFO: Start to measure pageTimingMetricsLast30Days
[2019-02-20 18:06:23] ERROR: TypeError: Cannot set property '_meta' of undefined
    at Object.addExtrasToHAR (/home/rajats/.nvm/versions/node/v10.6.0/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/har/index.js:145:34)
    at addExtraFieldsToHar (/home/rajats/.nvm/versions/node/v10.6.0/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:67:19)
    at Engine.runByScript (/home/rajats/.nvm/versions/node/v10.6.0/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:164:7)
[2019-02-20 18:06:24] INFO: HTML stored in /home/rajats/sitespeed-result/script_js/2019-02-20-18-06-03

**Comment by soulgalore** [comment] 2019-02-20 19:53
I don't see in your example that you change the URL? So internally it works like this: if the URL in the browser window is the same, we will treat it as the same content. 

If you can share a real example so I can understand or if you can find another site with the same problem, I can try to help. See https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue

Best
Peter

**Comment by rockmax-rajat** [comment] 2019-02-21 07:40
Yes, that was what my question as if we can track metrics between start() and stop() in a SPA where URL don't change (not even routes or url params).

Actually there is no use of sharing my code because url/endpoints are internal and you won't be able to access them. My script is same as mentioned on https://www.sitespeed.io/documentation/sitespeed.io/spa/#example-performance-test-grafana assuming that url didn't changed on clicking at the link 'Last 30 days' and rest everything works as it is like view rendering etc.

**Open question:**
In any application, if we do not updates the url at all, like mentioned above, then how can we measure metrics using sitespeed between any start and end points assuming that during this duration user performs some action like button click which leads to render respective view?

**Comment by soulgalore** [comment] 2019-02-21 14:25
At the moment the sad truth is that if the URL doesn't change when you change view, it will not work.

**Comment by rockmax-rajat** [comment] 2019-02-22 06:27
Thanks a lot @soulgalore for the clarification and looking into the issue. 
Anyways, is it planned in future to support this feature in Sitespeed?

**Comment by soulgalore** [comment] 2019-02-22 06:33
I looked into it briefly a week ago and it will be much work to fix (to change so that everything can be stored by alias instead of the actual URL) so that need to happen in a new major release (9/10/11 etc), so no plans for that right now.

**Comment by soulgalore** [comment] 2019-02-25 09:24
I'm closing this one, the fix for the future is the same as in #2295 and that is storing test based on alias instead of URL, however that is much work and need to come in a major release (even though I think we can do it backwards compatible).

**Closed by soulgalore** 2019-02-25 09:24 UTC
